-- Soal Figural (deret + analogi + matriks 3x3) — engine multi-objek, 40 soal
delete from questions where chapter_id = 'b0000000-0000-4000-8000-061500000000';

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q1-prompt.svg)',
 '![Opsi A](/figural/q1-a.svg)',
 '![Opsi B](/figural/q1-b.svg)',
 '![Opsi C](/figural/q1-c.svg)',
 '![Opsi D](/figural/q1-d.svg)',
 '![Opsi E](/figural/q1-e.svg)',
 'B',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q2-prompt.svg)',
 '![Opsi A](/figural/q2-a.svg)',
 '![Opsi B](/figural/q2-b.svg)',
 '![Opsi C](/figural/q2-c.svg)',
 '![Opsi D](/figural/q2-d.svg)',
 '![Opsi E](/figural/q2-e.svg)',
 'E',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q3-prompt.svg)',
 '![Opsi A](/figural/q3-a.svg)',
 '![Opsi B](/figural/q3-b.svg)',
 '![Opsi C](/figural/q3-c.svg)',
 '![Opsi D](/figural/q3-d.svg)',
 '![Opsi E](/figural/q3-e.svg)',
 'E',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q4-prompt.svg)',
 '![Opsi A](/figural/q4-a.svg)',
 '![Opsi B](/figural/q4-b.svg)',
 '![Opsi C](/figural/q4-c.svg)',
 '![Opsi D](/figural/q4-d.svg)',
 '![Opsi E](/figural/q4-e.svg)',
 'C',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q5-prompt.svg)',
 '![Opsi A](/figural/q5-a.svg)',
 '![Opsi B](/figural/q5-b.svg)',
 '![Opsi C](/figural/q5-c.svg)',
 '![Opsi D](/figural/q5-d.svg)',
 '![Opsi E](/figural/q5-e.svg)',
 'D',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q6-prompt.svg)',
 '![Opsi A](/figural/q6-a.svg)',
 '![Opsi B](/figural/q6-b.svg)',
 '![Opsi C](/figural/q6-c.svg)',
 '![Opsi D](/figural/q6-d.svg)',
 '![Opsi E](/figural/q6-e.svg)',
 'B',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q7-prompt.svg)',
 '![Opsi A](/figural/q7-a.svg)',
 '![Opsi B](/figural/q7-b.svg)',
 '![Opsi C](/figural/q7-c.svg)',
 '![Opsi D](/figural/q7-d.svg)',
 '![Opsi E](/figural/q7-e.svg)',
 'B',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q8-prompt.svg)',
 '![Opsi A](/figural/q8-a.svg)',
 '![Opsi B](/figural/q8-b.svg)',
 '![Opsi C](/figural/q8-c.svg)',
 '![Opsi D](/figural/q8-d.svg)',
 '![Opsi E](/figural/q8-e.svg)',
 'B',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q9-prompt.svg)',
 '![Opsi A](/figural/q9-a.svg)',
 '![Opsi B](/figural/q9-b.svg)',
 '![Opsi C](/figural/q9-c.svg)',
 '![Opsi D](/figural/q9-d.svg)',
 '![Opsi E](/figural/q9-e.svg)',
 'A',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q10-prompt.svg)',
 '![Opsi A](/figural/q10-a.svg)',
 '![Opsi B](/figural/q10-b.svg)',
 '![Opsi C](/figural/q10-c.svg)',
 '![Opsi D](/figural/q10-d.svg)',
 '![Opsi E](/figural/q10-e.svg)',
 'E',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q11-prompt.svg)',
 '![Opsi A](/figural/q11-a.svg)',
 '![Opsi B](/figural/q11-b.svg)',
 '![Opsi C](/figural/q11-c.svg)',
 '![Opsi D](/figural/q11-d.svg)',
 '![Opsi E](/figural/q11-e.svg)',
 'A',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q12-prompt.svg)',
 '![Opsi A](/figural/q12-a.svg)',
 '![Opsi B](/figural/q12-b.svg)',
 '![Opsi C](/figural/q12-c.svg)',
 '![Opsi D](/figural/q12-d.svg)',
 '![Opsi E](/figural/q12-e.svg)',
 'A',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q13-prompt.svg)',
 '![Opsi A](/figural/q13-a.svg)',
 '![Opsi B](/figural/q13-b.svg)',
 '![Opsi C](/figural/q13-c.svg)',
 '![Opsi D](/figural/q13-d.svg)',
 '![Opsi E](/figural/q13-e.svg)',
 'A',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q14-prompt.svg)',
 '![Opsi A](/figural/q14-a.svg)',
 '![Opsi B](/figural/q14-b.svg)',
 '![Opsi C](/figural/q14-c.svg)',
 '![Opsi D](/figural/q14-d.svg)',
 '![Opsi E](/figural/q14-e.svg)',
 'C',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q15-prompt.svg)',
 '![Opsi A](/figural/q15-a.svg)',
 '![Opsi B](/figural/q15-b.svg)',
 '![Opsi C](/figural/q15-c.svg)',
 '![Opsi D](/figural/q15-d.svg)',
 '![Opsi E](/figural/q15-e.svg)',
 'D',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q16-prompt.svg)',
 '![Opsi A](/figural/q16-a.svg)',
 '![Opsi B](/figural/q16-b.svg)',
 '![Opsi C](/figural/q16-c.svg)',
 '![Opsi D](/figural/q16-d.svg)',
 '![Opsi E](/figural/q16-e.svg)',
 'B',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q17-prompt.svg)',
 '![Opsi A](/figural/q17-a.svg)',
 '![Opsi B](/figural/q17-b.svg)',
 '![Opsi C](/figural/q17-c.svg)',
 '![Opsi D](/figural/q17-d.svg)',
 '![Opsi E](/figural/q17-e.svg)',
 'E',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q18-prompt.svg)',
 '![Opsi A](/figural/q18-a.svg)',
 '![Opsi B](/figural/q18-b.svg)',
 '![Opsi C](/figural/q18-c.svg)',
 '![Opsi D](/figural/q18-d.svg)',
 '![Opsi E](/figural/q18-e.svg)',
 'A',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q19-prompt.svg)',
 '![Opsi A](/figural/q19-a.svg)',
 '![Opsi B](/figural/q19-b.svg)',
 '![Opsi C](/figural/q19-c.svg)',
 '![Opsi D](/figural/q19-d.svg)',
 '![Opsi E](/figural/q19-e.svg)',
 'A',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Deret](/figural/q20-prompt.svg)',
 '![Opsi A](/figural/q20-a.svg)',
 '![Opsi B](/figural/q20-b.svg)',
 '![Opsi C](/figural/q20-c.svg)',
 '![Opsi D](/figural/q20-d.svg)',
 '![Opsi E](/figural/q20-e.svg)',
 'E',
 'Tiap objek berubah menurut aturannya sendiri sepanjang deret; jawaban tepat pada semua objek di kotak yang ditanyakan, tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Analogi](/figural/a1-prompt.svg)',
 '![Opsi A](/figural/a1-a.svg)',
 '![Opsi B](/figural/a1-b.svg)',
 '![Opsi C](/figural/a1-c.svg)',
 '![Opsi D](/figural/a1-d.svg)',
 '![Opsi E](/figural/a1-e.svg)',
 'B',
 'Perubahan dari kotak pertama ke kedua adalah transformasi yang sama untuk tiap objek; terapkan transformasi itu pada kotak ketiga untuk mendapatkan jawaban. Tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Analogi](/figural/a2-prompt.svg)',
 '![Opsi A](/figural/a2-a.svg)',
 '![Opsi B](/figural/a2-b.svg)',
 '![Opsi C](/figural/a2-c.svg)',
 '![Opsi D](/figural/a2-d.svg)',
 '![Opsi E](/figural/a2-e.svg)',
 'B',
 'Perubahan dari kotak pertama ke kedua adalah transformasi yang sama untuk tiap objek; terapkan transformasi itu pada kotak ketiga untuk mendapatkan jawaban. Tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Analogi](/figural/a3-prompt.svg)',
 '![Opsi A](/figural/a3-a.svg)',
 '![Opsi B](/figural/a3-b.svg)',
 '![Opsi C](/figural/a3-c.svg)',
 '![Opsi D](/figural/a3-d.svg)',
 '![Opsi E](/figural/a3-e.svg)',
 'B',
 'Perubahan dari kotak pertama ke kedua adalah transformasi yang sama untuk tiap objek; terapkan transformasi itu pada kotak ketiga untuk mendapatkan jawaban. Tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Analogi](/figural/a4-prompt.svg)',
 '![Opsi A](/figural/a4-a.svg)',
 '![Opsi B](/figural/a4-b.svg)',
 '![Opsi C](/figural/a4-c.svg)',
 '![Opsi D](/figural/a4-d.svg)',
 '![Opsi E](/figural/a4-e.svg)',
 'B',
 'Perubahan dari kotak pertama ke kedua adalah transformasi yang sama untuk tiap objek; terapkan transformasi itu pada kotak ketiga untuk mendapatkan jawaban. Tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Analogi](/figural/a5-prompt.svg)',
 '![Opsi A](/figural/a5-a.svg)',
 '![Opsi B](/figural/a5-b.svg)',
 '![Opsi C](/figural/a5-c.svg)',
 '![Opsi D](/figural/a5-d.svg)',
 '![Opsi E](/figural/a5-e.svg)',
 'E',
 'Perubahan dari kotak pertama ke kedua adalah transformasi yang sama untuk tiap objek; terapkan transformasi itu pada kotak ketiga untuk mendapatkan jawaban. Tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Analogi](/figural/a6-prompt.svg)',
 '![Opsi A](/figural/a6-a.svg)',
 '![Opsi B](/figural/a6-b.svg)',
 '![Opsi C](/figural/a6-c.svg)',
 '![Opsi D](/figural/a6-d.svg)',
 '![Opsi E](/figural/a6-e.svg)',
 'B',
 'Perubahan dari kotak pertama ke kedua adalah transformasi yang sama untuk tiap objek; terapkan transformasi itu pada kotak ketiga untuk mendapatkan jawaban. Tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Analogi](/figural/a7-prompt.svg)',
 '![Opsi A](/figural/a7-a.svg)',
 '![Opsi B](/figural/a7-b.svg)',
 '![Opsi C](/figural/a7-c.svg)',
 '![Opsi D](/figural/a7-d.svg)',
 '![Opsi E](/figural/a7-e.svg)',
 'E',
 'Perubahan dari kotak pertama ke kedua adalah transformasi yang sama untuk tiap objek; terapkan transformasi itu pada kotak ketiga untuk mendapatkan jawaban. Tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Analogi](/figural/a8-prompt.svg)',
 '![Opsi A](/figural/a8-a.svg)',
 '![Opsi B](/figural/a8-b.svg)',
 '![Opsi C](/figural/a8-c.svg)',
 '![Opsi D](/figural/a8-d.svg)',
 '![Opsi E](/figural/a8-e.svg)',
 'E',
 'Perubahan dari kotak pertama ke kedua adalah transformasi yang sama untuk tiap objek; terapkan transformasi itu pada kotak ketiga untuk mendapatkan jawaban. Tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Analogi](/figural/a9-prompt.svg)',
 '![Opsi A](/figural/a9-a.svg)',
 '![Opsi B](/figural/a9-b.svg)',
 '![Opsi C](/figural/a9-c.svg)',
 '![Opsi D](/figural/a9-d.svg)',
 '![Opsi E](/figural/a9-e.svg)',
 'D',
 'Perubahan dari kotak pertama ke kedua adalah transformasi yang sama untuk tiap objek; terapkan transformasi itu pada kotak ketiga untuk mendapatkan jawaban. Tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m1-prompt.svg)',
 '![Opsi A](/figural/m1-a.svg)',
 '![Opsi B](/figural/m1-b.svg)',
 '![Opsi C](/figural/m1-c.svg)',
 '![Opsi D](/figural/m1-d.svg)',
 '![Opsi E](/figural/m1-e.svg)',
 'D',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m2-prompt.svg)',
 '![Opsi A](/figural/m2-a.svg)',
 '![Opsi B](/figural/m2-b.svg)',
 '![Opsi C](/figural/m2-c.svg)',
 '![Opsi D](/figural/m2-d.svg)',
 '![Opsi E](/figural/m2-e.svg)',
 'C',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m3-prompt.svg)',
 '![Opsi A](/figural/m3-a.svg)',
 '![Opsi B](/figural/m3-b.svg)',
 '![Opsi C](/figural/m3-c.svg)',
 '![Opsi D](/figural/m3-d.svg)',
 '![Opsi E](/figural/m3-e.svg)',
 'C',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m4-prompt.svg)',
 '![Opsi A](/figural/m4-a.svg)',
 '![Opsi B](/figural/m4-b.svg)',
 '![Opsi C](/figural/m4-c.svg)',
 '![Opsi D](/figural/m4-d.svg)',
 '![Opsi E](/figural/m4-e.svg)',
 'C',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m5-prompt.svg)',
 '![Opsi A](/figural/m5-a.svg)',
 '![Opsi B](/figural/m5-b.svg)',
 '![Opsi C](/figural/m5-c.svg)',
 '![Opsi D](/figural/m5-d.svg)',
 '![Opsi E](/figural/m5-e.svg)',
 'A',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m6-prompt.svg)',
 '![Opsi A](/figural/m6-a.svg)',
 '![Opsi B](/figural/m6-b.svg)',
 '![Opsi C](/figural/m6-c.svg)',
 '![Opsi D](/figural/m6-d.svg)',
 '![Opsi E](/figural/m6-e.svg)',
 'D',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m7-prompt.svg)',
 '![Opsi A](/figural/m7-a.svg)',
 '![Opsi B](/figural/m7-b.svg)',
 '![Opsi C](/figural/m7-c.svg)',
 '![Opsi D](/figural/m7-d.svg)',
 '![Opsi E](/figural/m7-e.svg)',
 'E',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m8-prompt.svg)',
 '![Opsi A](/figural/m8-a.svg)',
 '![Opsi B](/figural/m8-b.svg)',
 '![Opsi C](/figural/m8-c.svg)',
 '![Opsi D](/figural/m8-d.svg)',
 '![Opsi E](/figural/m8-e.svg)',
 'C',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m9-prompt.svg)',
 '![Opsi A](/figural/m9-a.svg)',
 '![Opsi B](/figural/m9-b.svg)',
 '![Opsi C](/figural/m9-c.svg)',
 '![Opsi D](/figural/m9-d.svg)',
 '![Opsi E](/figural/m9-e.svg)',
 'A',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m10-prompt.svg)',
 '![Opsi A](/figural/m10-a.svg)',
 '![Opsi B](/figural/m10-b.svg)',
 '![Opsi C](/figural/m10-c.svg)',
 '![Opsi D](/figural/m10-d.svg)',
 '![Opsi E](/figural/m10-e.svg)',
 'C',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Matriks](/figural/m11-prompt.svg)',
 '![Opsi A](/figural/m11-a.svg)',
 '![Opsi B](/figural/m11-b.svg)',
 '![Opsi C](/figural/m11-c.svg)',
 '![Opsi D](/figural/m11-d.svg)',
 '![Opsi E](/figural/m11-e.svg)',
 'E',
 'Satu objek berubah mengikuti baris, satu mengikuti kolom, satu tetap sebagai jangkar. Sel kosong = keadaan baris ke-3 dan kolom ke-3 sekaligus; tiap pengecoh salah pada satu objek.',
 'hard')
;
