-- Soal Figural (7 tipe) — engine multi-tipe, 210 soal
delete from questions where chapter_id = 'b0000000-0000-4000-8000-061500000000';

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q1-prompt.svg)',
 '![Opsi A](/figural/q1-a.svg)',
 '![Opsi B](/figural/q1-b.svg)',
 '![Opsi C](/figural/q1-c.svg)',
 '![Opsi D](/figural/q1-d.svg)',
 '![Opsi E](/figural/q1-e.svg)',
 'A',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q2-prompt.svg)',
 '![Opsi A](/figural/q2-a.svg)',
 '![Opsi B](/figural/q2-b.svg)',
 '![Opsi C](/figural/q2-c.svg)',
 '![Opsi D](/figural/q2-d.svg)',
 '![Opsi E](/figural/q2-e.svg)',
 'D',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q3-prompt.svg)',
 '![Opsi A](/figural/q3-a.svg)',
 '![Opsi B](/figural/q3-b.svg)',
 '![Opsi C](/figural/q3-c.svg)',
 '![Opsi D](/figural/q3-d.svg)',
 '![Opsi E](/figural/q3-e.svg)',
 'C',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q4-prompt.svg)',
 '![Opsi A](/figural/q4-a.svg)',
 '![Opsi B](/figural/q4-b.svg)',
 '![Opsi C](/figural/q4-c.svg)',
 '![Opsi D](/figural/q4-d.svg)',
 '![Opsi E](/figural/q4-e.svg)',
 'B',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q5-prompt.svg)',
 '![Opsi A](/figural/q5-a.svg)',
 '![Opsi B](/figural/q5-b.svg)',
 '![Opsi C](/figural/q5-c.svg)',
 '![Opsi D](/figural/q5-d.svg)',
 '![Opsi E](/figural/q5-e.svg)',
 'A',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q6-prompt.svg)',
 '![Opsi A](/figural/q6-a.svg)',
 '![Opsi B](/figural/q6-b.svg)',
 '![Opsi C](/figural/q6-c.svg)',
 '![Opsi D](/figural/q6-d.svg)',
 '![Opsi E](/figural/q6-e.svg)',
 'B',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q7-prompt.svg)',
 '![Opsi A](/figural/q7-a.svg)',
 '![Opsi B](/figural/q7-b.svg)',
 '![Opsi C](/figural/q7-c.svg)',
 '![Opsi D](/figural/q7-d.svg)',
 '![Opsi E](/figural/q7-e.svg)',
 'E',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q8-prompt.svg)',
 '![Opsi A](/figural/q8-a.svg)',
 '![Opsi B](/figural/q8-b.svg)',
 '![Opsi C](/figural/q8-c.svg)',
 '![Opsi D](/figural/q8-d.svg)',
 '![Opsi E](/figural/q8-e.svg)',
 'A',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q9-prompt.svg)',
 '![Opsi A](/figural/q9-a.svg)',
 '![Opsi B](/figural/q9-b.svg)',
 '![Opsi C](/figural/q9-c.svg)',
 '![Opsi D](/figural/q9-d.svg)',
 '![Opsi E](/figural/q9-e.svg)',
 'B',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q10-prompt.svg)',
 '![Opsi A](/figural/q10-a.svg)',
 '![Opsi B](/figural/q10-b.svg)',
 '![Opsi C](/figural/q10-c.svg)',
 '![Opsi D](/figural/q10-d.svg)',
 '![Opsi E](/figural/q10-e.svg)',
 'E',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q11-prompt.svg)',
 '![Opsi A](/figural/q11-a.svg)',
 '![Opsi B](/figural/q11-b.svg)',
 '![Opsi C](/figural/q11-c.svg)',
 '![Opsi D](/figural/q11-d.svg)',
 '![Opsi E](/figural/q11-e.svg)',
 'C',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q12-prompt.svg)',
 '![Opsi A](/figural/q12-a.svg)',
 '![Opsi B](/figural/q12-b.svg)',
 '![Opsi C](/figural/q12-c.svg)',
 '![Opsi D](/figural/q12-d.svg)',
 '![Opsi E](/figural/q12-e.svg)',
 'E',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q13-prompt.svg)',
 '![Opsi A](/figural/q13-a.svg)',
 '![Opsi B](/figural/q13-b.svg)',
 '![Opsi C](/figural/q13-c.svg)',
 '![Opsi D](/figural/q13-d.svg)',
 '![Opsi E](/figural/q13-e.svg)',
 'D',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q14-prompt.svg)',
 '![Opsi A](/figural/q14-a.svg)',
 '![Opsi B](/figural/q14-b.svg)',
 '![Opsi C](/figural/q14-c.svg)',
 '![Opsi D](/figural/q14-d.svg)',
 '![Opsi E](/figural/q14-e.svg)',
 'E',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q15-prompt.svg)',
 '![Opsi A](/figural/q15-a.svg)',
 '![Opsi B](/figural/q15-b.svg)',
 '![Opsi C](/figural/q15-c.svg)',
 '![Opsi D](/figural/q15-d.svg)',
 '![Opsi E](/figural/q15-e.svg)',
 'A',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q16-prompt.svg)',
 '![Opsi A](/figural/q16-a.svg)',
 '![Opsi B](/figural/q16-b.svg)',
 '![Opsi C](/figural/q16-c.svg)',
 '![Opsi D](/figural/q16-d.svg)',
 '![Opsi E](/figural/q16-e.svg)',
 'C',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q17-prompt.svg)',
 '![Opsi A](/figural/q17-a.svg)',
 '![Opsi B](/figural/q17-b.svg)',
 '![Opsi C](/figural/q17-c.svg)',
 '![Opsi D](/figural/q17-d.svg)',
 '![Opsi E](/figural/q17-e.svg)',
 'C',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q18-prompt.svg)',
 '![Opsi A](/figural/q18-a.svg)',
 '![Opsi B](/figural/q18-b.svg)',
 '![Opsi C](/figural/q18-c.svg)',
 '![Opsi D](/figural/q18-d.svg)',
 '![Opsi E](/figural/q18-e.svg)',
 'C',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q19-prompt.svg)',
 '![Opsi A](/figural/q19-a.svg)',
 '![Opsi B](/figural/q19-b.svg)',
 '![Opsi C](/figural/q19-c.svg)',
 '![Opsi D](/figural/q19-d.svg)',
 '![Opsi E](/figural/q19-e.svg)',
 'A',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q20-prompt.svg)',
 '![Opsi A](/figural/q20-a.svg)',
 '![Opsi B](/figural/q20-b.svg)',
 '![Opsi C](/figural/q20-c.svg)',
 '![Opsi D](/figural/q20-d.svg)',
 '![Opsi E](/figural/q20-e.svg)',
 'D',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q21-prompt.svg)',
 '![Opsi A](/figural/q21-a.svg)',
 '![Opsi B](/figural/q21-b.svg)',
 '![Opsi C](/figural/q21-c.svg)',
 '![Opsi D](/figural/q21-d.svg)',
 '![Opsi E](/figural/q21-e.svg)',
 'E',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q22-prompt.svg)',
 '![Opsi A](/figural/q22-a.svg)',
 '![Opsi B](/figural/q22-b.svg)',
 '![Opsi C](/figural/q22-c.svg)',
 '![Opsi D](/figural/q22-d.svg)',
 '![Opsi E](/figural/q22-e.svg)',
 'B',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q23-prompt.svg)',
 '![Opsi A](/figural/q23-a.svg)',
 '![Opsi B](/figural/q23-b.svg)',
 '![Opsi C](/figural/q23-c.svg)',
 '![Opsi D](/figural/q23-d.svg)',
 '![Opsi E](/figural/q23-e.svg)',
 'C',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q24-prompt.svg)',
 '![Opsi A](/figural/q24-a.svg)',
 '![Opsi B](/figural/q24-b.svg)',
 '![Opsi C](/figural/q24-c.svg)',
 '![Opsi D](/figural/q24-d.svg)',
 '![Opsi E](/figural/q24-e.svg)',
 'A',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q25-prompt.svg)',
 '![Opsi A](/figural/q25-a.svg)',
 '![Opsi B](/figural/q25-b.svg)',
 '![Opsi C](/figural/q25-c.svg)',
 '![Opsi D](/figural/q25-d.svg)',
 '![Opsi E](/figural/q25-e.svg)',
 'D',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q26-prompt.svg)',
 '![Opsi A](/figural/q26-a.svg)',
 '![Opsi B](/figural/q26-b.svg)',
 '![Opsi C](/figural/q26-c.svg)',
 '![Opsi D](/figural/q26-d.svg)',
 '![Opsi E](/figural/q26-e.svg)',
 'C',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q27-prompt.svg)',
 '![Opsi A](/figural/q27-a.svg)',
 '![Opsi B](/figural/q27-b.svg)',
 '![Opsi C](/figural/q27-c.svg)',
 '![Opsi D](/figural/q27-d.svg)',
 '![Opsi E](/figural/q27-e.svg)',
 'B',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q28-prompt.svg)',
 '![Opsi A](/figural/q28-a.svg)',
 '![Opsi B](/figural/q28-b.svg)',
 '![Opsi C](/figural/q28-c.svg)',
 '![Opsi D](/figural/q28-d.svg)',
 '![Opsi E](/figural/q28-e.svg)',
 'B',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q29-prompt.svg)',
 '![Opsi A](/figural/q29-a.svg)',
 '![Opsi B](/figural/q29-b.svg)',
 '![Opsi C](/figural/q29-c.svg)',
 '![Opsi D](/figural/q29-d.svg)',
 '![Opsi E](/figural/q29-e.svg)',
 'E',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi kotak yang kosong sesuai pola deret.

![Gambar](/figural/q30-prompt.svg)',
 '![Opsi A](/figural/q30-a.svg)',
 '![Opsi B](/figural/q30-b.svg)',
 '![Opsi C](/figural/q30-c.svg)',
 '![Opsi D](/figural/q30-d.svg)',
 '![Opsi E](/figural/q30-e.svg)',
 'B',
 'Tipe Melanjutkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a1-prompt.svg)',
 '![Opsi A](/figural/a1-a.svg)',
 '![Opsi B](/figural/a1-b.svg)',
 '![Opsi C](/figural/a1-c.svg)',
 '![Opsi D](/figural/a1-d.svg)',
 '![Opsi E](/figural/a1-e.svg)',
 'A',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a2-prompt.svg)',
 '![Opsi A](/figural/a2-a.svg)',
 '![Opsi B](/figural/a2-b.svg)',
 '![Opsi C](/figural/a2-c.svg)',
 '![Opsi D](/figural/a2-d.svg)',
 '![Opsi E](/figural/a2-e.svg)',
 'E',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a3-prompt.svg)',
 '![Opsi A](/figural/a3-a.svg)',
 '![Opsi B](/figural/a3-b.svg)',
 '![Opsi C](/figural/a3-c.svg)',
 '![Opsi D](/figural/a3-d.svg)',
 '![Opsi E](/figural/a3-e.svg)',
 'A',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a4-prompt.svg)',
 '![Opsi A](/figural/a4-a.svg)',
 '![Opsi B](/figural/a4-b.svg)',
 '![Opsi C](/figural/a4-c.svg)',
 '![Opsi D](/figural/a4-d.svg)',
 '![Opsi E](/figural/a4-e.svg)',
 'C',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a5-prompt.svg)',
 '![Opsi A](/figural/a5-a.svg)',
 '![Opsi B](/figural/a5-b.svg)',
 '![Opsi C](/figural/a5-c.svg)',
 '![Opsi D](/figural/a5-d.svg)',
 '![Opsi E](/figural/a5-e.svg)',
 'A',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a6-prompt.svg)',
 '![Opsi A](/figural/a6-a.svg)',
 '![Opsi B](/figural/a6-b.svg)',
 '![Opsi C](/figural/a6-c.svg)',
 '![Opsi D](/figural/a6-d.svg)',
 '![Opsi E](/figural/a6-e.svg)',
 'A',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a7-prompt.svg)',
 '![Opsi A](/figural/a7-a.svg)',
 '![Opsi B](/figural/a7-b.svg)',
 '![Opsi C](/figural/a7-c.svg)',
 '![Opsi D](/figural/a7-d.svg)',
 '![Opsi E](/figural/a7-e.svg)',
 'C',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a8-prompt.svg)',
 '![Opsi A](/figural/a8-a.svg)',
 '![Opsi B](/figural/a8-b.svg)',
 '![Opsi C](/figural/a8-c.svg)',
 '![Opsi D](/figural/a8-d.svg)',
 '![Opsi E](/figural/a8-e.svg)',
 'D',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a9-prompt.svg)',
 '![Opsi A](/figural/a9-a.svg)',
 '![Opsi B](/figural/a9-b.svg)',
 '![Opsi C](/figural/a9-c.svg)',
 '![Opsi D](/figural/a9-d.svg)',
 '![Opsi E](/figural/a9-e.svg)',
 'D',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a10-prompt.svg)',
 '![Opsi A](/figural/a10-a.svg)',
 '![Opsi B](/figural/a10-b.svg)',
 '![Opsi C](/figural/a10-c.svg)',
 '![Opsi D](/figural/a10-d.svg)',
 '![Opsi E](/figural/a10-e.svg)',
 'D',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a11-prompt.svg)',
 '![Opsi A](/figural/a11-a.svg)',
 '![Opsi B](/figural/a11-b.svg)',
 '![Opsi C](/figural/a11-c.svg)',
 '![Opsi D](/figural/a11-d.svg)',
 '![Opsi E](/figural/a11-e.svg)',
 'E',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a12-prompt.svg)',
 '![Opsi A](/figural/a12-a.svg)',
 '![Opsi B](/figural/a12-b.svg)',
 '![Opsi C](/figural/a12-c.svg)',
 '![Opsi D](/figural/a12-d.svg)',
 '![Opsi E](/figural/a12-e.svg)',
 'C',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a13-prompt.svg)',
 '![Opsi A](/figural/a13-a.svg)',
 '![Opsi B](/figural/a13-b.svg)',
 '![Opsi C](/figural/a13-c.svg)',
 '![Opsi D](/figural/a13-d.svg)',
 '![Opsi E](/figural/a13-e.svg)',
 'C',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a14-prompt.svg)',
 '![Opsi A](/figural/a14-a.svg)',
 '![Opsi B](/figural/a14-b.svg)',
 '![Opsi C](/figural/a14-c.svg)',
 '![Opsi D](/figural/a14-d.svg)',
 '![Opsi E](/figural/a14-e.svg)',
 'D',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a15-prompt.svg)',
 '![Opsi A](/figural/a15-a.svg)',
 '![Opsi B](/figural/a15-b.svg)',
 '![Opsi C](/figural/a15-c.svg)',
 '![Opsi D](/figural/a15-d.svg)',
 '![Opsi E](/figural/a15-e.svg)',
 'C',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a16-prompt.svg)',
 '![Opsi A](/figural/a16-a.svg)',
 '![Opsi B](/figural/a16-b.svg)',
 '![Opsi C](/figural/a16-c.svg)',
 '![Opsi D](/figural/a16-d.svg)',
 '![Opsi E](/figural/a16-e.svg)',
 'B',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a17-prompt.svg)',
 '![Opsi A](/figural/a17-a.svg)',
 '![Opsi B](/figural/a17-b.svg)',
 '![Opsi C](/figural/a17-c.svg)',
 '![Opsi D](/figural/a17-d.svg)',
 '![Opsi E](/figural/a17-e.svg)',
 'E',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a18-prompt.svg)',
 '![Opsi A](/figural/a18-a.svg)',
 '![Opsi B](/figural/a18-b.svg)',
 '![Opsi C](/figural/a18-c.svg)',
 '![Opsi D](/figural/a18-d.svg)',
 '![Opsi E](/figural/a18-e.svg)',
 'A',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a19-prompt.svg)',
 '![Opsi A](/figural/a19-a.svg)',
 '![Opsi B](/figural/a19-b.svg)',
 '![Opsi C](/figural/a19-c.svg)',
 '![Opsi D](/figural/a19-d.svg)',
 '![Opsi E](/figural/a19-e.svg)',
 'B',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a20-prompt.svg)',
 '![Opsi A](/figural/a20-a.svg)',
 '![Opsi B](/figural/a20-b.svg)',
 '![Opsi C](/figural/a20-c.svg)',
 '![Opsi D](/figural/a20-d.svg)',
 '![Opsi E](/figural/a20-e.svg)',
 'D',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a21-prompt.svg)',
 '![Opsi A](/figural/a21-a.svg)',
 '![Opsi B](/figural/a21-b.svg)',
 '![Opsi C](/figural/a21-c.svg)',
 '![Opsi D](/figural/a21-d.svg)',
 '![Opsi E](/figural/a21-e.svg)',
 'C',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a22-prompt.svg)',
 '![Opsi A](/figural/a22-a.svg)',
 '![Opsi B](/figural/a22-b.svg)',
 '![Opsi C](/figural/a22-c.svg)',
 '![Opsi D](/figural/a22-d.svg)',
 '![Opsi E](/figural/a22-e.svg)',
 'E',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a23-prompt.svg)',
 '![Opsi A](/figural/a23-a.svg)',
 '![Opsi B](/figural/a23-b.svg)',
 '![Opsi C](/figural/a23-c.svg)',
 '![Opsi D](/figural/a23-d.svg)',
 '![Opsi E](/figural/a23-e.svg)',
 'B',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a24-prompt.svg)',
 '![Opsi A](/figural/a24-a.svg)',
 '![Opsi B](/figural/a24-b.svg)',
 '![Opsi C](/figural/a24-c.svg)',
 '![Opsi D](/figural/a24-d.svg)',
 '![Opsi E](/figural/a24-e.svg)',
 'D',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a25-prompt.svg)',
 '![Opsi A](/figural/a25-a.svg)',
 '![Opsi B](/figural/a25-b.svg)',
 '![Opsi C](/figural/a25-c.svg)',
 '![Opsi D](/figural/a25-d.svg)',
 '![Opsi E](/figural/a25-e.svg)',
 'C',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a26-prompt.svg)',
 '![Opsi A](/figural/a26-a.svg)',
 '![Opsi B](/figural/a26-b.svg)',
 '![Opsi C](/figural/a26-c.svg)',
 '![Opsi D](/figural/a26-d.svg)',
 '![Opsi E](/figural/a26-e.svg)',
 'A',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a27-prompt.svg)',
 '![Opsi A](/figural/a27-a.svg)',
 '![Opsi B](/figural/a27-b.svg)',
 '![Opsi C](/figural/a27-c.svg)',
 '![Opsi D](/figural/a27-d.svg)',
 '![Opsi E](/figural/a27-e.svg)',
 'D',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a28-prompt.svg)',
 '![Opsi A](/figural/a28-a.svg)',
 '![Opsi B](/figural/a28-b.svg)',
 '![Opsi C](/figural/a28-c.svg)',
 '![Opsi D](/figural/a28-d.svg)',
 '![Opsi E](/figural/a28-e.svg)',
 'B',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a29-prompt.svg)',
 '![Opsi A](/figural/a29-a.svg)',
 '![Opsi B](/figural/a29-b.svg)',
 '![Opsi C](/figural/a29-c.svg)',
 '![Opsi D](/figural/a29-d.svg)',
 '![Opsi E](/figural/a29-e.svg)',
 'A',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi analogi: A : B = C : ?

![Gambar](/figural/a30-prompt.svg)',
 '![Opsi A](/figural/a30-a.svg)',
 '![Opsi B](/figural/a30-b.svg)',
 '![Opsi C](/figural/a30-c.svg)',
 '![Opsi D](/figural/a30-d.svg)',
 '![Opsi E](/figural/a30-e.svg)',
 'D',
 'Tipe Membandingkan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m1-prompt.svg)',
 '![Opsi A](/figural/m1-a.svg)',
 '![Opsi B](/figural/m1-b.svg)',
 '![Opsi C](/figural/m1-c.svg)',
 '![Opsi D](/figural/m1-d.svg)',
 '![Opsi E](/figural/m1-e.svg)',
 'D',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m2-prompt.svg)',
 '![Opsi A](/figural/m2-a.svg)',
 '![Opsi B](/figural/m2-b.svg)',
 '![Opsi C](/figural/m2-c.svg)',
 '![Opsi D](/figural/m2-d.svg)',
 '![Opsi E](/figural/m2-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m3-prompt.svg)',
 '![Opsi A](/figural/m3-a.svg)',
 '![Opsi B](/figural/m3-b.svg)',
 '![Opsi C](/figural/m3-c.svg)',
 '![Opsi D](/figural/m3-d.svg)',
 '![Opsi E](/figural/m3-e.svg)',
 'B',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m4-prompt.svg)',
 '![Opsi A](/figural/m4-a.svg)',
 '![Opsi B](/figural/m4-b.svg)',
 '![Opsi C](/figural/m4-c.svg)',
 '![Opsi D](/figural/m4-d.svg)',
 '![Opsi E](/figural/m4-e.svg)',
 'C',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m5-prompt.svg)',
 '![Opsi A](/figural/m5-a.svg)',
 '![Opsi B](/figural/m5-b.svg)',
 '![Opsi C](/figural/m5-c.svg)',
 '![Opsi D](/figural/m5-d.svg)',
 '![Opsi E](/figural/m5-e.svg)',
 'C',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m6-prompt.svg)',
 '![Opsi A](/figural/m6-a.svg)',
 '![Opsi B](/figural/m6-b.svg)',
 '![Opsi C](/figural/m6-c.svg)',
 '![Opsi D](/figural/m6-d.svg)',
 '![Opsi E](/figural/m6-e.svg)',
 'C',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m7-prompt.svg)',
 '![Opsi A](/figural/m7-a.svg)',
 '![Opsi B](/figural/m7-b.svg)',
 '![Opsi C](/figural/m7-c.svg)',
 '![Opsi D](/figural/m7-d.svg)',
 '![Opsi E](/figural/m7-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m8-prompt.svg)',
 '![Opsi A](/figural/m8-a.svg)',
 '![Opsi B](/figural/m8-b.svg)',
 '![Opsi C](/figural/m8-c.svg)',
 '![Opsi D](/figural/m8-d.svg)',
 '![Opsi E](/figural/m8-e.svg)',
 'B',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m9-prompt.svg)',
 '![Opsi A](/figural/m9-a.svg)',
 '![Opsi B](/figural/m9-b.svg)',
 '![Opsi C](/figural/m9-c.svg)',
 '![Opsi D](/figural/m9-d.svg)',
 '![Opsi E](/figural/m9-e.svg)',
 'D',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m10-prompt.svg)',
 '![Opsi A](/figural/m10-a.svg)',
 '![Opsi B](/figural/m10-b.svg)',
 '![Opsi C](/figural/m10-c.svg)',
 '![Opsi D](/figural/m10-d.svg)',
 '![Opsi E](/figural/m10-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m11-prompt.svg)',
 '![Opsi A](/figural/m11-a.svg)',
 '![Opsi B](/figural/m11-b.svg)',
 '![Opsi C](/figural/m11-c.svg)',
 '![Opsi D](/figural/m11-d.svg)',
 '![Opsi E](/figural/m11-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m12-prompt.svg)',
 '![Opsi A](/figural/m12-a.svg)',
 '![Opsi B](/figural/m12-b.svg)',
 '![Opsi C](/figural/m12-c.svg)',
 '![Opsi D](/figural/m12-d.svg)',
 '![Opsi E](/figural/m12-e.svg)',
 'E',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m13-prompt.svg)',
 '![Opsi A](/figural/m13-a.svg)',
 '![Opsi B](/figural/m13-b.svg)',
 '![Opsi C](/figural/m13-c.svg)',
 '![Opsi D](/figural/m13-d.svg)',
 '![Opsi E](/figural/m13-e.svg)',
 'E',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m14-prompt.svg)',
 '![Opsi A](/figural/m14-a.svg)',
 '![Opsi B](/figural/m14-b.svg)',
 '![Opsi C](/figural/m14-c.svg)',
 '![Opsi D](/figural/m14-d.svg)',
 '![Opsi E](/figural/m14-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m15-prompt.svg)',
 '![Opsi A](/figural/m15-a.svg)',
 '![Opsi B](/figural/m15-b.svg)',
 '![Opsi C](/figural/m15-c.svg)',
 '![Opsi D](/figural/m15-d.svg)',
 '![Opsi E](/figural/m15-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m16-prompt.svg)',
 '![Opsi A](/figural/m16-a.svg)',
 '![Opsi B](/figural/m16-b.svg)',
 '![Opsi C](/figural/m16-c.svg)',
 '![Opsi D](/figural/m16-d.svg)',
 '![Opsi E](/figural/m16-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m17-prompt.svg)',
 '![Opsi A](/figural/m17-a.svg)',
 '![Opsi B](/figural/m17-b.svg)',
 '![Opsi C](/figural/m17-c.svg)',
 '![Opsi D](/figural/m17-d.svg)',
 '![Opsi E](/figural/m17-e.svg)',
 'E',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m18-prompt.svg)',
 '![Opsi A](/figural/m18-a.svg)',
 '![Opsi B](/figural/m18-b.svg)',
 '![Opsi C](/figural/m18-c.svg)',
 '![Opsi D](/figural/m18-d.svg)',
 '![Opsi E](/figural/m18-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m19-prompt.svg)',
 '![Opsi A](/figural/m19-a.svg)',
 '![Opsi B](/figural/m19-b.svg)',
 '![Opsi C](/figural/m19-c.svg)',
 '![Opsi D](/figural/m19-d.svg)',
 '![Opsi E](/figural/m19-e.svg)',
 'B',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m20-prompt.svg)',
 '![Opsi A](/figural/m20-a.svg)',
 '![Opsi B](/figural/m20-b.svg)',
 '![Opsi C](/figural/m20-c.svg)',
 '![Opsi D](/figural/m20-d.svg)',
 '![Opsi E](/figural/m20-e.svg)',
 'E',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m21-prompt.svg)',
 '![Opsi A](/figural/m21-a.svg)',
 '![Opsi B](/figural/m21-b.svg)',
 '![Opsi C](/figural/m21-c.svg)',
 '![Opsi D](/figural/m21-d.svg)',
 '![Opsi E](/figural/m21-e.svg)',
 'E',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m22-prompt.svg)',
 '![Opsi A](/figural/m22-a.svg)',
 '![Opsi B](/figural/m22-b.svg)',
 '![Opsi C](/figural/m22-c.svg)',
 '![Opsi D](/figural/m22-d.svg)',
 '![Opsi E](/figural/m22-e.svg)',
 'D',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m23-prompt.svg)',
 '![Opsi A](/figural/m23-a.svg)',
 '![Opsi B](/figural/m23-b.svg)',
 '![Opsi C](/figural/m23-c.svg)',
 '![Opsi D](/figural/m23-d.svg)',
 '![Opsi E](/figural/m23-e.svg)',
 'E',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m24-prompt.svg)',
 '![Opsi A](/figural/m24-a.svg)',
 '![Opsi B](/figural/m24-b.svg)',
 '![Opsi C](/figural/m24-c.svg)',
 '![Opsi D](/figural/m24-d.svg)',
 '![Opsi E](/figural/m24-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m25-prompt.svg)',
 '![Opsi A](/figural/m25-a.svg)',
 '![Opsi B](/figural/m25-b.svg)',
 '![Opsi C](/figural/m25-c.svg)',
 '![Opsi D](/figural/m25-d.svg)',
 '![Opsi E](/figural/m25-e.svg)',
 'E',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m26-prompt.svg)',
 '![Opsi A](/figural/m26-a.svg)',
 '![Opsi B](/figural/m26-b.svg)',
 '![Opsi C](/figural/m26-c.svg)',
 '![Opsi D](/figural/m26-d.svg)',
 '![Opsi E](/figural/m26-e.svg)',
 'E',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m27-prompt.svg)',
 '![Opsi A](/figural/m27-a.svg)',
 '![Opsi B](/figural/m27-b.svg)',
 '![Opsi C](/figural/m27-c.svg)',
 '![Opsi D](/figural/m27-d.svg)',
 '![Opsi E](/figural/m27-e.svg)',
 'A',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m28-prompt.svg)',
 '![Opsi A](/figural/m28-a.svg)',
 '![Opsi B](/figural/m28-b.svg)',
 '![Opsi C](/figural/m28-c.svg)',
 '![Opsi D](/figural/m28-d.svg)',
 '![Opsi E](/figural/m28-e.svg)',
 'E',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m29-prompt.svg)',
 '![Opsi A](/figural/m29-a.svg)',
 '![Opsi B](/figural/m29-b.svg)',
 '![Opsi C](/figural/m29-c.svg)',
 '![Opsi D](/figural/m29-d.svg)',
 '![Opsi E](/figural/m29-e.svg)',
 'B',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Lengkapi sel kosong sesuai pola baris & kolom.

![Gambar](/figural/m30-prompt.svg)',
 '![Opsi A](/figural/m30-a.svg)',
 '![Opsi B](/figural/m30-b.svg)',
 '![Opsi C](/figural/m30-c.svg)',
 '![Opsi D](/figural/m30-d.svg)',
 '![Opsi E](/figural/m30-e.svg)',
 'D',
 'Tipe Tebak 9. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r1-prompt.svg)',
 '![Opsi A](/figural/r1-a.svg)',
 '![Opsi B](/figural/r1-b.svg)',
 '![Opsi C](/figural/r1-c.svg)',
 '![Opsi D](/figural/r1-d.svg)',
 '![Opsi E](/figural/r1-e.svg)',
 'D',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r2-prompt.svg)',
 '![Opsi A](/figural/r2-a.svg)',
 '![Opsi B](/figural/r2-b.svg)',
 '![Opsi C](/figural/r2-c.svg)',
 '![Opsi D](/figural/r2-d.svg)',
 '![Opsi E](/figural/r2-e.svg)',
 'B',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r3-prompt.svg)',
 '![Opsi A](/figural/r3-a.svg)',
 '![Opsi B](/figural/r3-b.svg)',
 '![Opsi C](/figural/r3-c.svg)',
 '![Opsi D](/figural/r3-d.svg)',
 '![Opsi E](/figural/r3-e.svg)',
 'E',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r4-prompt.svg)',
 '![Opsi A](/figural/r4-a.svg)',
 '![Opsi B](/figural/r4-b.svg)',
 '![Opsi C](/figural/r4-c.svg)',
 '![Opsi D](/figural/r4-d.svg)',
 '![Opsi E](/figural/r4-e.svg)',
 'C',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r5-prompt.svg)',
 '![Opsi A](/figural/r5-a.svg)',
 '![Opsi B](/figural/r5-b.svg)',
 '![Opsi C](/figural/r5-c.svg)',
 '![Opsi D](/figural/r5-d.svg)',
 '![Opsi E](/figural/r5-e.svg)',
 'B',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r6-prompt.svg)',
 '![Opsi A](/figural/r6-a.svg)',
 '![Opsi B](/figural/r6-b.svg)',
 '![Opsi C](/figural/r6-c.svg)',
 '![Opsi D](/figural/r6-d.svg)',
 '![Opsi E](/figural/r6-e.svg)',
 'C',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r7-prompt.svg)',
 '![Opsi A](/figural/r7-a.svg)',
 '![Opsi B](/figural/r7-b.svg)',
 '![Opsi C](/figural/r7-c.svg)',
 '![Opsi D](/figural/r7-d.svg)',
 '![Opsi E](/figural/r7-e.svg)',
 'B',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r8-prompt.svg)',
 '![Opsi A](/figural/r8-a.svg)',
 '![Opsi B](/figural/r8-b.svg)',
 '![Opsi C](/figural/r8-c.svg)',
 '![Opsi D](/figural/r8-d.svg)',
 '![Opsi E](/figural/r8-e.svg)',
 'A',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r9-prompt.svg)',
 '![Opsi A](/figural/r9-a.svg)',
 '![Opsi B](/figural/r9-b.svg)',
 '![Opsi C](/figural/r9-c.svg)',
 '![Opsi D](/figural/r9-d.svg)',
 '![Opsi E](/figural/r9-e.svg)',
 'A',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r10-prompt.svg)',
 '![Opsi A](/figural/r10-a.svg)',
 '![Opsi B](/figural/r10-b.svg)',
 '![Opsi C](/figural/r10-c.svg)',
 '![Opsi D](/figural/r10-d.svg)',
 '![Opsi E](/figural/r10-e.svg)',
 'D',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r11-prompt.svg)',
 '![Opsi A](/figural/r11-a.svg)',
 '![Opsi B](/figural/r11-b.svg)',
 '![Opsi C](/figural/r11-c.svg)',
 '![Opsi D](/figural/r11-d.svg)',
 '![Opsi E](/figural/r11-e.svg)',
 'D',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r12-prompt.svg)',
 '![Opsi A](/figural/r12-a.svg)',
 '![Opsi B](/figural/r12-b.svg)',
 '![Opsi C](/figural/r12-c.svg)',
 '![Opsi D](/figural/r12-d.svg)',
 '![Opsi E](/figural/r12-e.svg)',
 'E',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r13-prompt.svg)',
 '![Opsi A](/figural/r13-a.svg)',
 '![Opsi B](/figural/r13-b.svg)',
 '![Opsi C](/figural/r13-c.svg)',
 '![Opsi D](/figural/r13-d.svg)',
 '![Opsi E](/figural/r13-e.svg)',
 'C',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r14-prompt.svg)',
 '![Opsi A](/figural/r14-a.svg)',
 '![Opsi B](/figural/r14-b.svg)',
 '![Opsi C](/figural/r14-c.svg)',
 '![Opsi D](/figural/r14-d.svg)',
 '![Opsi E](/figural/r14-e.svg)',
 'B',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r15-prompt.svg)',
 '![Opsi A](/figural/r15-a.svg)',
 '![Opsi B](/figural/r15-b.svg)',
 '![Opsi C](/figural/r15-c.svg)',
 '![Opsi D](/figural/r15-d.svg)',
 '![Opsi E](/figural/r15-e.svg)',
 'E',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r16-prompt.svg)',
 '![Opsi A](/figural/r16-a.svg)',
 '![Opsi B](/figural/r16-b.svg)',
 '![Opsi C](/figural/r16-c.svg)',
 '![Opsi D](/figural/r16-d.svg)',
 '![Opsi E](/figural/r16-e.svg)',
 'A',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r17-prompt.svg)',
 '![Opsi A](/figural/r17-a.svg)',
 '![Opsi B](/figural/r17-b.svg)',
 '![Opsi C](/figural/r17-c.svg)',
 '![Opsi D](/figural/r17-d.svg)',
 '![Opsi E](/figural/r17-e.svg)',
 'B',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r18-prompt.svg)',
 '![Opsi A](/figural/r18-a.svg)',
 '![Opsi B](/figural/r18-b.svg)',
 '![Opsi C](/figural/r18-c.svg)',
 '![Opsi D](/figural/r18-d.svg)',
 '![Opsi E](/figural/r18-e.svg)',
 'E',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r19-prompt.svg)',
 '![Opsi A](/figural/r19-a.svg)',
 '![Opsi B](/figural/r19-b.svg)',
 '![Opsi C](/figural/r19-c.svg)',
 '![Opsi D](/figural/r19-d.svg)',
 '![Opsi E](/figural/r19-e.svg)',
 'B',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r20-prompt.svg)',
 '![Opsi A](/figural/r20-a.svg)',
 '![Opsi B](/figural/r20-b.svg)',
 '![Opsi C](/figural/r20-c.svg)',
 '![Opsi D](/figural/r20-d.svg)',
 '![Opsi E](/figural/r20-e.svg)',
 'A',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r21-prompt.svg)',
 '![Opsi A](/figural/r21-a.svg)',
 '![Opsi B](/figural/r21-b.svg)',
 '![Opsi C](/figural/r21-c.svg)',
 '![Opsi D](/figural/r21-d.svg)',
 '![Opsi E](/figural/r21-e.svg)',
 'C',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r22-prompt.svg)',
 '![Opsi A](/figural/r22-a.svg)',
 '![Opsi B](/figural/r22-b.svg)',
 '![Opsi C](/figural/r22-c.svg)',
 '![Opsi D](/figural/r22-d.svg)',
 '![Opsi E](/figural/r22-e.svg)',
 'B',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r23-prompt.svg)',
 '![Opsi A](/figural/r23-a.svg)',
 '![Opsi B](/figural/r23-b.svg)',
 '![Opsi C](/figural/r23-c.svg)',
 '![Opsi D](/figural/r23-d.svg)',
 '![Opsi E](/figural/r23-e.svg)',
 'A',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r24-prompt.svg)',
 '![Opsi A](/figural/r24-a.svg)',
 '![Opsi B](/figural/r24-b.svg)',
 '![Opsi C](/figural/r24-c.svg)',
 '![Opsi D](/figural/r24-d.svg)',
 '![Opsi E](/figural/r24-e.svg)',
 'E',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r25-prompt.svg)',
 '![Opsi A](/figural/r25-a.svg)',
 '![Opsi B](/figural/r25-b.svg)',
 '![Opsi C](/figural/r25-c.svg)',
 '![Opsi D](/figural/r25-d.svg)',
 '![Opsi E](/figural/r25-e.svg)',
 'B',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r26-prompt.svg)',
 '![Opsi A](/figural/r26-a.svg)',
 '![Opsi B](/figural/r26-b.svg)',
 '![Opsi C](/figural/r26-c.svg)',
 '![Opsi D](/figural/r26-d.svg)',
 '![Opsi E](/figural/r26-e.svg)',
 'B',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r27-prompt.svg)',
 '![Opsi A](/figural/r27-a.svg)',
 '![Opsi B](/figural/r27-b.svg)',
 '![Opsi C](/figural/r27-c.svg)',
 '![Opsi D](/figural/r27-d.svg)',
 '![Opsi E](/figural/r27-e.svg)',
 'E',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r28-prompt.svg)',
 '![Opsi A](/figural/r28-a.svg)',
 '![Opsi B](/figural/r28-b.svg)',
 '![Opsi C](/figural/r28-c.svg)',
 '![Opsi D](/figural/r28-d.svg)',
 '![Opsi E](/figural/r28-e.svg)',
 'E',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r29-prompt.svg)',
 '![Opsi A](/figural/r29-a.svg)',
 '![Opsi B](/figural/r29-b.svg)',
 '![Opsi C](/figural/r29-c.svg)',
 '![Opsi D](/figural/r29-d.svg)',
 '![Opsi E](/figural/r29-e.svg)',
 'E',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih gambar yang merupakan hasil PUTARAN gambar di atas.

![Gambar](/figural/r30-prompt.svg)',
 '![Opsi A](/figural/r30-a.svg)',
 '![Opsi B](/figural/r30-b.svg)',
 '![Opsi C](/figural/r30-c.svg)',
 '![Opsi D](/figural/r30-d.svg)',
 '![Opsi E](/figural/r30-e.svg)',
 'C',
 'Tipe Rotasi. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c1-prompt.svg)',
 '![Opsi A](/figural/c1-a.svg)',
 '![Opsi B](/figural/c1-b.svg)',
 '![Opsi C](/figural/c1-c.svg)',
 '![Opsi D](/figural/c1-d.svg)',
 '![Opsi E](/figural/c1-e.svg)',
 'B',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c2-prompt.svg)',
 '![Opsi A](/figural/c2-a.svg)',
 '![Opsi B](/figural/c2-b.svg)',
 '![Opsi C](/figural/c2-c.svg)',
 '![Opsi D](/figural/c2-d.svg)',
 '![Opsi E](/figural/c2-e.svg)',
 'E',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c3-prompt.svg)',
 '![Opsi A](/figural/c3-a.svg)',
 '![Opsi B](/figural/c3-b.svg)',
 '![Opsi C](/figural/c3-c.svg)',
 '![Opsi D](/figural/c3-d.svg)',
 '![Opsi E](/figural/c3-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c4-prompt.svg)',
 '![Opsi A](/figural/c4-a.svg)',
 '![Opsi B](/figural/c4-b.svg)',
 '![Opsi C](/figural/c4-c.svg)',
 '![Opsi D](/figural/c4-d.svg)',
 '![Opsi E](/figural/c4-e.svg)',
 'A',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c5-prompt.svg)',
 '![Opsi A](/figural/c5-a.svg)',
 '![Opsi B](/figural/c5-b.svg)',
 '![Opsi C](/figural/c5-c.svg)',
 '![Opsi D](/figural/c5-d.svg)',
 '![Opsi E](/figural/c5-e.svg)',
 'B',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c6-prompt.svg)',
 '![Opsi A](/figural/c6-a.svg)',
 '![Opsi B](/figural/c6-b.svg)',
 '![Opsi C](/figural/c6-c.svg)',
 '![Opsi D](/figural/c6-d.svg)',
 '![Opsi E](/figural/c6-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c7-prompt.svg)',
 '![Opsi A](/figural/c7-a.svg)',
 '![Opsi B](/figural/c7-b.svg)',
 '![Opsi C](/figural/c7-c.svg)',
 '![Opsi D](/figural/c7-d.svg)',
 '![Opsi E](/figural/c7-e.svg)',
 'A',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c8-prompt.svg)',
 '![Opsi A](/figural/c8-a.svg)',
 '![Opsi B](/figural/c8-b.svg)',
 '![Opsi C](/figural/c8-c.svg)',
 '![Opsi D](/figural/c8-d.svg)',
 '![Opsi E](/figural/c8-e.svg)',
 'D',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c9-prompt.svg)',
 '![Opsi A](/figural/c9-a.svg)',
 '![Opsi B](/figural/c9-b.svg)',
 '![Opsi C](/figural/c9-c.svg)',
 '![Opsi D](/figural/c9-d.svg)',
 '![Opsi E](/figural/c9-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c10-prompt.svg)',
 '![Opsi A](/figural/c10-a.svg)',
 '![Opsi B](/figural/c10-b.svg)',
 '![Opsi C](/figural/c10-c.svg)',
 '![Opsi D](/figural/c10-d.svg)',
 '![Opsi E](/figural/c10-e.svg)',
 'A',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c11-prompt.svg)',
 '![Opsi A](/figural/c11-a.svg)',
 '![Opsi B](/figural/c11-b.svg)',
 '![Opsi C](/figural/c11-c.svg)',
 '![Opsi D](/figural/c11-d.svg)',
 '![Opsi E](/figural/c11-e.svg)',
 'E',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c12-prompt.svg)',
 '![Opsi A](/figural/c12-a.svg)',
 '![Opsi B](/figural/c12-b.svg)',
 '![Opsi C](/figural/c12-c.svg)',
 '![Opsi D](/figural/c12-d.svg)',
 '![Opsi E](/figural/c12-e.svg)',
 'E',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c13-prompt.svg)',
 '![Opsi A](/figural/c13-a.svg)',
 '![Opsi B](/figural/c13-b.svg)',
 '![Opsi C](/figural/c13-c.svg)',
 '![Opsi D](/figural/c13-d.svg)',
 '![Opsi E](/figural/c13-e.svg)',
 'A',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c14-prompt.svg)',
 '![Opsi A](/figural/c14-a.svg)',
 '![Opsi B](/figural/c14-b.svg)',
 '![Opsi C](/figural/c14-c.svg)',
 '![Opsi D](/figural/c14-d.svg)',
 '![Opsi E](/figural/c14-e.svg)',
 'D',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c15-prompt.svg)',
 '![Opsi A](/figural/c15-a.svg)',
 '![Opsi B](/figural/c15-b.svg)',
 '![Opsi C](/figural/c15-c.svg)',
 '![Opsi D](/figural/c15-d.svg)',
 '![Opsi E](/figural/c15-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c16-prompt.svg)',
 '![Opsi A](/figural/c16-a.svg)',
 '![Opsi B](/figural/c16-b.svg)',
 '![Opsi C](/figural/c16-c.svg)',
 '![Opsi D](/figural/c16-d.svg)',
 '![Opsi E](/figural/c16-e.svg)',
 'B',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c17-prompt.svg)',
 '![Opsi A](/figural/c17-a.svg)',
 '![Opsi B](/figural/c17-b.svg)',
 '![Opsi C](/figural/c17-c.svg)',
 '![Opsi D](/figural/c17-d.svg)',
 '![Opsi E](/figural/c17-e.svg)',
 'D',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c18-prompt.svg)',
 '![Opsi A](/figural/c18-a.svg)',
 '![Opsi B](/figural/c18-b.svg)',
 '![Opsi C](/figural/c18-c.svg)',
 '![Opsi D](/figural/c18-d.svg)',
 '![Opsi E](/figural/c18-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c19-prompt.svg)',
 '![Opsi A](/figural/c19-a.svg)',
 '![Opsi B](/figural/c19-b.svg)',
 '![Opsi C](/figural/c19-c.svg)',
 '![Opsi D](/figural/c19-d.svg)',
 '![Opsi E](/figural/c19-e.svg)',
 'D',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c20-prompt.svg)',
 '![Opsi A](/figural/c20-a.svg)',
 '![Opsi B](/figural/c20-b.svg)',
 '![Opsi C](/figural/c20-c.svg)',
 '![Opsi D](/figural/c20-d.svg)',
 '![Opsi E](/figural/c20-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c21-prompt.svg)',
 '![Opsi A](/figural/c21-a.svg)',
 '![Opsi B](/figural/c21-b.svg)',
 '![Opsi C](/figural/c21-c.svg)',
 '![Opsi D](/figural/c21-d.svg)',
 '![Opsi E](/figural/c21-e.svg)',
 'D',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c22-prompt.svg)',
 '![Opsi A](/figural/c22-a.svg)',
 '![Opsi B](/figural/c22-b.svg)',
 '![Opsi C](/figural/c22-c.svg)',
 '![Opsi D](/figural/c22-d.svg)',
 '![Opsi E](/figural/c22-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c23-prompt.svg)',
 '![Opsi A](/figural/c23-a.svg)',
 '![Opsi B](/figural/c23-b.svg)',
 '![Opsi C](/figural/c23-c.svg)',
 '![Opsi D](/figural/c23-d.svg)',
 '![Opsi E](/figural/c23-e.svg)',
 'E',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c24-prompt.svg)',
 '![Opsi A](/figural/c24-a.svg)',
 '![Opsi B](/figural/c24-b.svg)',
 '![Opsi C](/figural/c24-c.svg)',
 '![Opsi D](/figural/c24-d.svg)',
 '![Opsi E](/figural/c24-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c25-prompt.svg)',
 '![Opsi A](/figural/c25-a.svg)',
 '![Opsi B](/figural/c25-b.svg)',
 '![Opsi C](/figural/c25-c.svg)',
 '![Opsi D](/figural/c25-d.svg)',
 '![Opsi E](/figural/c25-e.svg)',
 'A',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c26-prompt.svg)',
 '![Opsi A](/figural/c26-a.svg)',
 '![Opsi B](/figural/c26-b.svg)',
 '![Opsi C](/figural/c26-c.svg)',
 '![Opsi D](/figural/c26-d.svg)',
 '![Opsi E](/figural/c26-e.svg)',
 'D',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c27-prompt.svg)',
 '![Opsi A](/figural/c27-a.svg)',
 '![Opsi B](/figural/c27-b.svg)',
 '![Opsi C](/figural/c27-c.svg)',
 '![Opsi D](/figural/c27-d.svg)',
 '![Opsi E](/figural/c27-e.svg)',
 'E',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c28-prompt.svg)',
 '![Opsi A](/figural/c28-a.svg)',
 '![Opsi B](/figural/c28-b.svg)',
 '![Opsi C](/figural/c28-c.svg)',
 '![Opsi D](/figural/c28-d.svg)',
 '![Opsi E](/figural/c28-e.svg)',
 'E',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c29-prompt.svg)',
 '![Opsi A](/figural/c29-a.svg)',
 '![Opsi B](/figural/c29-b.svg)',
 '![Opsi C](/figural/c29-c.svg)',
 '![Opsi D](/figural/c29-d.svg)',
 '![Opsi E](/figural/c29-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih hasil pencerminan gambar terhadap garis putus-putus.

![Gambar](/figural/c30-prompt.svg)',
 '![Opsi A](/figural/c30-a.svg)',
 '![Opsi B](/figural/c30-b.svg)',
 '![Opsi C](/figural/c30-c.svg)',
 '![Opsi D](/figural/c30-d.svg)',
 '![Opsi E](/figural/c30-e.svg)',
 'C',
 'Tipe Pencerminan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o1-a.svg)',
 '![Opsi B](/figural/o1-b.svg)',
 '![Opsi C](/figural/o1-c.svg)',
 '![Opsi D](/figural/o1-d.svg)',
 '![Opsi E](/figural/o1-e.svg)',
 'B',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o2-a.svg)',
 '![Opsi B](/figural/o2-b.svg)',
 '![Opsi C](/figural/o2-c.svg)',
 '![Opsi D](/figural/o2-d.svg)',
 '![Opsi E](/figural/o2-e.svg)',
 'C',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o3-a.svg)',
 '![Opsi B](/figural/o3-b.svg)',
 '![Opsi C](/figural/o3-c.svg)',
 '![Opsi D](/figural/o3-d.svg)',
 '![Opsi E](/figural/o3-e.svg)',
 'E',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o4-a.svg)',
 '![Opsi B](/figural/o4-b.svg)',
 '![Opsi C](/figural/o4-c.svg)',
 '![Opsi D](/figural/o4-d.svg)',
 '![Opsi E](/figural/o4-e.svg)',
 'E',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o5-a.svg)',
 '![Opsi B](/figural/o5-b.svg)',
 '![Opsi C](/figural/o5-c.svg)',
 '![Opsi D](/figural/o5-d.svg)',
 '![Opsi E](/figural/o5-e.svg)',
 'C',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o6-a.svg)',
 '![Opsi B](/figural/o6-b.svg)',
 '![Opsi C](/figural/o6-c.svg)',
 '![Opsi D](/figural/o6-d.svg)',
 '![Opsi E](/figural/o6-e.svg)',
 'E',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o7-a.svg)',
 '![Opsi B](/figural/o7-b.svg)',
 '![Opsi C](/figural/o7-c.svg)',
 '![Opsi D](/figural/o7-d.svg)',
 '![Opsi E](/figural/o7-e.svg)',
 'E',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o8-a.svg)',
 '![Opsi B](/figural/o8-b.svg)',
 '![Opsi C](/figural/o8-c.svg)',
 '![Opsi D](/figural/o8-d.svg)',
 '![Opsi E](/figural/o8-e.svg)',
 'A',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o9-a.svg)',
 '![Opsi B](/figural/o9-b.svg)',
 '![Opsi C](/figural/o9-c.svg)',
 '![Opsi D](/figural/o9-d.svg)',
 '![Opsi E](/figural/o9-e.svg)',
 'E',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o10-a.svg)',
 '![Opsi B](/figural/o10-b.svg)',
 '![Opsi C](/figural/o10-c.svg)',
 '![Opsi D](/figural/o10-d.svg)',
 '![Opsi E](/figural/o10-e.svg)',
 'B',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o11-a.svg)',
 '![Opsi B](/figural/o11-b.svg)',
 '![Opsi C](/figural/o11-c.svg)',
 '![Opsi D](/figural/o11-d.svg)',
 '![Opsi E](/figural/o11-e.svg)',
 'B',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o12-a.svg)',
 '![Opsi B](/figural/o12-b.svg)',
 '![Opsi C](/figural/o12-c.svg)',
 '![Opsi D](/figural/o12-d.svg)',
 '![Opsi E](/figural/o12-e.svg)',
 'C',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o13-a.svg)',
 '![Opsi B](/figural/o13-b.svg)',
 '![Opsi C](/figural/o13-c.svg)',
 '![Opsi D](/figural/o13-d.svg)',
 '![Opsi E](/figural/o13-e.svg)',
 'E',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o14-a.svg)',
 '![Opsi B](/figural/o14-b.svg)',
 '![Opsi C](/figural/o14-c.svg)',
 '![Opsi D](/figural/o14-d.svg)',
 '![Opsi E](/figural/o14-e.svg)',
 'D',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o15-a.svg)',
 '![Opsi B](/figural/o15-b.svg)',
 '![Opsi C](/figural/o15-c.svg)',
 '![Opsi D](/figural/o15-d.svg)',
 '![Opsi E](/figural/o15-e.svg)',
 'D',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o16-a.svg)',
 '![Opsi B](/figural/o16-b.svg)',
 '![Opsi C](/figural/o16-c.svg)',
 '![Opsi D](/figural/o16-d.svg)',
 '![Opsi E](/figural/o16-e.svg)',
 'A',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o17-a.svg)',
 '![Opsi B](/figural/o17-b.svg)',
 '![Opsi C](/figural/o17-c.svg)',
 '![Opsi D](/figural/o17-d.svg)',
 '![Opsi E](/figural/o17-e.svg)',
 'E',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o18-a.svg)',
 '![Opsi B](/figural/o18-b.svg)',
 '![Opsi C](/figural/o18-c.svg)',
 '![Opsi D](/figural/o18-d.svg)',
 '![Opsi E](/figural/o18-e.svg)',
 'B',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o19-a.svg)',
 '![Opsi B](/figural/o19-b.svg)',
 '![Opsi C](/figural/o19-c.svg)',
 '![Opsi D](/figural/o19-d.svg)',
 '![Opsi E](/figural/o19-e.svg)',
 'E',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o20-a.svg)',
 '![Opsi B](/figural/o20-b.svg)',
 '![Opsi C](/figural/o20-c.svg)',
 '![Opsi D](/figural/o20-d.svg)',
 '![Opsi E](/figural/o20-e.svg)',
 'C',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o21-a.svg)',
 '![Opsi B](/figural/o21-b.svg)',
 '![Opsi C](/figural/o21-c.svg)',
 '![Opsi D](/figural/o21-d.svg)',
 '![Opsi E](/figural/o21-e.svg)',
 'A',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o22-a.svg)',
 '![Opsi B](/figural/o22-b.svg)',
 '![Opsi C](/figural/o22-c.svg)',
 '![Opsi D](/figural/o22-d.svg)',
 '![Opsi E](/figural/o22-e.svg)',
 'A',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o23-a.svg)',
 '![Opsi B](/figural/o23-b.svg)',
 '![Opsi C](/figural/o23-c.svg)',
 '![Opsi D](/figural/o23-d.svg)',
 '![Opsi E](/figural/o23-e.svg)',
 'C',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o24-a.svg)',
 '![Opsi B](/figural/o24-b.svg)',
 '![Opsi C](/figural/o24-c.svg)',
 '![Opsi D](/figural/o24-d.svg)',
 '![Opsi E](/figural/o24-e.svg)',
 'C',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o25-a.svg)',
 '![Opsi B](/figural/o25-b.svg)',
 '![Opsi C](/figural/o25-c.svg)',
 '![Opsi D](/figural/o25-d.svg)',
 '![Opsi E](/figural/o25-e.svg)',
 'D',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o26-a.svg)',
 '![Opsi B](/figural/o26-b.svg)',
 '![Opsi C](/figural/o26-c.svg)',
 '![Opsi D](/figural/o26-d.svg)',
 '![Opsi E](/figural/o26-e.svg)',
 'C',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o27-a.svg)',
 '![Opsi B](/figural/o27-b.svg)',
 '![Opsi C](/figural/o27-c.svg)',
 '![Opsi D](/figural/o27-d.svg)',
 '![Opsi E](/figural/o27-e.svg)',
 'D',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o28-a.svg)',
 '![Opsi B](/figural/o28-b.svg)',
 '![Opsi C](/figural/o28-c.svg)',
 '![Opsi D](/figural/o28-d.svg)',
 '![Opsi E](/figural/o28-e.svg)',
 'D',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o29-a.svg)',
 '![Opsi B](/figural/o29-b.svg)',
 '![Opsi C](/figural/o29-c.svg)',
 '![Opsi D](/figural/o29-d.svg)',
 '![Opsi E](/figural/o29-e.svg)',
 'D',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Empat gambar adalah figur yang sama diputar; pilih gambar yang berbeda (bukan hasil putaran).',
 '![Opsi A](/figural/o30-a.svg)',
 '![Opsi B](/figural/o30-b.svg)',
 '![Opsi C](/figural/o30-c.svg)',
 '![Opsi D](/figural/o30-d.svg)',
 '![Opsi E](/figural/o30-e.svg)',
 'A',
 'Tipe Berbeda. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s1-prompt.svg)',
 '![Opsi A](/figural/s1-a.svg)',
 '![Opsi B](/figural/s1-b.svg)',
 '![Opsi C](/figural/s1-c.svg)',
 '![Opsi D](/figural/s1-d.svg)',
 '![Opsi E](/figural/s1-e.svg)',
 'C',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s2-prompt.svg)',
 '![Opsi A](/figural/s2-a.svg)',
 '![Opsi B](/figural/s2-b.svg)',
 '![Opsi C](/figural/s2-c.svg)',
 '![Opsi D](/figural/s2-d.svg)',
 '![Opsi E](/figural/s2-e.svg)',
 'D',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s3-prompt.svg)',
 '![Opsi A](/figural/s3-a.svg)',
 '![Opsi B](/figural/s3-b.svg)',
 '![Opsi C](/figural/s3-c.svg)',
 '![Opsi D](/figural/s3-d.svg)',
 '![Opsi E](/figural/s3-e.svg)',
 'D',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s4-prompt.svg)',
 '![Opsi A](/figural/s4-a.svg)',
 '![Opsi B](/figural/s4-b.svg)',
 '![Opsi C](/figural/s4-c.svg)',
 '![Opsi D](/figural/s4-d.svg)',
 '![Opsi E](/figural/s4-e.svg)',
 'B',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s5-prompt.svg)',
 '![Opsi A](/figural/s5-a.svg)',
 '![Opsi B](/figural/s5-b.svg)',
 '![Opsi C](/figural/s5-c.svg)',
 '![Opsi D](/figural/s5-d.svg)',
 '![Opsi E](/figural/s5-e.svg)',
 'E',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s6-prompt.svg)',
 '![Opsi A](/figural/s6-a.svg)',
 '![Opsi B](/figural/s6-b.svg)',
 '![Opsi C](/figural/s6-c.svg)',
 '![Opsi D](/figural/s6-d.svg)',
 '![Opsi E](/figural/s6-e.svg)',
 'E',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s7-prompt.svg)',
 '![Opsi A](/figural/s7-a.svg)',
 '![Opsi B](/figural/s7-b.svg)',
 '![Opsi C](/figural/s7-c.svg)',
 '![Opsi D](/figural/s7-d.svg)',
 '![Opsi E](/figural/s7-e.svg)',
 'C',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s8-prompt.svg)',
 '![Opsi A](/figural/s8-a.svg)',
 '![Opsi B](/figural/s8-b.svg)',
 '![Opsi C](/figural/s8-c.svg)',
 '![Opsi D](/figural/s8-d.svg)',
 '![Opsi E](/figural/s8-e.svg)',
 'B',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s9-prompt.svg)',
 '![Opsi A](/figural/s9-a.svg)',
 '![Opsi B](/figural/s9-b.svg)',
 '![Opsi C](/figural/s9-c.svg)',
 '![Opsi D](/figural/s9-d.svg)',
 '![Opsi E](/figural/s9-e.svg)',
 'B',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s10-prompt.svg)',
 '![Opsi A](/figural/s10-a.svg)',
 '![Opsi B](/figural/s10-b.svg)',
 '![Opsi C](/figural/s10-c.svg)',
 '![Opsi D](/figural/s10-d.svg)',
 '![Opsi E](/figural/s10-e.svg)',
 'B',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s11-prompt.svg)',
 '![Opsi A](/figural/s11-a.svg)',
 '![Opsi B](/figural/s11-b.svg)',
 '![Opsi C](/figural/s11-c.svg)',
 '![Opsi D](/figural/s11-d.svg)',
 '![Opsi E](/figural/s11-e.svg)',
 'B',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s12-prompt.svg)',
 '![Opsi A](/figural/s12-a.svg)',
 '![Opsi B](/figural/s12-b.svg)',
 '![Opsi C](/figural/s12-c.svg)',
 '![Opsi D](/figural/s12-d.svg)',
 '![Opsi E](/figural/s12-e.svg)',
 'D',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s13-prompt.svg)',
 '![Opsi A](/figural/s13-a.svg)',
 '![Opsi B](/figural/s13-b.svg)',
 '![Opsi C](/figural/s13-c.svg)',
 '![Opsi D](/figural/s13-d.svg)',
 '![Opsi E](/figural/s13-e.svg)',
 'C',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s14-prompt.svg)',
 '![Opsi A](/figural/s14-a.svg)',
 '![Opsi B](/figural/s14-b.svg)',
 '![Opsi C](/figural/s14-c.svg)',
 '![Opsi D](/figural/s14-d.svg)',
 '![Opsi E](/figural/s14-e.svg)',
 'E',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s15-prompt.svg)',
 '![Opsi A](/figural/s15-a.svg)',
 '![Opsi B](/figural/s15-b.svg)',
 '![Opsi C](/figural/s15-c.svg)',
 '![Opsi D](/figural/s15-d.svg)',
 '![Opsi E](/figural/s15-e.svg)',
 'C',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s16-prompt.svg)',
 '![Opsi A](/figural/s16-a.svg)',
 '![Opsi B](/figural/s16-b.svg)',
 '![Opsi C](/figural/s16-c.svg)',
 '![Opsi D](/figural/s16-d.svg)',
 '![Opsi E](/figural/s16-e.svg)',
 'B',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s17-prompt.svg)',
 '![Opsi A](/figural/s17-a.svg)',
 '![Opsi B](/figural/s17-b.svg)',
 '![Opsi C](/figural/s17-c.svg)',
 '![Opsi D](/figural/s17-d.svg)',
 '![Opsi E](/figural/s17-e.svg)',
 'D',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s18-prompt.svg)',
 '![Opsi A](/figural/s18-a.svg)',
 '![Opsi B](/figural/s18-b.svg)',
 '![Opsi C](/figural/s18-c.svg)',
 '![Opsi D](/figural/s18-d.svg)',
 '![Opsi E](/figural/s18-e.svg)',
 'A',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s19-prompt.svg)',
 '![Opsi A](/figural/s19-a.svg)',
 '![Opsi B](/figural/s19-b.svg)',
 '![Opsi C](/figural/s19-c.svg)',
 '![Opsi D](/figural/s19-d.svg)',
 '![Opsi E](/figural/s19-e.svg)',
 'B',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s20-prompt.svg)',
 '![Opsi A](/figural/s20-a.svg)',
 '![Opsi B](/figural/s20-b.svg)',
 '![Opsi C](/figural/s20-c.svg)',
 '![Opsi D](/figural/s20-d.svg)',
 '![Opsi E](/figural/s20-e.svg)',
 'A',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s21-prompt.svg)',
 '![Opsi A](/figural/s21-a.svg)',
 '![Opsi B](/figural/s21-b.svg)',
 '![Opsi C](/figural/s21-c.svg)',
 '![Opsi D](/figural/s21-d.svg)',
 '![Opsi E](/figural/s21-e.svg)',
 'E',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s22-prompt.svg)',
 '![Opsi A](/figural/s22-a.svg)',
 '![Opsi B](/figural/s22-b.svg)',
 '![Opsi C](/figural/s22-c.svg)',
 '![Opsi D](/figural/s22-d.svg)',
 '![Opsi E](/figural/s22-e.svg)',
 'B',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s23-prompt.svg)',
 '![Opsi A](/figural/s23-a.svg)',
 '![Opsi B](/figural/s23-b.svg)',
 '![Opsi C](/figural/s23-c.svg)',
 '![Opsi D](/figural/s23-d.svg)',
 '![Opsi E](/figural/s23-e.svg)',
 'A',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s24-prompt.svg)',
 '![Opsi A](/figural/s24-a.svg)',
 '![Opsi B](/figural/s24-b.svg)',
 '![Opsi C](/figural/s24-c.svg)',
 '![Opsi D](/figural/s24-d.svg)',
 '![Opsi E](/figural/s24-e.svg)',
 'E',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s25-prompt.svg)',
 '![Opsi A](/figural/s25-a.svg)',
 '![Opsi B](/figural/s25-b.svg)',
 '![Opsi C](/figural/s25-c.svg)',
 '![Opsi D](/figural/s25-d.svg)',
 '![Opsi E](/figural/s25-e.svg)',
 'C',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s26-prompt.svg)',
 '![Opsi A](/figural/s26-a.svg)',
 '![Opsi B](/figural/s26-b.svg)',
 '![Opsi C](/figural/s26-c.svg)',
 '![Opsi D](/figural/s26-d.svg)',
 '![Opsi E](/figural/s26-e.svg)',
 'A',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s27-prompt.svg)',
 '![Opsi A](/figural/s27-a.svg)',
 '![Opsi B](/figural/s27-b.svg)',
 '![Opsi C](/figural/s27-c.svg)',
 '![Opsi D](/figural/s27-d.svg)',
 '![Opsi E](/figural/s27-e.svg)',
 'A',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s28-prompt.svg)',
 '![Opsi A](/figural/s28-a.svg)',
 '![Opsi B](/figural/s28-b.svg)',
 '![Opsi C](/figural/s28-c.svg)',
 '![Opsi D](/figural/s28-d.svg)',
 '![Opsi E](/figural/s28-e.svg)',
 'E',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s29-prompt.svg)',
 '![Opsi A](/figural/s29-a.svg)',
 '![Opsi B](/figural/s29-b.svg)',
 '![Opsi C](/figural/s29-c.svg)',
 '![Opsi D](/figural/s29-d.svg)',
 '![Opsi E](/figural/s29-e.svg)',
 'E',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard'),
('b0000000-0000-4000-8000-061500000000',
 'Pilih bayangan (siluet hitam) yang sesuai dengan gambar.

![Gambar](/figural/s30-prompt.svg)',
 '![Opsi A](/figural/s30-a.svg)',
 '![Opsi B](/figural/s30-b.svg)',
 '![Opsi C](/figural/s30-c.svg)',
 '![Opsi D](/figural/s30-d.svg)',
 '![Opsi E](/figural/s30-e.svg)',
 'C',
 'Tipe Bayangan. Kunci ditentukan aturan/transformasi soal; tiap pengecoh salah pada satu aspek.',
 'hard')
;
