-- 5 soal per bab untuk Modul Pengelolaan Keuangan Negara (M4)
-- Menggantikan soal-soal lama yang jumlahnya sedikit & tersebar tidak merata.

delete from questions where chapter_id in (
  'b0000000-0000-4000-8000-040100000000',
  'b0000000-0000-4000-8000-040200000000',
  'b0000000-0000-4000-8000-040300000000',
  'b0000000-0000-4000-8000-040400000000',
  'b0000000-0000-4000-8000-040500000000',
  'b0000000-0000-4000-8000-040600000000'
);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values
('b0000000-0000-4000-8000-040100000000', 'Yang dimaksud dengan Pengelolaan Keuangan Negara menurut bahan ajar ini adalah pengelolaan yang dilakukan Pemerintah terhadap sumber-sumber keuangan berupa apa saja?', 'Pendapatan negara, belanja negara, dan sumber keuangan untuk menutup/membiayai defisit', 'Pendapatan negara dan belanja daerah saja', 'Kekayaan negara yang dipisahkan pada BUMN saja', 'Anggaran rutin dan anggaran pembangunan', null, 'A', 'Pengelolaan Keuangan Negara mencakup pendapatan negara, belanja negara, dan sumber keuangan untuk menutup/membiayai kekurangan (defisit) yang mungkin timbul.', 'easy'),
('b0000000-0000-4000-8000-040100000000', 'Dari mana sumber pendapatan negara berasal sesuai kewenangan Pemerintah menurut peraturan perundangan?', 'Utang luar negeri saja', 'Pajak dan bukan pajak', 'Hibah luar negeri saja', 'Privatisasi BUMN saja', null, 'B', 'Pendapatan negara berasal dari pajak dan bukan pajak sesuai kewenangan Pemerintah menurut peraturan perundangan.', 'easy'),
('b0000000-0000-4000-8000-040100000000', 'Agar wewenang dan fungsi Pemerintah dalam pengelolaan keuangan negara terlaksana dengan transparan dan akuntabel, hal ini harus dibatasi oleh peraturan perundangan serta melibatkan persetujuan dan pengawasan dari lembaga apa?', 'Mahkamah Agung', 'Bank Indonesia', 'DPR (legislatif)', 'Badan Pemeriksa Keuangan saja', null, 'C', 'Wewenang dan fungsi Pemerintah dibatasi peraturan perundangan, termasuk persetujuan dan pengawasan oleh legislatif (DPR), agar tercipta transparansi dan akuntabilitas.', 'medium'),
('b0000000-0000-4000-8000-040100000000', 'Kementerian Keuangan berperan strategis dalam pengelolaan keuangan negara sebagai apa?', 'Chief Operational Officer (COO) negara', 'Chief Risk Officer (CRO) negara', 'Chief Executive Officer (CEO) negara', 'Chief Financial Officer (CFO) negara', null, 'D', 'Kementerian Keuangan berperan strategis sebagai Chief Financial Officer (CFO) negara.', 'easy'),
('b0000000-0000-4000-8000-040100000000', 'Manakah cakupan bahan ajar modul Pengelolaan Keuangan Negara yang disebutkan pada Bab Pendahuluan?', 'Maksud & tujuan pengelolaan keuangan negara umum, pengelolaan APBN (pendapatan, belanja, pembiayaan defisit), serta pengawasan dan pertanggungjawaban APBN', 'Hanya pengelolaan APBN tanpa pengawasan', 'Hanya kebijakan moneter Bank Indonesia', 'Hanya siklus penyusunan Rencana Kerja Pemerintah', null, 'A', 'Cakupan bahan ajar mencakup tiga hal: maksud & tujuan pengelolaan keuangan negara umum, pengelolaan APBN (pendapatan, belanja, pembiayaan defisit), dan pengawasan serta pertanggungjawaban APBN.', 'medium'),
('b0000000-0000-4000-8000-040200000000', 'Pengertian Keuangan Negara diatur dalam peraturan perundangan apa?', 'UU Nomor 1 Tahun 2004', 'UU Nomor 17 Tahun 2003 tentang Keuangan Negara', 'UU Nomor 15 Tahun 2004', 'UU Nomor 9 Tahun 2018', null, 'B', 'Dasar hukum pengertian Keuangan Negara adalah UU Nomor 17 Tahun 2003 tentang Keuangan Negara.', 'easy'),
('b0000000-0000-4000-8000-040200000000', 'Menurut penjelasan UU Nomor 17 Tahun 2003, unsur pengertian Keuangan Negara yang menjelaskan bahwa keuangan negara mencakup seluruh objek yang dimiliki/dikuasai Pemerintah dan badan hukum publik lainnya disebut unsur apa?', 'Objek', 'Proses', 'Subjek', 'Tujuan', null, 'C', 'Unsur Subjek menyatakan bahwa seluruh objek keuangan negara yang dimiliki/dikuasai Pemerintah dan badan hukum publik lainnya termasuk dalam pengertian keuangan negara.', 'medium'),
('b0000000-0000-4000-8000-040200000000', 'Kebijakan terkait jumlah uang beredar, cadangan wajib bank, tingkat diskonto, kebijakan kredit dan pasar terbuka, serta kurs valuta asing termasuk dalam subbidang pengelolaan keuangan negara yang mana, dan siapa pelaksananya?', 'Subbidang Fiskal, dilaksanakan oleh Kementerian Keuangan', 'Subbidang Fiskal, dilaksanakan oleh DPR', 'Subbidang Kekayaan Negara Dipisahkan, dilaksanakan oleh BUMN', 'Subbidang Moneter, dilaksanakan oleh Bank Indonesia', null, 'D', 'Subbidang Pengelolaan Moneter berkaitan dengan jumlah uang beredar, cadangan wajib bank, diskonto, kredit, pasar terbuka, dan kurs valas; dilaksanakan oleh Bank Indonesia.', 'medium'),
('b0000000-0000-4000-8000-040200000000', 'Kebijakan counter-cyclical dalam tujuan pengelolaan keuangan negara untuk menjaga stabilitas ekonomi dilakukan dengan cara apa saat resesi?', 'Menaikkan belanja pemerintah dan/atau menurunkan pajak', 'Menurunkan belanja pemerintah dan menaikkan pajak', 'Membiarkan pasar bergerak tanpa intervensi', 'Menaikkan belanja pemerintah dan menaikkan pajak secara bersamaan', null, 'A', 'Kebijakan counter-cyclical melawan arah siklus ekonomi: menaikkan belanja/menurunkan pajak saat resesi, dan sebaliknya saat inflasi tinggi.', 'hard'),
('b0000000-0000-4000-8000-040200000000', 'Berikut ini adalah asas-asas umum pengelolaan keuangan negara, KECUALI:', 'Asas Tahunan', 'Asas Sentralisasi Penuh', 'Asas Universalitas', 'Asas Spesialitas', null, 'B', 'Sembilan asas umum pengelolaan keuangan negara adalah Tahunan, Universalitas, Kesatuan, Spesialitas, Akuntabilitas, Profesionalitas, Proporsionalitas, Keterbukaan, dan Pemeriksaan keuangan. Asas "Sentralisasi Penuh" bukan bagian dari kesembilan asas tersebut.', 'medium'),
('b0000000-0000-4000-8000-040300000000', 'Berapa persen batas maksimal defisit APBN terhadap PDB menurut UU Nomor 17 Tahun 2003?', '2%', '5%', '3%', '60%', null, 'C', 'Batas maksimal defisit APBN terhadap PDB adalah 3% sesuai UU Nomor 17 Tahun 2003. Adapun batas pinjaman untuk membiayai defisit maksimal 60% dari PDB.', 'easy'),
('b0000000-0000-4000-8000-040300000000', 'Pelonggaran batas defisit APBN 3% pada masa pandemi Covid-19 dilakukan melalui peraturan apa?', 'PP Nomor 45 Tahun 2013', 'UU Nomor 33 Tahun 2004', 'UU Nomor 1 Tahun 2004 tentang Perbendaharaan Negara', 'Perppu Nomor 1 Tahun 2020 tentang Kebijakan Keuangan Negara dan Stabilitas Sistem Keuangan untuk Penanganan Pandemi Covid-19', null, 'D', 'Saat pandemi Covid-19, batas defisit 3% dilonggarkan melalui Perppu Nomor 1 Tahun 2020 tentang Kebijakan Keuangan Negara dan Stabilitas Sistem Keuangan untuk Penanganan Pandemi Covid-19.', 'medium'),
('b0000000-0000-4000-8000-040300000000', 'Manakah urutan yang benar dari siklus/tahapan pengelolaan APBN?', 'Perencanaan - Penyusunan - Pembahasan - Penetapan - Pelaksanaan - Pelaporan dan Pencatatan - Pemeriksaan dan Pertanggungjawaban', 'Pelaksanaan - Perencanaan - Penetapan - Pembahasan - Pelaporan - Pemeriksaan', 'Penyusunan - Perencanaan - Pelaksanaan - Pembahasan - Penetapan - Pemeriksaan', 'Pembahasan - Penetapan - Perencanaan - Penyusunan - Pelaksanaan - Pelaporan', null, 'A', 'Siklus APBN terdiri atas 7 tahap berurutan: Perencanaan, Penyusunan, Pembahasan, Penetapan, Pelaksanaan, Pelaporan dan Pencatatan, serta Pemeriksaan dan Pertanggungjawaban.', 'medium'),
('b0000000-0000-4000-8000-040300000000', 'Format APBN mulai berubah dari rekening scontro (T-Account) menjadi stafel (I-Account) sesuai standar internasional Government Finance Statistics mulai tahun anggaran berapa?', 'Tahun anggaran 1969/1970', 'Tahun anggaran 2000', 'Tahun anggaran 2003', 'Tahun anggaran 2016', null, 'B', 'Mulai tahun anggaran 2000, format APBN berubah dari T-Account (rekening scontro) menjadi I-Account (stafel) sesuai standar internasional Government Finance Statistics.', 'medium'),
('b0000000-0000-4000-8000-040300000000', 'Dalam tahapan pelaksanaan APBN di level operasional, siapa yang berwenang melakukan pembayaran atas beban APBN setelah menguji kelengkapan perintah bayar, kebenaran perhitungan tagihan, dan ketersediaan dana?', 'Pejabat Pembuat Komitmen (PPK)', 'Pengguna Anggaran/Kuasa Pengguna Anggaran (PA/KPA)', 'Bendahara Umum Negara (BUN)/Kuasa BUN', 'Dewan Perwakilan Rakyat (DPR)', null, 'C', 'Tahapan Pembayaran dilaksanakan oleh Bendahara Umum Negara (BUN)/Kuasa BUN, yang meneliti kelengkapan perintah bayar, menguji kebenaran perhitungan tagihan, menguji ketersediaan dana, dan memerintahkan pencairan dana.', 'hard'),
('b0000000-0000-4000-8000-040400000000', 'Pendapatan Negara terdiri atas komponen apa saja?', 'Penerimaan Perpajakan dan Penerimaan Negara Bukan Pajak (PNBP) saja', 'Utang dalam negeri dan utang luar negeri', 'Belanja Pemerintah Pusat dan Transfer ke Daerah', 'Penerimaan Perpajakan, Penerimaan Negara Bukan Pajak (PNBP), dan Hibah', null, 'D', 'Pendapatan Negara = Penerimaan Perpajakan + Penerimaan Negara Bukan Pajak (PNBP) + Hibah.', 'easy'),
('b0000000-0000-4000-8000-040400000000', 'Pajak Penghasilan (PPh) diatur dalam UU Nomor 7 Tahun 1983, yang terakhir kali diubah melalui peraturan apa?', 'UU Nomor 7 Tahun 2021 tentang Harmonisasi Peraturan Perpajakan (HPP)', 'UU Nomor 28 Tahun 2009 tentang PDRD', 'UU Nomor 9 Tahun 2018', 'UU Nomor 1 Tahun 2022 tentang HKPD', null, 'A', 'PPh diatur dalam UU Nomor 7 Tahun 1983 tentang Pajak Penghasilan, terakhir diubah dengan UU Nomor 7 Tahun 2021 tentang Harmonisasi Peraturan Perpajakan (HPP).', 'medium'),
('b0000000-0000-4000-8000-040400000000', 'Bea Materai diatur dalam UU Nomor 10 Tahun 2020 dan berlaku untuk dokumen dengan nilai nominal di atas berapa, dengan tarif berapa?', 'Di atas Rp1.000.000, tarif tetap Rp3.000', 'Di atas Rp5.000.000, tarif tetap Rp10.000', 'Di atas Rp10.000.000, tarif tetap Rp6.000', 'Di atas Rp3.000.000, tarif tetap Rp10.000', null, 'B', 'Bea Materai (UU Nomor 10 Tahun 2020) berlaku untuk dokumen dengan nilai nominal di atas Rp5.000.000, dengan tarif tetap Rp10.000.', 'medium'),
('b0000000-0000-4000-8000-040400000000', 'Sejak diberlakukannya ASEAN Free Trade Area (AFTA), penerimaan Bea Masuk semakin terkikis karena penghapusan bea masuk impor antarnegara ASEAN mulai tahun berapa?', '2010', '2011', '2015', '2020', null, 'C', 'Penerimaan Bea Masuk terkikis dengan adanya ASEAN Free Trade Area (AFTA) yang menghapus bea masuk impor mulai 2015.', 'medium'),
('b0000000-0000-4000-8000-040400000000', 'Berikut ini merupakan jenis objek Penerimaan Negara Bukan Pajak (PNBP) sesuai UU Nomor 9 Tahun 2018, KECUALI:', 'Pemanfaatan Sumber Daya Alam', 'Pengelolaan Barang Milik Negara', 'Pengelolaan Kekayaan Negara Dipisahkan', 'Penerimaan Perpajakan Dalam Negeri', null, 'D', 'PNBP memiliki 6 jenis objek: Pemanfaatan SDA, Pelayanan, Pengelolaan Kekayaan Negara Dipisahkan, Pengelolaan Barang Milik Negara, Pengelolaan Dana, dan Hak Negara Lainnya. Penerimaan Perpajakan adalah komponen Pendapatan Negara yang terpisah dari PNBP.', 'medium'),
('b0000000-0000-4000-8000-040500000000', 'Belanja Negara terdiri atas dua kelompok besar, yaitu apa?', 'Belanja Pemerintah Pusat dan Transfer ke Daerah (TKD)', 'Belanja rutin dan belanja pembangunan', 'Belanja pegawai dan belanja modal saja', 'Pembiayaan dalam negeri dan pembiayaan luar negeri', null, 'A', 'Belanja negara terdiri atas Belanja Pemerintah Pusat dan Transfer ke Daerah (TKD).', 'easy'),
('b0000000-0000-4000-8000-040500000000', 'Jenis Transfer ke Daerah (TKD) yang bertujuan mengurangi ketimpangan kemampuan keuangan dan layanan publik antardaerah, dengan pertimbangan kebutuhan layanan publik dan kemampuan keuangan negara, disebut apa?', 'Dana Bagi Hasil (DBH)', 'Dana Alokasi Umum (DAU)', 'Dana Alokasi Khusus (DAK)', 'Dana Otonomi Khusus', null, 'B', 'Dana Alokasi Umum (DAU) bertujuan mengurangi ketimpangan kemampuan keuangan dan layanan publik antardaerah, dengan pertimbangan kebutuhan layanan publik, kemampuan keuangan negara, pagu TKD, dan target pembangunan nasional.', 'medium'),
('b0000000-0000-4000-8000-040500000000', 'Dasar hukum definisi pembiayaan sebagai "penerimaan yang harus dibayar kembali dan/atau pengeluaran yang akan diterima kembali" terdapat pada pasal berapa?', 'Pasal 17 UU Nomor 1 Tahun 2004', 'Pasal 30 UU Nomor 17 Tahun 2003', 'Pasal 1 Angka 17 UU Nomor 17 Tahun 2003', 'Pasal 23 ayat 5 UUD 1945', null, 'C', 'Pasal 1 Angka 17 UU Nomor 17 Tahun 2003 mendefinisikan pembiayaan sebagai penerimaan yang harus dibayar kembali dan/atau pengeluaran yang akan diterima kembali.', 'hard'),
('b0000000-0000-4000-8000-040500000000', 'Manakah yang termasuk sumber Pembiayaan Dalam Negeri sektor Nonperbankan untuk menutup defisit anggaran?', 'Pinjaman Program dan Pinjaman Proyek', 'Dana Bagi Hasil dan Dana Alokasi Umum', 'Obligasi Indonesia di pasar modal internasional', 'Privatisasi BUMN, Penjualan Aset Restrukturisasi Perbankan, dan Penerbitan Surat Utang Negara (SUN)', null, 'D', 'Sektor Nonperbankan dalam Pembiayaan Dalam Negeri mencakup Privatisasi BUMN, Penjualan Aset Restrukturisasi Perbankan (bank BBO/BTO eks BPPN), dan Penerbitan Surat Utang Negara (SUN).', 'medium'),
('b0000000-0000-4000-8000-040500000000', 'Debt Service Ratio (DSR) merupakan rasio yang membandingkan angsuran dan bunga pinjaman terhadap apa?', 'Net ekspor (migas dan nonmigas)', 'Total belanja negara', 'Produk Domestik Bruto (PDB)', 'Penerimaan Negara Bukan Pajak (PNBP)', null, 'A', 'Debt Service Ratio (DSR) = rasio Angsuran + Bunga Pinjaman terhadap Net Ekspor (Migas + Non Migas); makin besar rasio ini, makin menyulitkan negara.', 'hard'),
('b0000000-0000-4000-8000-040600000000', 'Sistem pengawasan atas pelaksanaan APBN terbagi menjadi dua sistem utama, yaitu apa?', 'Sistem Pengawasan DPR dan Sistem Pengawasan Presiden', 'Sistem Pengawasan Eksternal Pemerintah dan Sistem Pengawasan Internal Pemerintah', 'Sistem Pengawasan Pusat dan Sistem Pengawasan Daerah', 'Sistem Pengawasan Preventif dan Sistem Pengawasan Represif', null, 'B', 'Terdapat 2 sistem pengawasan utama atas pelaksanaan APBN: Sistem Pengawasan Eksternal Pemerintah dan Sistem Pengawasan Internal Pemerintah.', 'easy'),
('b0000000-0000-4000-8000-040600000000', 'Pengawasan BPK atas APBN memiliki dasar hukum konstitusional pada Pasal berapa UUD 1945?', 'Pasal 20A UUD 1945', 'Pasal 28 UUD 1945', 'Pasal 23E UUD 1945', 'Pasal 30 UUD 1945', null, 'C', 'Pengawasan oleh BPK memiliki dasar hukum Pasal 23E UUD 1945, yang direalisasikan lebih lanjut dalam UU No. 5 Tahun 1973 tentang BPK.', 'medium'),
('b0000000-0000-4000-8000-040600000000', 'Berdasarkan Pasal 4 UU Nomor 15 Tahun 2004, BPK melakukan 3 tipe pemeriksaan. Manakah yang termasuk ketiga tipe tersebut?', 'Pemeriksaan rechtmatigheid, wetmatigheid, dan doelmatigheid', 'Pre-audit, post-audit, dan audit investigatif', 'Pemeriksaan pajak, pemeriksaan bea cukai, dan pemeriksaan PNBP', 'Pemeriksaan keuangan, pemeriksaan kinerja, dan pemeriksaan dengan tujuan tertentu', null, 'D', 'Pasal 4 UU Nomor 15 Tahun 2004 mengatur 3 tipe pemeriksaan BPK: pemeriksaan keuangan (opini kewajaran laporan keuangan), pemeriksaan kinerja (ekonomi, efisiensi, efektivitas), dan pemeriksaan dengan tujuan tertentu (termasuk investigatif).', 'medium'),
('b0000000-0000-4000-8000-040600000000', 'BPKP sebagai bagian dari Aparat Pengawasan Intern Pemerintah (APIP) awalnya dibentuk berdasarkan peraturan apa?', 'Keppres RI Nomor 31 Tahun 1983', 'Perpres Nomor 192 Tahun 2014', 'Peraturan BPKP Nomor 9 Tahun 2021', 'Perpres Nomor 47 Tahun 2009', null, 'A', 'BPKP dibentuk berdasarkan Keppres RI Nomor 31 Tahun 1983 (3 Juni 1983), kemudian diatur ulang melalui Perpres Nomor 192 Tahun 2014 (diubah Perpres Nomor 20 Tahun 2023), dan organisasinya diatur Peraturan BPKP Nomor 9 Tahun 2021 (diubah Peraturan BPKP Nomor 3 Tahun 2023).', 'hard'),
('b0000000-0000-4000-8000-040600000000', 'Sejak berlakunya UU Nomor 17 Tahun 2003, batas waktu penyampaian Laporan Keuangan Pemerintah Pusat ke DPR mulai Tahun Anggaran 2005 menjadi berapa bulan setelah tahun anggaran berakhir?', '2 bulan', '6 bulan', '9 bulan', '12 bulan', null, 'B', 'Batas waktu penyampaian Laporan Keuangan ke DPR untuk TA 2004 adalah 9 bulan, kemudian mulai TA 2005 dipercepat menjadi 6 bulan.', 'hard')
;
