-- 5 soal per bab untuk Modul Tata Aturan Kepegawaian (M3)
-- Menggantikan soal lama yang sedikit dan tersebar tidak merata.

delete from questions where chapter_id in (
  'b0000000-0000-4000-8000-030100000000',
  'b0000000-0000-4000-8000-030200000000',
  'b0000000-0000-4000-8000-030300000000',
  'b0000000-0000-4000-8000-030400000000',
  'b0000000-0000-4000-8000-030500000000'
);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values
('b0000000-0000-4000-8000-030100000000', 'UU Nomor 20 Tahun 2023 tentang Aparatur Sipil Negara menggantikan undang-undang ASN sebelumnya, yaitu...?', 'UU Nomor 5 Tahun 2014', 'UU Nomor 43 Tahun 1999', 'UU Nomor 8 Tahun 1974', 'UU Nomor 30 Tahun 2014', null, 'A', 'UU Nomor 20 Tahun 2023 tentang ASN disahkan 31 Oktober 2023 dan menggantikan UU Nomor 5 Tahun 2014 tentang ASN.', 'easy'),
('b0000000-0000-4000-8000-030100000000', 'Perbedaan mendasar antara PNS dan PPPK menurut UU Nomor 20 Tahun 2023 terletak pada...?', 'PNS digaji lebih tinggi daripada PPPK', 'PNS diangkat secara tetap oleh PPK, sedangkan PPPK diangkat berdasarkan perjanjian kerja untuk jangka waktu tertentu', 'PPPK tidak boleh menduduki jabatan pemerintahan sama sekali', 'PNS hanya bisa bekerja di instansi pusat, PPPK hanya di instansi daerah', null, 'B', 'PNS diangkat sebagai Pegawai ASN secara tetap oleh Pejabat Pembina Kepegawaian (PPK), sedangkan PPPK diangkat berdasarkan perjanjian kerja untuk jangka waktu tertentu.', 'easy'),
('b0000000-0000-4000-8000-030100000000', 'Jabatan Manajerial dalam UU ASN terdiri atas 3 (tiga) jenjang. Manakah urutan dari tingkat tertinggi ke tingkat dasar yang benar?', 'Jabatan Pengawas - Jabatan Administrator - Jabatan Pimpinan Tinggi', 'Jabatan Administrator - Jabatan Pimpinan Tinggi - Jabatan Pengawas', 'Jabatan Pimpinan Tinggi - Jabatan Administrator - Jabatan Pengawas', 'Jabatan Pimpinan Tinggi - Jabatan Pengawas - Jabatan Administrator', null, 'C', 'Jabatan Manajerial terdiri atas Jabatan Pimpinan Tinggi (tingkat tinggi), Jabatan Administrator (tingkat menengah), dan Jabatan Pengawas (tingkat dasar), sesuai Pasal 16 UU Nomor 20 Tahun 2023.', 'medium'),
('b0000000-0000-4000-8000-030100000000', 'Seorang PNS pemegang Jabatan Administrasi ditugaskan belajar penuh selama 8 (delapan) bulan. Berdasarkan ketentuan, apa konsekuensinya terhadap jabatannya?', 'Tidak ada konsekuensi karena tugas belajar bukan alasan pemberhentian dari jabatan', 'Gajinya dihentikan sampai tugas belajar selesai', 'Otomatis dipindahkan ke Jabatan Fungsional', 'Diberhentikan dari Jabatan Administrasi karena menjalani tugas belajar lebih dari 6 (enam) bulan', null, 'D', 'PNS diberhentikan dari jabatan administrasi apabila menjalani tugas belajar lebih dari 6 (enam) bulan, salah satu dari beberapa alasan pemberhentian dari jabatan administrasi.', 'medium'),
('b0000000-0000-4000-8000-030100000000', 'Jenjang Jabatan Fungsional Keterampilan menurut UU ASN terdiri atas...?', 'Penyelia, Mahir, Terampil, Pemula', 'Ahli Utama, Ahli Madya, Ahli Muda, Ahli Pertama', 'Eselon III, Eselon IV, Eselon V', 'Utama, Madya, Pratama', null, 'A', 'Jabatan Fungsional Keterampilan terdiri atas jenjang Penyelia, Mahir, Terampil, dan Pemula, berbeda dengan Jabatan Fungsional Keahlian yang terdiri atas Ahli Utama, Ahli Madya, Ahli Muda, dan Ahli Pertama.', 'hard'),
('b0000000-0000-4000-8000-030200000000', 'Berapa jumlah hak Pegawai ASN yang diatur dalam UU Nomor 20 Tahun 2023?', '5 (lima) hak', '7 (tujuh) hak', '6 (enam) hak', '8 (delapan) hak', null, 'B', 'Pegawai ASN berhak memperoleh penghargaan dan pengakuan berupa materiel/nonmateriel yang terdiri atas 7 (tujuh) hak: penghasilan, penghargaan motivasi, tunjangan dan fasilitas, jaminan sosial, lingkungan kerja, pengembangan diri, dan bantuan hukum.', 'easy'),
('b0000000-0000-4000-8000-030200000000', 'Manakah yang BUKAN termasuk salah satu dari 7 (tujuh) hak Pegawai ASN?', 'Jaminan sosial', 'Bantuan hukum', 'Cuti di luar tanggungan negara', 'Pengembangan diri', null, 'C', 'Cuti di luar tanggungan negara adalah salah satu jenis cuti PNS, bukan bagian dari 7 hak Pegawai ASN (penghasilan, penghargaan motivasi, tunjangan dan fasilitas, jaminan sosial, lingkungan kerja, pengembangan diri, bantuan hukum).', 'medium'),
('b0000000-0000-4000-8000-030200000000', 'Berapa jumlah kewajiban ASN yang diatur dalam UU Nomor 20 Tahun 2023?', '4 (empat) kewajiban', '7 (tujuh) kewajiban', '6 (enam) kewajiban', '5 (lima) kewajiban', null, 'D', 'Kewajiban ASN terdiri atas 5 (lima) poin, di antaranya setia dan taat kepada Pancasila, UUD 1945, NKRI, dan pemerintah yang sah, serta bersedia ditempatkan di seluruh wilayah NKRI.', 'easy'),
('b0000000-0000-4000-8000-030200000000', 'Seorang PNS menolak untuk ditempatkan di wilayah lain dalam NKRI dengan alasan pribadi semata. Sikap tersebut bertentangan dengan kewajiban ASN yang mana?', 'Bersedia ditempatkan di seluruh wilayah NKRI dan perwakilan NKRI di luar negeri', 'Menjaga netralitas', 'Menaati ketentuan peraturan perundang-undangan', 'Melaksanakan nilai dasar ASN', null, 'A', 'Salah satu kewajiban ASN adalah bersedia ditempatkan di seluruh wilayah Negara Kesatuan Republik Indonesia dan di perwakilan Negara Kesatuan Republik Indonesia di luar negeri.', 'medium'),
('b0000000-0000-4000-8000-030200000000', 'Kewajiban ASN untuk "menjaga netralitas" pada dasarnya berkaitan erat dengan larangan bagi ASN untuk...?', 'Menerima tunjangan kinerja', 'Terlibat atau memihak dalam kegiatan politik praktis/partai politik', 'Mengajukan cuti tahunan', 'Mengikuti pengembangan kompetensi', null, 'B', 'Kewajiban menjaga netralitas berkaitan dengan kedudukan Pegawai ASN sebagai unsur aparatur negara yang harus bebas dari pengaruh dan intervensi golongan dan partai politik (Pasal 8 dan 9 UU Nomor 20 Tahun 2023).', 'medium'),
('b0000000-0000-4000-8000-030300000000', 'Siapakah pemegang kekuasaan pemerintahan tertinggi dalam kebijakan, pembinaan profesi, dan Manajemen ASN?', 'Menteri PAN-RB', 'Kepala BKN', 'Presiden', 'Ketua KASN', null, 'C', 'Presiden adalah pemegang kekuasaan pemerintahan tertinggi dalam kebijakan, pembinaan profesi, dan Manajemen ASN, yang kewenangannya didelegasikan kepada Kementerian PAN-RB.', 'easy'),
('b0000000-0000-4000-8000-030300000000', 'Presiden mendelegasikan kewenangan atas kebijakan, pembinaan profesi, dan Manajemen ASN kepada...?', 'Kementerian Dalam Negeri', 'Badan Kepegawaian Negara (BKN)', 'Komite Aparatur Sipil Negara (KASN)', 'Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi (PAN-RB)', null, 'D', 'Presiden mendelegasikan kewenangan tersebut kepada Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi (PAN-RB).', 'easy'),
('b0000000-0000-4000-8000-030300000000', 'Manakah berikut ini yang termasuk tugas Kementerian PAN-RB dalam kelembagaan Manajemen ASN?', 'Melakukan pengawasan penerapan Sistem Merit pada Kementerian/Lembaga', 'Menjatuhkan hukuman disiplin kepada PNS di seluruh instansi', 'Menetapkan gaji pokok seluruh PNS', 'Menjadi pejabat pembina kepegawaian di semua instansi daerah', null, 'A', 'Tugas Kementerian PAN-RB antara lain mengoordinasikan rencana kerja lembaga terkait Manajemen ASN, sinkronisasi dan pengendalian tugas pengembangan kapasitas ASN, pengendalian kebijakan teknis, serta pengawasan penerapan Sistem Merit pada Kementerian/Lembaga.', 'medium'),
('b0000000-0000-4000-8000-030300000000', 'Pendelegasian kewenangan Presiden kepada Kementerian PAN-RB dalam Manajemen ASN, kecuali meliputi...?', 'Perumusan dan penetapan kebijakan strategis', 'Penetapan putusan pengadilan tata usaha negara terkait sengketa kepegawaian', 'Pengendalian kebijakan Manajemen ASN secara nasional', 'Koordinasi dan sinkronisasi kebijakan', null, 'B', 'Pendelegasian kewenangan Presiden kepada Kementerian PAN-RB meliputi perumusan dan penetapan kebijakan strategis, koordinasi dan sinkronisasi kebijakan, serta pengendalian kebijakan Manajemen ASN secara nasional -- bukan penetapan putusan pengadilan.', 'medium'),
('b0000000-0000-4000-8000-030300000000', 'Pengawasan terhadap penerapan Sistem Merit pada Kementerian/Lembaga menjadi salah satu tugas dari...?', 'Badan Kepegawaian Negara', 'Lembaga Administrasi Negara', 'Kementerian PAN-RB', 'Sekretariat Kabinet', null, 'C', 'Salah satu tugas Kementerian PAN-RB adalah melakukan pengawasan penerapan Sistem Merit pada Kementerian/Lembaga.', 'medium'),
('b0000000-0000-4000-8000-030400000000', 'Berapa lama masa percobaan yang harus dijalani oleh calon PNS (CPNS) sebelum diangkat menjadi PNS?', '6 (enam) bulan', '3 (tiga) tahun', '2 (dua) tahun', '1 (satu) tahun', null, 'D', 'Masa percobaan CPNS adalah 1 (satu) tahun, dilaksanakan melalui pendidikan dan pelatihan (diklat) terintegrasi sesuai PP 11/2017 stdd PP 17/2020.', 'easy'),
('b0000000-0000-4000-8000-030400000000', 'Berapa Batas Usia Pensiun (BUP) bagi Pejabat Administrasi, Pejabat Fungsional Ahli Muda, Ahli Pertama, dan Pejabat Fungsional Keterampilan?', '58 tahun', '56 tahun', '60 tahun', '65 tahun', null, 'A', 'Sesuai PP 11 Tahun 2017 sebagaimana diubah PP 17 Tahun 2020, BUP 58 tahun berlaku bagi Pejabat Administrasi, Pejabat Fungsional Ahli Muda, Ahli Pertama, dan Pejabat Fungsional Keterampilan; sedangkan JPT dan Ahli Madya 60 tahun, dan Ahli Utama 65 tahun.', 'medium'),
('b0000000-0000-4000-8000-030400000000', 'Dalam proses pengisian Jabatan Pimpinan Tinggi (JPT) Utama dan Madya di Instansi Pusat, setelah panitia seleksi memilih 3 (tiga) nama calon per 1 lowongan dan diusulkan PPK, siapakah yang memilih 1 (satu) nama akhir?', 'PPK secara langsung', 'Presiden', 'Menteri PAN-RB', 'KASN', null, 'B', 'Untuk JPT Utama/Madya di Instansi Pusat, panitia seleksi memilih 3 nama calon per lowongan yang diusulkan PPK kepada Presiden, kemudian Presiden memilih 1 (satu) nama.', 'medium'),
('b0000000-0000-4000-8000-030400000000', 'Berapa lama masa jabatan Jabatan Pimpinan Tinggi (JPT) paling lama menurut ketentuan?', '3 (tiga) tahun', '4 (empat) tahun', '5 (lima) tahun', '10 (sepuluh) tahun', null, 'C', 'Masa jabatan JPT paling lama 5 (lima) tahun, dapat diperpanjang berdasarkan kinerja, kompetensi, dan kebutuhan instansi dengan persetujuan PPK serta koordinasi KASN.', 'medium'),
('b0000000-0000-4000-8000-030400000000', 'Seorang PNS diangkat menjadi Menteri. Berdasarkan Pasal 58 UU Nomor 20 Tahun 2023, status kepegawaiannya adalah...?', 'Diberhentikan tidak dengan hormat sebagai PNS', 'Tetap menjabat sebagai PNS dan Menteri sekaligus tanpa pemberhentian', 'Otomatis pensiun dini', 'Diberhentikan sementara dari jabatan ASN-nya, namun tidak kehilangan status PNS', null, 'D', 'Pegawai ASN dari PNS yang diangkat menjadi pejabat negara seperti Menteri diberhentikan sementara dari jabatan ASN-nya, tetapi tidak kehilangan status sebagai PNS, dan diaktifkan kembali bila tidak lagi menjabat (Pasal 58 UU Nomor 20 Tahun 2023).', 'hard'),
('b0000000-0000-4000-8000-030500000000', 'Sejak tahun berapa Kementerian Keuangan mulai menerapkan sistem merit melalui reformasi birokrasi?', '2007', '2004', '2010', '2014', null, 'A', 'Kemenkeu sejak reformasi birokrasi tahun 2007 telah menerapkan sistem merit, meliputi rekrutmen objektif dan transparan, pengukuran kompetensi, manajemen kinerja, peringkat jabatan, talent management, dan remunerasi berbasis peringkat jabatan dan kinerja.', 'easy'),
('b0000000-0000-4000-8000-030500000000', 'Peraturan yang mengatur Manajemen Talenta di Lingkungan Kementerian Keuangan saat ini, yang mencabut PMK Nomor 60/PMK.01/2016, adalah...?', 'PMK Nomor 224/PMK.01/2020', 'PMK Nomor 38 Tahun 2025', 'PMK Nomor 216/PMK.01/2018', 'PMK Nomor 300/KMK.01/2022', null, 'B', 'PMK Nomor 38 Tahun 2025 tentang Manajemen Talenta di Lingkungan Kemenkeu mencabut PMK Nomor 60/PMK.01/2016 stdd PMK Nomor 161/PMK.01/2017 tentang Manajemen Talenta Kemenkeu.', 'medium'),
('b0000000-0000-4000-8000-030500000000', 'Dalam tahapan Pola Karier di Lingkungan Kemenkeu (PMK 224/2020), masa branding berlangsung selama berapa lama setelah CPNS diangkat menjadi PNS?', '1 (satu) tahun', '3 (tiga) tahun', '2 (dua) tahun', '5 (lima) tahun', null, 'C', 'Masa branding berlangsung 2 (dua) tahun setelah CPNS diangkat menjadi PNS, mencakup program penguatan nilai Kemenkeu, kode etik, disiplin, pembekalan teknis jabatan, dan pembekalan rencana pengembangan karier individu.', 'medium'),
('b0000000-0000-4000-8000-030500000000', 'Seorang PNS di Kemenkeu tidak masuk kerja tanpa alasan sah secara kumulatif selama 15 (lima belas) hari dalam 1 tahun. Berdasarkan ambang pelanggaran jam kerja, jenis hukuman disiplin yang dijatuhkan adalah...?', 'Teguran lisan', 'Pemberhentian dengan hormat tidak atas permintaan sendiri', 'Penurunan jabatan setingkat lebih rendah selama 12 bulan', 'Pemotongan tunjangan kinerja 25% selama 9 bulan', null, 'D', 'Sesuai jenjang hukuman pelanggaran jam kerja pada PP Nomor 94 Tahun 2021, tidak masuk kerja 14-16 hari dikenai hukuman sedang berupa pemotongan tunjangan kinerja 25% selama 9 bulan.', 'hard'),
('b0000000-0000-4000-8000-030500000000', 'Berapa persen iuran wajib PNS untuk program kesejahteraan (dana pensiun dan tabungan hari tua/perumahan) dari penghasilan, berdasarkan Keppres Nomor 56 Tahun 1974?', '10% (4,75% dana pensiun, 3,25% THT)', '7,5% (5% dana pensiun, 2,5% THT)', '5% (4% dana pensiun, 1% THT)', '12% (8% dana pensiun, 4% THT)', null, 'A', 'Berdasarkan Keppres Nomor 56 Tahun 1974, iuran wajib PNS sebesar 10% dari penghasilan, terdiri atas 4,75% untuk iuran dana pensiun dan 3,25% untuk iuran tabungan hari tua dan perumahan.', 'hard')
;
