-- =====================================================================
-- Bank soal APLIKATIF / STUDI KASUS — Modul Pengelolaan Keuangan Negara (M4)
-- =====================================================================
-- Mengganti soal hafalan lama dengan soal studi kasus per bab, berpijak pada
-- materi/ringkasan modul: konsep PKN (Kemenkeu sebagai CFO negara), UU 17/2003
-- Keuangan Negara (unsur, subbidang, asas, counter-cyclical), pengelolaan APBN
-- (batas defisit, siklus, pelaksanaan), pendapatan negara (perpajakan/PNBP/hibah),
-- belanja & pembiayaan (TKD, DSR), serta pengawasan & pertanggungjawaban APBN
-- (BPK, BPKP/APIP, pelaporan).
-- File ini idempotent: menghapus dulu soal M4 yang ada, lalu memasukkan yang baru.
--
-- Aman untuk skema baru: attempts menyimpan salinan soal (jsonb), jadi riwayat
-- lama tidak terpengaruh; seen_questions ikut terhapus otomatis (cascade).

delete from questions where chapter_id in (
  'b0000000-0000-4000-8000-040100000000',
  'b0000000-0000-4000-8000-040200000000',
  'b0000000-0000-4000-8000-040300000000',
  'b0000000-0000-4000-8000-040400000000',
  'b0000000-0000-4000-8000-040500000000',
  'b0000000-0000-4000-8000-040600000000'
);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values

-- ===================== BAB I: PENDAHULUAN & KONSEP PKN =====================
('b0000000-0000-4000-8000-040100000000',
 'Dalam sebuah paparan, seorang pejabat menyatakan Pengelolaan Keuangan Negara hanya soal membelanjakan anggaran. Berdasarkan modul, pernyataan ini kurang tepat karena PKN mencakup...',
 'Pendapatan negara, belanja negara, dan sumber keuangan untuk menutup/membiayai defisit',
 'Hanya belanja negara dan belanja daerah',
 'Hanya kekayaan negara yang dipisahkan pada BUMN',
 'Hanya anggaran rutin dan anggaran pembangunan',
 null, 'A',
 'Pengelolaan Keuangan Negara mencakup pendapatan negara, belanja negara, serta sumber keuangan untuk menutup/membiayai kekurangan (defisit) yang mungkin timbul.',
 'easy'),

('b0000000-0000-4000-8000-040100000000',
 'Seorang pegawai ingin menjelaskan asal sumber pendapatan negara sesuai kewenangan Pemerintah. Jawaban yang tepat adalah...',
 'Utang luar negeri semata',
 'Pajak dan bukan pajak',
 'Hibah luar negeri semata',
 'Hasil privatisasi BUMN semata',
 null, 'B',
 'Pendapatan negara berasal dari pajak dan bukan pajak sesuai kewenangan Pemerintah menurut peraturan perundang-undangan.',
 'easy'),

('b0000000-0000-4000-8000-040100000000',
 'Pemerintah hendak menetapkan program belanja besar untuk tahun anggaran berikutnya. Agar pengelolaannya transparan dan akuntabel, langkah yang wajib ditempuh adalah...',
 'Menetapkan sendiri tanpa melibatkan pihak mana pun',
 'Cukup melapor ke Bank Indonesia',
 'Memperoleh persetujuan dan pengawasan dari legislatif (DPR)',
 'Meminta izin Mahkamah Agung',
 null, 'C',
 'Wewenang dan fungsi Pemerintah dalam PKN dibatasi peraturan perundang-undangan, termasuk persetujuan dan pengawasan legislatif (DPR), demi transparansi dan akuntabilitas.',
 'medium'),

('b0000000-0000-4000-8000-040100000000',
 'Dalam pengelolaan keuangan negara, Kementerian Keuangan memegang peran strategis yang dianalogikan sebagai...',
 'Chief Operational Officer (COO) negara',
 'Chief Risk Officer (CRO) negara',
 'Chief Executive Officer (CEO) negara',
 'Chief Financial Officer (CFO) negara',
 null, 'D',
 'Kementerian Keuangan berperan strategis sebagai Chief Financial Officer (CFO) negara.',
 'easy'),

('b0000000-0000-4000-8000-040100000000',
 'Mengapa wewenang Pemerintah dalam pengelolaan keuangan negara perlu dibatasi oleh peraturan perundang-undangan?',
 'Agar pengelolaan berjalan transparan, akuntabel, serta dapat diawasi dan dipertanggungjawabkan',
 'Agar Pemerintah bebas membelanjakan tanpa batas',
 'Agar keputusan keuangan cukup ditentukan satu orang',
 'Agar tidak perlu ada pelaporan keuangan',
 null, 'A',
 'Pembatasan oleh peraturan perundang-undangan bertujuan agar pengelolaan keuangan negara transparan, akuntabel, serta dapat diawasi dan dipertanggungjawabkan.',
 'medium'),

('b0000000-0000-4000-8000-040100000000',
 'Cakupan bahan ajar modul Pengelolaan Keuangan Negara pada Bab Pendahuluan meliputi tiga hal, yaitu...',
 'Hanya pengelolaan APBN tanpa pengawasan',
 'Maksud & tujuan PKN secara umum, pengelolaan APBN (pendapatan, belanja, pembiayaan defisit), serta pengawasan dan pertanggungjawaban APBN',
 'Hanya kebijakan moneter Bank Indonesia',
 'Hanya siklus penyusunan Rencana Kerja Pemerintah',
 null, 'B',
 'Cakupan modul: maksud & tujuan PKN secara umum; pengelolaan APBN (pendapatan, belanja, pembiayaan defisit); serta pengawasan dan pertanggungjawaban APBN.',
 'medium'),

-- ===================== BAB II: UU 17/2003, UNSUR, SUBBIDANG, ASAS =====================
('b0000000-0000-4000-8000-040200000000',
 'Seorang analis mencari dasar hukum utama pengertian Keuangan Negara. Peraturan yang tepat adalah...',
 'UU Nomor 1 Tahun 2004 tentang Perbendaharaan Negara',
 'UU Nomor 15 Tahun 2004 tentang Pemeriksaan Pengelolaan dan Tanggung Jawab Keuangan Negara',
 'UU Nomor 17 Tahun 2003 tentang Keuangan Negara',
 'UU Nomor 9 Tahun 2018 tentang PNBP',
 null, 'C',
 'Pengertian Keuangan Negara diatur dalam UU Nomor 17 Tahun 2003 tentang Keuangan Negara.',
 'easy'),

('b0000000-0000-4000-8000-040200000000',
 'Penjelasan UU Nomor 17 Tahun 2003 menyebut bahwa keuangan negara mencakup seluruh objek yang dimiliki/dikuasai Pemerintah dan badan hukum publik lainnya. Unsur pengertian keuangan negara yang dimaksud adalah unsur...',
 'Objek',
 'Proses',
 'Tujuan',
 'Subjek',
 null, 'D',
 'Unsur Subjek menegaskan bahwa seluruh objek keuangan negara yang dimiliki/dikuasai Pemerintah dan badan hukum publik lainnya termasuk dalam pengertian keuangan negara.',
 'medium'),

('b0000000-0000-4000-8000-040200000000',
 'Kebijakan mengenai jumlah uang beredar, cadangan wajib bank, tingkat diskonto, serta kurs valuta asing termasuk subbidang pengelolaan keuangan negara yang dilaksanakan oleh...',
 'Subbidang Moneter, dilaksanakan oleh Bank Indonesia',
 'Subbidang Fiskal, dilaksanakan oleh DPR',
 'Subbidang Kekayaan Negara Dipisahkan, dilaksanakan oleh BUMN',
 'Subbidang Fiskal, dilaksanakan oleh Kementerian Keuangan',
 null, 'A',
 'Subbidang Pengelolaan Moneter (jumlah uang beredar, cadangan wajib bank, diskonto, kredit, pasar terbuka, kurs valas) dilaksanakan oleh Bank Indonesia.',
 'medium'),

('b0000000-0000-4000-8000-040200000000',
 'Perekonomian sedang mengalami resesi. Sesuai kebijakan counter-cyclical dalam pengelolaan keuangan negara, langkah Pemerintah yang tepat adalah...',
 'Menurunkan belanja pemerintah dan menaikkan pajak',
 'Menaikkan belanja pemerintah dan/atau menurunkan pajak',
 'Membiarkan pasar tanpa intervensi apa pun',
 'Menaikkan belanja pemerintah sekaligus menaikkan pajak',
 null, 'B',
 'Kebijakan counter-cyclical bergerak melawan arah siklus ekonomi: saat resesi, Pemerintah menaikkan belanja dan/atau menurunkan pajak untuk mendorong perekonomian (dan sebaliknya saat inflasi tinggi).',
 'hard'),

('b0000000-0000-4000-8000-040200000000',
 'Berikut ini adalah asas-asas umum pengelolaan keuangan negara, KECUALI...',
 'Asas Tahunan',
 'Asas Universalitas',
 'Asas Sentralisasi Penuh',
 'Asas Spesialitas',
 null, 'C',
 'Sembilan asas umum PKN: Tahunan, Universalitas, Kesatuan, Spesialitas, Akuntabilitas, Profesionalitas, Proporsionalitas, Keterbukaan, dan Pemeriksaan keuangan. "Sentralisasi Penuh" bukan bagian dari asas-asas tersebut.',
 'medium'),

('b0000000-0000-4000-8000-040200000000',
 'Pengelolaan APBN yang bersifat fiskal — menyangkut pendapatan, belanja, dan pembiayaan negara — dilaksanakan oleh...',
 'Bank Indonesia',
 'Dewan Perwakilan Rakyat',
 'Badan Usaha Milik Negara',
 'Kementerian Keuangan (subbidang Fiskal)',
 null, 'D',
 'Subbidang Fiskal (pendapatan, belanja, pembiayaan) dalam pengelolaan keuangan negara dilaksanakan oleh Kementerian Keuangan.',
 'medium'),

('b0000000-0000-4000-8000-040200000000',
 'Prinsip bahwa APBN disusun dan disajikan sebagai satu kesatuan yang utuh, mencakup semua penerimaan dan pengeluaran negara dalam satu dokumen anggaran, paling sesuai dengan asas...',
 'Asas Kesatuan dan Universalitas',
 'Asas Sentralisasi Penuh',
 'Asas Kerahasiaan Anggaran',
 'Asas Anggaran Berimbang Mutlak',
 null, 'A',
 'Asas Kesatuan menghendaki APBN disajikan sebagai satu kesatuan utuh, dan asas Universalitas menghendaki seluruh penerimaan dan pengeluaran tercakup dalam dokumen anggaran.',
 'medium'),

-- ===================== BAB III: PENGELOLAAN APBN (DEFISIT, SIKLUS, PELAKSANAAN) =====================
('b0000000-0000-4000-8000-040300000000',
 'Pemerintah menyusun APBN dengan rencana defisit. Menurut UU Nomor 17 Tahun 2003, batas maksimal defisit APBN terhadap PDB adalah...',
 '2%',
 '3%',
 '5%',
 '60%',
 null, 'B',
 'Batas maksimal defisit APBN terhadap PDB adalah 3% menurut UU Nomor 17 Tahun 2003.',
 'easy'),

('b0000000-0000-4000-8000-040300000000',
 'Selain batas defisit, UU Nomor 17 Tahun 2003 juga menetapkan batas jumlah pinjaman (utang) untuk membiayai defisit, yaitu maksimal...',
 '3% dari PDB',
 '30% dari PDB',
 '60% dari PDB',
 '100% dari PDB',
 null, 'C',
 'Batas jumlah pinjaman untuk membiayai defisit adalah maksimal 60% dari PDB.',
 'medium'),

('b0000000-0000-4000-8000-040300000000',
 'Pada masa pandemi Covid-19, batas defisit APBN 3% terhadap PDB dilonggarkan sementara. Pelonggaran ini dilakukan melalui...',
 'PP Nomor 45 Tahun 2013',
 'UU Nomor 33 Tahun 2004',
 'UU Nomor 1 Tahun 2004 tentang Perbendaharaan Negara',
 'Perppu Nomor 1 Tahun 2020 tentang Kebijakan Keuangan Negara dan Stabilitas Sistem Keuangan untuk Penanganan Pandemi Covid-19',
 null, 'D',
 'Batas defisit 3% dilonggarkan sementara pada masa pandemi Covid-19 melalui Perppu Nomor 1 Tahun 2020 (kemudian menjadi UU).',
 'medium'),

('b0000000-0000-4000-8000-040300000000',
 'Manakah urutan yang benar dari siklus/tahapan pengelolaan APBN?',
 'Perencanaan - Penyusunan - Pembahasan - Penetapan - Pelaksanaan - Pelaporan dan Pencatatan - Pemeriksaan dan Pertanggungjawaban',
 'Pelaksanaan - Perencanaan - Penetapan - Pembahasan - Pelaporan - Pemeriksaan',
 'Penyusunan - Perencanaan - Pelaksanaan - Pembahasan - Penetapan - Pemeriksaan',
 'Pembahasan - Penetapan - Perencanaan - Penyusunan - Pelaksanaan - Pelaporan',
 null, 'A',
 'Siklus APBN terdiri atas 7 tahap berurutan: Perencanaan, Penyusunan, Pembahasan, Penetapan, Pelaksanaan, Pelaporan dan Pencatatan, serta Pemeriksaan dan Pertanggungjawaban.',
 'medium'),

('b0000000-0000-4000-8000-040300000000',
 'Format penyajian APBN pernah berubah dari rekening scontro (T-Account) menjadi stafel (I-Account) sesuai standar Government Finance Statistics. Perubahan ini berlaku mulai tahun anggaran...',
 'Tahun anggaran 1969/1970',
 'Tahun anggaran 2000',
 'Tahun anggaran 2003',
 'Tahun anggaran 2016',
 null, 'B',
 'Mulai tahun anggaran 2000, format APBN berubah dari T-Account (rekening scontro) menjadi I-Account (stafel) sesuai standar Government Finance Statistics.',
 'medium'),

('b0000000-0000-4000-8000-040300000000',
 'Dalam pelaksanaan APBN, setelah menguji kelengkapan perintah bayar, kebenaran perhitungan tagihan, dan ketersediaan dana, pihak yang berwenang memerintahkan pencairan/pembayaran atas beban APBN adalah...',
 'Pejabat Pembuat Komitmen (PPK)',
 'Pengguna Anggaran/Kuasa Pengguna Anggaran (PA/KPA)',
 'Bendahara Umum Negara (BUN)/Kuasa BUN',
 'Dewan Perwakilan Rakyat (DPR)',
 null, 'C',
 'Fungsi pembayaran (menguji perintah bayar, kebenaran tagihan, ketersediaan dana, lalu memerintahkan pencairan) dilaksanakan oleh Bendahara Umum Negara (BUN)/Kuasa BUN.',
 'hard'),

('b0000000-0000-4000-8000-040300000000',
 'DPR bersama Pemerintah sedang membahas Rancangan Undang-Undang APBN sebelum disahkan menjadi UU APBN. Dalam siklus APBN, tahap yang sedang berlangsung adalah...',
 'Perencanaan',
 'Penetapan',
 'Pelaksanaan',
 'Pembahasan',
 null, 'D',
 'Pembahasan RUU APBN antara Pemerintah dan DPR merupakan tahap Pembahasan, yang mendahului tahap Penetapan (pengesahan menjadi UU APBN).',
 'medium'),

-- ===================== BAB IV: PENDAPATAN NEGARA (PERPAJAKAN, PNBP, HIBAH) =====================
('b0000000-0000-4000-8000-040400000000',
 'Dalam struktur APBN, Pendapatan Negara terdiri atas komponen...',
 'Penerimaan Perpajakan, Penerimaan Negara Bukan Pajak (PNBP), dan Hibah',
 'Utang dalam negeri dan utang luar negeri',
 'Belanja Pemerintah Pusat dan Transfer ke Daerah',
 'Penerimaan Perpajakan dan PNBP saja',
 null, 'A',
 'Pendapatan Negara = Penerimaan Perpajakan + Penerimaan Negara Bukan Pajak (PNBP) + Hibah.',
 'easy'),

('b0000000-0000-4000-8000-040400000000',
 'Pajak Penghasilan (PPh) diatur dalam UU Nomor 7 Tahun 1983. Perubahan terakhirnya dilakukan melalui...',
 'UU Nomor 28 Tahun 2009 tentang PDRD',
 'UU Nomor 7 Tahun 2021 tentang Harmonisasi Peraturan Perpajakan (HPP)',
 'UU Nomor 9 Tahun 2018 tentang PNBP',
 'UU Nomor 1 Tahun 2022 tentang HKPD',
 null, 'B',
 'PPh diatur dalam UU Nomor 7 Tahun 1983, terakhir diubah dengan UU Nomor 7 Tahun 2021 tentang Harmonisasi Peraturan Perpajakan (HPP).',
 'medium'),

('b0000000-0000-4000-8000-040400000000',
 'Sebuah dokumen perjanjian bernilai nominal Rp7.000.000 hendak dibubuhi bea materai. Berdasarkan UU Nomor 10 Tahun 2020, dokumen tersebut...',
 'Tidak dikenai bea materai karena nilainya di bawah batas',
 'Dikenai bea materai dengan tarif Rp3.000',
 'Dikenai bea materai dengan tarif tetap Rp10.000 karena nilainya di atas Rp5.000.000',
 'Dikenai bea materai dengan tarif Rp6.000',
 null, 'C',
 'Bea Materai (UU Nomor 10 Tahun 2020) dikenakan atas dokumen dengan nilai nominal di atas Rp5.000.000 dengan tarif tetap Rp10.000; dokumen Rp7.000.000 melampaui ambang tersebut.',
 'medium'),

('b0000000-0000-4000-8000-040400000000',
 'Penerimaan negara dari Bea Masuk cenderung terkikis seiring penghapusan bea masuk impor antarnegara ASEAN. Skema perdagangan yang menyebabkannya (berlaku penuh mulai 2015) adalah...',
 'Masyarakat Ekonomi Eropa',
 'World Trade Organization',
 'Trans-Pacific Partnership',
 'ASEAN Free Trade Area (AFTA)',
 null, 'D',
 'Penerimaan Bea Masuk terkikis dengan berlakunya ASEAN Free Trade Area (AFTA) yang menghapus bea masuk impor antarnegara ASEAN mulai 2015.',
 'medium'),

('b0000000-0000-4000-8000-040400000000',
 'Berikut ini merupakan jenis objek Penerimaan Negara Bukan Pajak (PNBP) menurut UU Nomor 9 Tahun 2018, KECUALI...',
 'Penerimaan Perpajakan Dalam Negeri',
 'Pemanfaatan Sumber Daya Alam',
 'Pengelolaan Barang Milik Negara',
 'Pengelolaan Kekayaan Negara Dipisahkan',
 null, 'A',
 'Enam objek PNBP: Pemanfaatan SDA, Pelayanan, Pengelolaan Kekayaan Negara Dipisahkan, Pengelolaan Barang Milik Negara, Pengelolaan Dana, dan Hak Negara Lainnya. Penerimaan Perpajakan adalah komponen pendapatan tersendiri, bukan PNBP.',
 'medium'),

('b0000000-0000-4000-8000-040400000000',
 'Negara memperoleh penerimaan dari royalti pemanfaatan hasil tambang oleh perusahaan pertambangan. Penerimaan ini digolongkan sebagai...',
 'Penerimaan Perpajakan',
 'Penerimaan Negara Bukan Pajak (PNBP) dari Pemanfaatan Sumber Daya Alam',
 'Hibah',
 'Pembiayaan',
 null, 'B',
 'Royalti atas pemanfaatan sumber daya alam termasuk objek PNBP, yaitu Pemanfaatan Sumber Daya Alam.',
 'medium'),

('b0000000-0000-4000-8000-040400000000',
 'Biaya yang dipungut atas pelayanan penerbitan paspor oleh instansi pemerintah kepada masyarakat termasuk objek PNBP berupa...',
 'Pemanfaatan Sumber Daya Alam',
 'Pengelolaan Kekayaan Negara Dipisahkan',
 'Pelayanan',
 'Pengelolaan Barang Milik Negara',
 null, 'C',
 'Pungutan atas pelayanan yang diberikan instansi pemerintah kepada masyarakat (mis. penerbitan paspor) termasuk objek PNBP berupa Pelayanan.',
 'medium'),

-- ===================== BAB V: BELANJA & PEMBIAYAAN =====================
('b0000000-0000-4000-8000-040500000000',
 'Dalam struktur APBN, Belanja Negara terdiri atas dua kelompok besar, yaitu...',
 'Belanja rutin dan belanja pembangunan',
 'Belanja pegawai dan belanja modal saja',
 'Pembiayaan dalam negeri dan pembiayaan luar negeri',
 'Belanja Pemerintah Pusat dan Transfer ke Daerah (TKD)',
 null, 'D',
 'Belanja Negara terdiri atas Belanja Pemerintah Pusat dan Transfer ke Daerah (TKD).',
 'easy'),

('b0000000-0000-4000-8000-040500000000',
 'Sebuah jenis Transfer ke Daerah bertujuan mengurangi ketimpangan kemampuan keuangan dan layanan publik antardaerah, dengan mempertimbangkan kebutuhan layanan publik dan kemampuan keuangan negara. Jenis TKD ini adalah...',
 'Dana Alokasi Umum (DAU)',
 'Dana Bagi Hasil (DBH)',
 'Dana Alokasi Khusus (DAK)',
 'Dana Otonomi Khusus',
 null, 'A',
 'Dana Alokasi Umum (DAU) bertujuan mengurangi ketimpangan kemampuan keuangan dan layanan publik antardaerah.',
 'medium'),

('b0000000-0000-4000-8000-040500000000',
 'Definisi pembiayaan sebagai "penerimaan yang harus dibayar kembali dan/atau pengeluaran yang akan diterima kembali" memiliki dasar hukum pada...',
 'Pasal 17 UU Nomor 1 Tahun 2004',
 'Pasal 1 Angka 17 UU Nomor 17 Tahun 2003',
 'Pasal 30 UU Nomor 17 Tahun 2003',
 'Pasal 23 ayat (5) UUD 1945',
 null, 'B',
 'Pasal 1 Angka 17 UU Nomor 17 Tahun 2003 mendefinisikan pembiayaan sebagai penerimaan yang harus dibayar kembali dan/atau pengeluaran yang akan diterima kembali.',
 'hard'),

('b0000000-0000-4000-8000-040500000000',
 'Manakah yang termasuk sumber Pembiayaan Dalam Negeri sektor Nonperbankan untuk menutup defisit anggaran?',
 'Pinjaman Program dan Pinjaman Proyek dari luar negeri',
 'Dana Bagi Hasil dan Dana Alokasi Umum',
 'Privatisasi BUMN, Penjualan Aset Restrukturisasi Perbankan, dan Penerbitan Surat Utang Negara (SUN)',
 'Bea Masuk dan Bea Keluar',
 null, 'C',
 'Sektor Nonperbankan dalam Pembiayaan Dalam Negeri mencakup Privatisasi BUMN, Penjualan Aset Restrukturisasi Perbankan, dan Penerbitan Surat Utang Negara (SUN).',
 'medium'),

('b0000000-0000-4000-8000-040500000000',
 'Debt Service Ratio (DSR) merupakan rasio yang membandingkan angsuran dan bunga pinjaman terhadap...',
 'Total belanja negara',
 'Produk Domestik Bruto (PDB)',
 'Penerimaan Negara Bukan Pajak (PNBP)',
 'Net ekspor (migas dan nonmigas)',
 null, 'D',
 'Debt Service Ratio (DSR) = rasio (Angsuran + Bunga Pinjaman) terhadap Net Ekspor (migas + nonmigas); makin besar rasio ini, makin berat beban negara.',
 'hard'),

('b0000000-0000-4000-8000-040500000000',
 'Pemerintah pusat mengalokasikan dana ke daerah tertentu untuk mendanai kegiatan khusus yang menjadi prioritas nasional (misalnya pembangunan infrastruktur tertentu di daerah). Jenis Transfer ke Daerah ini adalah...',
 'Dana Alokasi Khusus (DAK)',
 'Dana Alokasi Umum (DAU)',
 'Dana Bagi Hasil (DBH)',
 'Dana Insentif Nasional tanpa syarat',
 null, 'A',
 'Dana Alokasi Khusus (DAK) dialokasikan untuk mendanai kegiatan khusus yang menjadi prioritas nasional di daerah tertentu.',
 'medium'),

('b0000000-0000-4000-8000-040500000000',
 'Dalam suatu tahun anggaran, belanja negara direncanakan lebih besar daripada pendapatan negara. Selisih (defisit) tersebut ditutup melalui...',
 'Menaikkan seluruh tarif pajak seketika pada tahun berjalan',
 'Pembiayaan anggaran, antara lain melalui penerbitan Surat Utang Negara (SUN)',
 'Memangkas seluruh belanja hingga nol',
 'Mencetak uang baru oleh Kementerian Keuangan',
 null, 'B',
 'Defisit (belanja > pendapatan) ditutup melalui pembiayaan anggaran, antara lain penerbitan Surat Utang Negara (SUN) dan sumber pembiayaan lain sesuai ketentuan.',
 'medium'),

-- ===================== BAB VI: PENGAWASAN & PERTANGGUNGJAWABAN APBN =====================
('b0000000-0000-4000-8000-040600000000',
 'Sistem pengawasan atas pelaksanaan APBN terbagi menjadi dua sistem utama, yaitu...',
 'Sistem Pengawasan DPR dan Sistem Pengawasan Presiden',
 'Sistem Pengawasan Pusat dan Sistem Pengawasan Daerah',
 'Sistem Pengawasan Eksternal Pemerintah dan Sistem Pengawasan Internal Pemerintah',
 'Sistem Pengawasan Preventif dan Sistem Pengawasan Represif',
 null, 'C',
 'Pengawasan atas pelaksanaan APBN terbagi menjadi Sistem Pengawasan Eksternal Pemerintah dan Sistem Pengawasan Internal Pemerintah.',
 'easy'),

('b0000000-0000-4000-8000-040600000000',
 'Pemeriksaan atas pengelolaan dan tanggung jawab keuangan negara oleh BPK memiliki dasar hukum konstitusional pada...',
 'Pasal 20A UUD 1945',
 'Pasal 28 UUD 1945',
 'Pasal 30 UUD 1945',
 'Pasal 23E UUD 1945',
 null, 'D',
 'Pemeriksaan oleh BPK memiliki dasar konstitusional pada Pasal 23E UUD 1945.',
 'medium'),

('b0000000-0000-4000-8000-040600000000',
 'Berdasarkan Pasal 4 UU Nomor 15 Tahun 2004, BPK melaksanakan tiga tipe pemeriksaan, yaitu...',
 'Pemeriksaan keuangan, pemeriksaan kinerja, dan pemeriksaan dengan tujuan tertentu',
 'Pre-audit, post-audit, dan audit investigatif',
 'Pemeriksaan pajak, bea cukai, dan PNBP',
 'Pemeriksaan rechtmatigheid, wetmatigheid, dan doelmatigheid',
 null, 'A',
 'Tiga tipe pemeriksaan BPK menurut Pasal 4 UU Nomor 15 Tahun 2004: pemeriksaan keuangan, pemeriksaan kinerja, dan pemeriksaan dengan tujuan tertentu.',
 'medium'),

('b0000000-0000-4000-8000-040600000000',
 'BPKP dan Inspektorat Jenderal kementerian menjalankan fungsi Aparat Pengawasan Intern Pemerintah (APIP). BPKP awalnya dibentuk berdasarkan...',
 'Perpres Nomor 192 Tahun 2014',
 'Keppres RI Nomor 31 Tahun 1983',
 'Peraturan BPKP Nomor 9 Tahun 2021',
 'Perpres Nomor 47 Tahun 2009',
 null, 'B',
 'BPKP dibentuk berdasarkan Keppres RI Nomor 31 Tahun 1983, kemudian diatur ulang melalui Perpres Nomor 192 Tahun 2014 dan Peraturan BPKP Nomor 9 Tahun 2021.',
 'hard'),

('b0000000-0000-4000-8000-040600000000',
 'Sejak berlakunya UU Nomor 17 Tahun 2003, batas waktu penyampaian Laporan Keuangan Pemerintah Pusat kepada DPR mulai Tahun Anggaran 2005 dipercepat menjadi...',
 '2 bulan setelah tahun anggaran berakhir',
 '12 bulan setelah tahun anggaran berakhir',
 '6 bulan setelah tahun anggaran berakhir',
 '9 bulan setelah tahun anggaran berakhir',
 null, 'C',
 'Batas waktu penyampaian Laporan Keuangan ke DPR untuk TA 2004 adalah 9 bulan, kemudian dipercepat menjadi 6 bulan mulai TA 2005.',
 'hard'),

('b0000000-0000-4000-8000-040600000000',
 'Inspektorat Jenderal sebuah kementerian melakukan audit atas pelaksanaan anggaran di lingkungan kementeriannya sendiri. Kegiatan ini termasuk jenis pengawasan...',
 'Eksternal pemerintah oleh BPK',
 'Legislatif oleh DPR',
 'Yudikatif oleh pengadilan',
 'Internal pemerintah (APIP)',
 null, 'D',
 'Audit oleh Inspektorat Jenderal (bagian dari APIP) atas instansinya sendiri termasuk pengawasan internal pemerintah, berbeda dengan pengawasan eksternal oleh BPK.',
 'medium')
;
