-- =====================================================================
-- Bank soal APLIKATIF / STUDI KASUS — Modul Nilai-Nilai Kemenkeu (M2)
-- =====================================================================
-- Mengganti soal hafalan lama dengan soal studi kasus per bab, semua
-- berpijak pada materi/ringkasan modul (pengertian nilai & nilai organisasi,
-- sifat & fungsi nilai, budaya organisasi (Robbins), Core Values ASN
-- BerAKHLAK, serta 5 Nilai Kemenkeu: Integritas, Profesionalisme, Sinergi,
-- Pelayanan, Kesempurnaan — KMK 312/KMK.01/2011).
-- File ini idempotent: menghapus dulu soal M2 yang ada, lalu memasukkan yang baru.
--
-- Aman untuk skema baru: attempts menyimpan salinan soal (jsonb), jadi riwayat
-- lama tidak terpengaruh; seen_questions ikut terhapus otomatis (cascade).

delete from questions where chapter_id in (
  'b0000000-0000-4000-8000-020100000000',
  'b0000000-0000-4000-8000-020200000000',
  'b0000000-0000-4000-8000-020300000000',
  'b0000000-0000-4000-8000-020400000000',
  'b0000000-0000-4000-8000-020500000000'
);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values

-- ===================== BAB I: PENDAHULUAN =====================
('b0000000-0000-4000-8000-020100000000',
 'Seorang kepala unit kagum pada praktik manajemen sebuah perusahaan swasta dan ingin menyalinnya bulat-bulat ke unitnya tanpa penyesuaian apa pun. Berdasarkan Bab I modul, langkah yang paling tepat adalah...',
 'Mengadopsi dan mengadaptasi praktik yang sehat, lalu menyelaraskannya dengan nilai-nilai organisasi Kemenkeu',
 'Menolak semua praktik swasta karena tidak cocok dengan birokrasi pemerintah',
 'Menyalin seluruh praktik itu apa adanya karena sudah terbukti berhasil di swasta',
 'Menyerahkan keputusan sepenuhnya ke tiap pegawai tanpa pedoman bersama',
 null, 'A',
 'Bab I menyebut Kemenkeu sebagai organisasi modern mengadopsi DAN mengadaptasi praktik manajemen yang sehat (best practices), bukan menyalin mentah, lalu menetapkan nilai-nilai organisasi untuk diimplementasikan di seluruh unit sebagai budaya organisasi.',
 'medium'),

('b0000000-0000-4000-8000-020100000000',
 'Dalam rapat, seorang pegawai berkata, "Nilai organisasi itu cuma dokumen resmi yang diteken pimpinan; tidak ada hubungannya dengan cara saya bekerja sehari-hari." Tanggapan yang paling sesuai konsep nilai pada modul adalah...',
 'Benar, nilai hanyalah dokumen administratif organisasi',
 'Keliru, karena nilai adalah struktur jabatan formal organisasi',
 'Benar, karena yang penting hanya target kinerja, bukan nilai',
 'Keliru, karena nilai adalah keyakinan tentang baik/buruk yang justru memengaruhi tindakan dan menjadi pedoman berperilaku',
 null, 'D',
 'Modul mendefinisikan nilai sebagai keyakinan tentang apa yang dianggap baik/buruk yang memengaruhi tindakan seseorang dan menjadi pedoman berperilaku — bukan sekadar dokumen administratif.',
 'medium'),

('b0000000-0000-4000-8000-020100000000',
 'Seorang pejabat senior berpendapat bahwa nilai organisasi cukup dipahami dan dijalankan oleh pimpinan puncak saja, sedangkan staf pelaksana tidak perlu ambil pusing. Menurut Bab I, pendapat ini...',
 'Tepat, karena nilai organisasi adalah urusan strategis pimpinan',
 'Tepat, karena staf cukup mengikuti perintah',
 'Kurang tepat, karena nilai organisasi harus dimiliki dan menjadi pedoman bersama individu, kelompok, dan seluruh pemangku kepentingan organisasi',
 'Kurang tepat, karena justru hanya staf yang perlu memahami nilai',
 null, 'C',
 'Nilai organisasi didefinisikan sebagai keyakinan yang dimiliki individu, kelompok, dan seluruh pemangku kepentingan organisasi untuk berpikir, bertindak, dan berperilaku demi mencapai tujuan organisasi — bukan monopoli pimpinan.',
 'easy'),

('b0000000-0000-4000-8000-020100000000',
 'Dua pegawai berdebat tentang manfaat memahami nilai organisasi bagi pekerjaan mereka. Manakah pernyataan yang PALING selaras dengan tujuan pembahasan nilai pada modul ini?',
 'Nilai organisasi membantu menyeragamkan cara berpikir dan berperilaku untuk mencapai visi dan misi organisasi',
 'Nilai organisasi hanya menambah beban administrasi tanpa manfaat nyata',
 'Nilai organisasi menggantikan seluruh aturan dan SOP yang ada',
 'Nilai organisasi hanya relevan saat penilaian kinerja tahunan',
 null, 'A',
 'Modul menempatkan nilai organisasi sebagai pedoman bersama untuk berpikir, bertindak, dan berperilaku demi mencapai tujuan (visi & misi) organisasi, sehingga menjadi budaya organisasi.',
 'easy'),

('b0000000-0000-4000-8000-020100000000',
 'Sebuah unit menuliskan nilai-nilai organisasi di poster besar, tetapi perilaku kesehariannya tidak mencerminkan nilai itu sama sekali. Berdasarkan semangat Bab I, kondisi ini menunjukkan bahwa...',
 'Nilai sudah cukup diwujudkan karena telah dipajang',
 'Nilai baru bermakna bila diinternalisasi menjadi budaya organisasi yang tercermin dalam perilaku nyata, bukan sekadar dipajang',
 'Perilaku tidak penting selama nilai tertulis rapi',
 'Poster nilai adalah bentuk tertinggi implementasi nilai',
 null, 'B',
 'Modul menekankan nilai organisasi diimplementasikan dan diinternalisasi menjadi budaya organisasi; nilai bermakna ketika tercermin dalam perilaku nyata, bukan sekadar simbol tertulis.',
 'medium'),

-- ===================== BAB II: PENGERTIAN, PEMBENTUKAN, FUNGSI NILAI & BUDAYA ORGANISASI =====================
('b0000000-0000-4000-8000-020200000000',
 'Seorang pegawai menolak setiap perubahan tata nilai dengan alasan, "Nilai itu harga mati, sekali ditetapkan tidak boleh berubah selamanya." Berdasarkan sifat-sifat nilai pada Bab II, pandangan ini...',
 'Benar, karena nilai bersifat statis dan permanen',
 'Keliru, karena nilai justru tidak memiliki daya dorong',
 'Benar, karena nilai adalah realitas konkret yang tidak dapat diubah',
 'Keliru, karena salah satu sifat nilai adalah selalu berkembang seiring perkembangan kehidupan manusia',
 null, 'D',
 'Empat sifat nilai menurut modul: realitas abstrak; normatif (das sollen); daya dorong/motivator; dan selalu berkembang seiring kehidupan manusia. Jadi nilai bukan sesuatu yang statis.',
 'medium'),

('b0000000-0000-4000-8000-020200000000',
 'Dalam sebuah organisasi, nilai "jujur" bukan sekadar menggambarkan kenyataan, melainkan menjadi keharusan dan cita-cita yang mendorong pegawai bertindak benar. Sifat nilai yang paling tepat menggambarkan hal ini adalah...',
 'Bersifat realitas abstrak semata',
 'Bersifat teknis dan prosedural',
 'Bersifat statis dan tidak berubah',
 'Bersifat normatif — mengandung harapan, cita-cita, dan keharusan (das sollen)',
 null, 'D',
 'Sifat normatif nilai berarti nilai mengandung harapan, cita-cita, dan keharusan (das sollen) — bagaimana seharusnya seseorang bertindak, bukan sekadar menggambarkan kenyataan (das sein).',
 'medium'),

('b0000000-0000-4000-8000-020200000000',
 'Seorang pegawai merasa bersemangat dan terdorong bekerja lebih baik setiap kali mengingat nilai pelayanan yang ia yakini. Fenomena ini paling tepat dijelaskan oleh sifat nilai sebagai...',
 'Realitas abstrak',
 'Norma yang kaku',
 'Daya dorong/motivator, dengan manusia sebagai pendukung nilai',
 'Aturan hukuman',
 null, 'C',
 'Salah satu sifat nilai adalah berfungsi sebagai daya dorong/motivator; manusia adalah pendukung nilai sehingga nilai mendorong perilaku ke arah yang diyakini baik.',
 'medium'),

('b0000000-0000-4000-8000-020200000000',
 'Sebuah unit sangat menekankan ketelitian: setiap dokumen diperiksa berulang agar tidak ada satu angka pun yang salah. Dalam enam karakteristik budaya organisasi menurut Robbins, penekanan ini mencerminkan karakteristik...',
 'Innovation and risk taking',
 'Attention to detail (perhatian pada detail)',
 'Team orientation',
 'Stability',
 null, 'B',
 'Attention to detail adalah karakteristik budaya organisasi yang menekankan ketelitian, analisis, dan perhatian pada detail — sesuai perilaku unit yang memeriksa dokumen secara cermat.',
 'medium'),

('b0000000-0000-4000-8000-020200000000',
 'Pimpinan sebuah unit mendorong pegawai berani mencoba pendekatan baru dan mengambil risiko terukur demi perbaikan, meski ada kemungkinan gagal. Karakteristik budaya organisasi (Robbins) yang paling menonjol di sini adalah...',
 'Attention to detail',
 'Stability',
 'People orientation',
 'Innovation and risk taking (inovasi & keberanian mengambil risiko)',
 null, 'D',
 'Innovation and risk taking menggambarkan sejauh mana pegawai didorong untuk inovatif dan berani mengambil risiko — persis situasi yang dijelaskan.',
 'medium'),

('b0000000-0000-4000-8000-020200000000',
 'Manajer A menilai pegawai murni dari hasil/target yang dicapai; Manajer B sangat memperhatikan dampak keputusan terhadap orang-orang di dalam tim. Dalam karakteristik Robbins, orientasi Manajer A dan Manajer B berturut-turut adalah...',
 'Outcome orientation dan People orientation',
 'People orientation dan Team orientation',
 'Stability dan Innovation',
 'Team orientation dan Attention to detail',
 null, 'A',
 'Outcome orientation berfokus pada hasil/keluaran, sedangkan people orientation mempertimbangkan efek keputusan terhadap orang-orang dalam organisasi — dua dari enam karakteristik budaya organisasi Robbins.',
 'hard'),

('b0000000-0000-4000-8000-020200000000',
 'Seorang direktur ingin menetapkan nilai organisasi secara cepat dengan mengumumkannya sepihak melalui surat edaran, tanpa menggali kebiasaan baik yang sudah hidup di unit. Menurut tahapan identifikasi nilai (Heathfield) pada Bab II, cara ini...',
 'Sudah tepat karena penetapan nilai adalah wewenang tunggal pimpinan',
 'Kurang tepat, karena tahap awal seharusnya menggali, mempelajari, dan mendiskusikan nilai yang berkembang, lalu mencari konsensus',
 'Sudah tepat karena semakin cepat semakin baik',
 'Kurang tepat, karena nilai seharusnya ditentukan oleh pihak eksternal',
 null, 'B',
 'Menurut Heathfield, identifikasi nilai dimulai dari menggali, mempelajari, dan mendiskusikan nilai yang berkembang dalam keseharian organisasi, kemudian mencari kesepakatan/konsensus di antara para pemimpin — bukan pengumuman sepihak.',
 'hard'),

('b0000000-0000-4000-8000-020200000000',
 'Seorang narasumber menggambarkan nilai organisasi sebagai "DNA" organisasi. Menurut Roope Heinila yang dikutip modul, "DNA" tersebut merupakan gabungan dari...',
 'Anggaran, aset, dan target kinerja',
 'Visi, misi, dan logo resmi',
 'Kepercayaan (beliefs), filosofi (philosophies), dan prinsip-prinsip (principles) yang menjadi pendorong organisasi',
 'Struktur jabatan, uraian tugas, dan SOP',
 null, 'C',
 'Roope Heinila menyebut nilai organisasi sebagai DNA organisasi: gabungan kepercayaan (beliefs), filosofi (philosophies), dan prinsip-prinsip (principles) yang menjadi pendorong (driver) organisasi.',
 'medium'),

-- ===================== BAB III: CORE VALUES ASN BerAKHLAK & KETERKAITAN =====================
('b0000000-0000-4000-8000-020300000000',
 'Seorang petugas layanan menghadapi pemohon yang bingung dan gugup. Ia menyapa ramah, menjelaskan prosedur dengan sabar, dan memastikan kebutuhan pemohon terpenuhi dengan baik. Nilai dasar ASN (BerAKHLAK) yang paling tampak adalah...',
 'Loyal',
 'Berorientasi Pelayanan',
 'Adaptif',
 'Harmonis',
 null, 'B',
 'Berorientasi Pelayanan berarti berkomitmen memberikan pelayanan prima demi kepuasan masyarakat — memahami dan memenuhi kebutuhan, ramah, cekatan, solutif, dan dapat diandalkan.',
 'easy'),

('b0000000-0000-4000-8000-020300000000',
 'Seorang bendahara diminta atasannya mempercepat pencairan dengan melewati satu tahap verifikasi. Ia menolak dan tetap menjalankan prosedur secara jujur dan bertanggung jawab. Perilaku ini paling mencerminkan nilai BerAKHLAK...',
 'Kompeten',
 'Kolaboratif',
 'Akuntabel',
 'Adaptif',
 null, 'C',
 'Akuntabel berarti bertanggung jawab atas kepercayaan yang diberikan: jujur, cermat, disiplin, berintegritas, dan tidak menyalahgunakan kewenangan/jabatan — termasuk menolak menerabas prosedur.',
 'medium'),

('b0000000-0000-4000-8000-020300000000',
 'Melihat rekan baru kesulitan menguasai aplikasi kerja, seorang pegawai menyisihkan waktu mengajarinya dan berbagi pengetahuan agar hasil kerja tim membaik. Nilai BerAKHLAK yang paling menonjol adalah...',
 'Kompeten (terus belajar & membantu orang lain belajar)',
 'Loyal',
 'Harmonis',
 'Berorientasi Pelayanan',
 null, 'A',
 'Kompeten berarti terus meningkatkan kompetensi diri, membantu orang lain belajar, dan menyelesaikan tugas dengan kualitas terbaik.',
 'medium'),

('b0000000-0000-4000-8000-020300000000',
 'Di sebuah unit terdapat pegawai dari beragam latar belakang suku dan agama. Seorang pegawai aktif membangun suasana saling menghargai dan suka menolong tanpa membeda-bedakan. Nilai BerAKHLAK yang paling sesuai adalah...',
 'Akuntabel',
 'Adaptif',
 'Harmonis (menghargai perbedaan & membangun lingkungan kondusif)',
 'Loyal',
 null, 'C',
 'Harmonis berarti saling peduli dan menghargai perbedaan, suka menolong, dan membangun lingkungan kerja yang kondusif.',
 'easy'),

('b0000000-0000-4000-8000-020300000000',
 'Seorang pegawai mengetahui informasi rahasia jabatan yang bila dibocorkan bisa merugikan negara. Ia menjaganya rapat dan tetap menjaga nama baik instansi meski ditawari imbalan. Nilai BerAKHLAK yang paling tepat adalah...',
 'Loyal (menjaga nama baik & rahasia jabatan/negara)',
 'Kompeten',
 'Kolaboratif',
 'Berorientasi Pelayanan',
 null, 'A',
 'Loyal berarti berdedikasi dan mengutamakan kepentingan bangsa dan negara, termasuk menjaga nama baik ASN, pimpinan, instansi, serta rahasia jabatan dan negara.',
 'medium'),

('b0000000-0000-4000-8000-020300000000',
 'Ketika kebijakan dan sistem kerja berubah cepat, seorang pegawai justru antusias mempelajari hal baru, berinovasi, dan proaktif menyesuaikan diri. Nilai BerAKHLAK yang paling tampak adalah...',
 'Stabilitas',
 'Adaptif (cepat menyesuaikan diri, terus berinovasi, bertindak proaktif)',
 'Harmonis',
 'Akuntabel',
 null, 'B',
 'Adaptif berarti terus berinovasi dan antusias dalam menggerakkan/menghadapi perubahan, cepat menyesuaikan diri, dan bertindak proaktif.',
 'easy'),

('b0000000-0000-4000-8000-020300000000',
 'Sebuah tugas lintas unit menuntut banyak pihak bekerja sama. Seorang pegawai terbuka berkontribusi, berbagi sumber daya, dan menggerakkan kerja sama untuk hasil terbaik. Nilai BerAKHLAK yang paling sesuai adalah...',
 'Loyal',
 'Kompeten',
 'Kolaboratif (membangun kerja sama yang sinergis)',
 'Akuntabel',
 null, 'C',
 'Kolaboratif berarti membangun kerja sama yang sinergis: memberi kesempatan berbagai pihak berkontribusi, terbuka bekerja sama, dan menggerakkan pemanfaatan sumber daya bersama.',
 'easy'),

('b0000000-0000-4000-8000-020300000000',
 'Seorang pegawai Kemenkeu ingin memahami bagaimana nilai ASN "Kompeten" bersambung dengan Nilai-Nilai Kemenkeu. Berdasarkan tabel keterkaitan pada Bab III, "Kompeten" paling selaras dengan Nilai Kemenkeu...',
 'Integritas',
 'Profesionalisme',
 'Sinergi',
 'Kesempurnaan',
 null, 'B',
 'Tabel keterkaitan Core Values ASN dan Nilai-Nilai Kemenkeu memetakan nilai ASN "Kompeten" selaras dengan Nilai Kemenkeu "Profesionalisme" (bekerja atas dasar kompetensi terbaik).',
 'medium'),

('b0000000-0000-4000-8000-020300000000',
 'Dalam diskusi, seorang pegawai keliru menyebut bahwa Core Values ASN dan Nilai-Nilai Kemenkeu saling bertentangan sehingga harus dipilih salah satu. Berdasarkan modul, koreksi yang tepat adalah...',
 'Keduanya memang bertentangan dan tidak bisa dijalankan bersama',
 'Keduanya saling mendukung dan memperkuat karena berkonsep dasar sama, yaitu mengelola diri selaras tujuan pelaksanaan tugas',
 'Nilai Kemenkeu harus dibuang dan diganti BerAKHLAK sepenuhnya',
 'BerAKHLAK hanya berlaku bagi pejabat, bukan pelaksana',
 null, 'B',
 'Modul menegaskan Nilai Dasar ASN (BerAKHLAK) dan Nilai-Nilai Kemenkeu saling mendukung — bukan bertentangan — karena konsep dasarnya sama: ASN/pegawai mengelola pribadi selaras dengan tujuan pelaksanaan tugas.',
 'medium'),

-- ===================== BAB IV: NILAI-NILAI KEMENTERIAN KEUANGAN =====================
('b0000000-0000-4000-8000-020400000000',
 'Seorang pegawai diminta rekannya "sedikit menyesuaikan" angka dalam laporan agar terlihat lebih baik. Ia menolak dan melaporkan data apa adanya. Nilai Kemenkeu dan perilaku utama yang paling tepat menggambarkan sikapnya adalah...',
 'Sinergi — menemukan solusi terbaik',
 'Kesempurnaan — perbaikan terus-menerus',
 'Pelayanan — bersikap proaktif',
 'Integritas — bersikap jujur, tulus, dan dapat dipercaya',
 null, 'D',
 'Menolak memanipulasi data dan menyajikan laporan apa adanya adalah perwujudan Integritas, khususnya perilaku utama bersikap jujur, tulus, dan dapat dipercaya.',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Seorang pejabat ditawari gratifikasi oleh mitra kerja agar memuluskan suatu urusan. Ia menolak tegas demi menjaga martabat dan menghindari perbuatan tercela. Perilaku ini paling tepat dikaitkan dengan Nilai Kemenkeu...',
 'Profesionalisme — bekerja dengan hati',
 'Pelayanan — sepenuh hati',
 'Integritas — menjaga martabat dan tidak melakukan hal-hal tercela',
 'Sinergi — saling percaya',
 null, 'C',
 'Menolak gratifikasi demi menjaga martabat dan menghindari perbuatan tercela adalah perilaku utama kedua dari Integritas: menjaga martabat dan tidak melakukan hal-hal tercela.',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Seorang analis rutin memutakhirkan keahliannya, mendalami peraturan terbaru, dan menguasai aplikasi baru agar hasil kerjanya efisien dan berkualitas. Nilai Kemenkeu dan perilaku utama yang paling sesuai adalah...',
 'Profesionalisme — mempunyai keahlian dan pengetahuan yang luas',
 'Kesempurnaan — mengembangkan inovasi',
 'Sinergi — saling menghormati',
 'Integritas — jujur dan tulus',
 null, 'A',
 'Terus meningkatkan keahlian, pengetahuan, dan penguasaan teknologi agar bekerja efisien dan berkualitas adalah perilaku utama pertama Profesionalisme: mempunyai keahlian dan pengetahuan yang luas.',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Seorang pegawai mengerjakan tugas bukan sekadar demi gaji, melainkan dengan sepenuh perasaan: ia menyeimbangkan SOP dengan hati nurani dan sungguh mencintai pekerjaannya. Hal ini adalah wujud perilaku utama Profesionalisme yang disebut...',
 'Bersikap proaktif',
 'Bekerja dengan hati',
 'Melakukan perbaikan terus-menerus',
 'Menjaga martabat',
 null, 'B',
 'Bekerja dengan hati adalah perilaku utama kedua Profesionalisme: menyeimbangkan SOP dengan hati nurani/perasaan; mencintai pekerjaan, bukan bekerja karena terpaksa atau sekadar dibayar.',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Dua unit sempat berselisih karena saling curiga soal pembagian tugas. Seorang pegawai mengajak keduanya menaruh sangka baik, saling percaya, dan saling menghormati agar kerja sama kembali produktif. Nilai Kemenkeu yang paling sesuai adalah...',
 'Integritas',
 'Kesempurnaan',
 'Sinergi — memiliki sangka baik, saling percaya, dan saling menghormati',
 'Pelayanan',
 null, 'C',
 'Membangun hubungan kerja sama internal yang produktif dengan menaruh sangka baik, saling percaya, dan saling menghormati adalah perilaku utama pertama Sinergi.',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Menghadapi persoalan yang rumit, sebuah tim lintas unit mengumpulkan data akurat dan berpikir "out of the box" untuk menemukan jalan keluar yang paling bermanfaat bagi organisasi. Perilaku utama Sinergi yang paling tepat adalah...',
 'Memiliki sangka baik',
 'Bekerja dengan hati',
 'Menjaga martabat',
 'Menemukan dan melaksanakan solusi terbaik',
 null, 'D',
 'Menemukan dan melaksanakan solusi terbaik adalah perilaku utama kedua Sinergi, yang membutuhkan data/informasi akurat dan kreativitas (berpikir out of the box).',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Sebuah loket layanan dinilai buruk karena berbelit, lambat, dan tidak transparan. Sebagai perbaikan berbasis Nilai Kemenkeu "Pelayanan", prinsip yang seharusnya diterapkan adalah...',
 'Tertutup, birokratis, dan kaku',
 'Cepat namun boleh mengorbankan akurasi',
 'Sepenuh hati, transparan, cepat, akurat, dan aman',
 'Formal dan hierarkis di atas segalanya',
 null, 'C',
 'Nilai Pelayanan berarti memberikan layanan yang memenuhi kepuasan pemangku kepentingan, dilaksanakan dengan sepenuh hati, transparan, cepat, akurat, dan aman.',
 'easy'),

('b0000000-0000-4000-8000-020400000000',
 'Sebelum diminta, seorang petugas melihat pengunjung kebingungan lalu menghampiri, menawarkan bantuan, dan cepat tanggap menyelesaikan kebutuhannya. Perilaku ini merupakan perilaku utama Pelayanan yang disebut...',
 'Bersikap proaktif dan cepat tanggap',
 'Melakukan perbaikan terus-menerus',
 'Menjaga martabat',
 'Mempunyai keahlian yang luas',
 null, 'A',
 'Menghampiri dan menawarkan bantuan tanpa diminta serta cepat tanggap adalah perilaku utama kedua Pelayanan: bersikap proaktif dan cepat tanggap.',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Setelah menerima penghargaan unit terbaik, sebuah tim tidak cepat berpuas diri; mereka mengevaluasi hasil kerja dan mencari cara agar tahun depan lebih baik lagi. Nilai Kemenkeu dan perilaku utama yang paling tepat adalah...',
 'Integritas — jujur',
 'Kesempurnaan — melakukan perbaikan terus-menerus',
 'Pelayanan — transparan',
 'Sinergi — saling percaya',
 null, 'B',
 'Tidak cepat puas dengan prestasi dan selalu mengevaluasi untuk menjadi lebih baik adalah perilaku utama pertama Kesempurnaan: melakukan perbaikan terus-menerus.',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Seorang pegawai mengembangkan aplikasi sederhana yang memangkas waktu proses dari tiga hari menjadi tiga jam, tanpa melanggar aturan. Nilai Kemenkeu dan perilaku utama yang paling sesuai adalah...',
 'Kesempurnaan — mengembangkan inovasi dan kreativitas',
 'Integritas — menjaga martabat',
 'Sinergi — sangka baik',
 'Pelayanan — proaktif',
 null, 'A',
 'Mengembangkan inovasi dan kreativitas (proses/hasil pengembangan pengetahuan & keterampilan untuk nilai tambah) adalah perilaku utama kedua Kesempurnaan.',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Seorang pegawai baru bertanya apa dasar hukum penetapan lima Nilai-Nilai Kementerian Keuangan (Integritas, Profesionalisme, Sinergi, Pelayanan, Kesempurnaan). Jawaban yang tepat adalah...',
 'Undang-Undang tentang ASN semata',
 'Peraturan Pemerintah Nomor 42 Tahun 2004',
 'Surat Edaran Menteri PANRB Nomor 20 Tahun 2021',
 'Keputusan Menteri Keuangan Nomor 312/KMK.01/2011',
 null, 'D',
 'Nilai-Nilai Kementerian Keuangan ditetapkan melalui Keputusan Menteri Keuangan Nomor 312/KMK.01/2011, yang juga mengatur kaidah perilaku utama tiap nilai.',
 'medium'),

('b0000000-0000-4000-8000-020400000000',
 'Seorang pegawai berpendapat, "Karena kesempurnaan hakiki hanya milik Tuhan, kita tidak perlu repot-repot memperbaiki diri." Berdasarkan makna Nilai "Kesempurnaan", pendapat ini...',
 'Tepat, karena usaha manusia pasti sia-sia',
 'Keliru, karena kesempurnaan bisa dicapai sepenuhnya oleh manusia',
 'Tepat, karena perbaikan adalah tugas pimpinan saja',
 'Keliru, karena justru manusia tidak akan pernah sempurna sehingga perlu pengembangan diri tanpa batas melalui perbaikan dan inovasi terus-menerus',
 null, 'D',
 'Nilai Kesempurnaan justru bermakna: karena kesempurnaan hakiki milik Tuhan, manusia tidak akan pernah sempurna sehingga perlu usaha pengembangan diri tanpa batas lewat perbaikan terus-menerus dan inovasi/kreativitas.',
 'hard'),

-- ===================== BAB V: PENUTUP & SINTESIS =====================
('b0000000-0000-4000-8000-020500000000',
 'Seorang pegawai bimbang: haruskah ia mengutamakan Nilai Dasar ASN (BerAKHLAK) atau Nilai-Nilai Kemenkeu dalam bekerja? Berdasarkan Bab V, sikap yang paling tepat adalah...',
 'Memilih salah satu karena keduanya bertentangan',
 'Menjalankan keduanya secara selaras karena saling mendukung dengan konsep dasar yang sama',
 'Mengabaikan keduanya dan cukup mengikuti perintah atasan',
 'Menunda penerapan sampai ada aturan baru',
 null, 'B',
 'Bab V menegaskan Nilai Dasar ASN dan Nilai-Nilai Kemenkeu saling mendukung karena konsep dasarnya sama — mengelola pribadi selaras tujuan pelaksanaan tugas — sehingga dijalankan bersama secara selaras.',
 'easy'),

('b0000000-0000-4000-8000-020500000000',
 'Sebuah unit memiliki pegawai-pegawai hebat secara individu, tetapi kinerja unit tetap rendah karena tidak ada keterpaduan antara individu, kelompok, dan organisasi. Berdasarkan Bab V, akar masalahnya berkaitan dengan...',
 'Kurangnya anggaran operasional',
 'Lokasi kantor yang kurang strategis',
 'Lemahnya kohesi individu-kelompok-organisasi sebagai prasyarat kinerja melalui budaya organisasi',
 'Jumlah pegawai yang terlalu sedikit',
 null, 'C',
 'Bab V menyatakan kohesi individu-kelompok-organisasi adalah prasyarat kinerja organisasi melalui budaya organisasi; tanpa keterpaduan itu, keunggulan individu tidak berbuah kinerja organisasi.',
 'hard'),

('b0000000-0000-4000-8000-020500000000',
 'Seorang pegawai konsisten jujur, terus meningkatkan kompetensi, kompak dengan tim, melayani sepenuh hati, dan tak pernah berhenti memperbaiki diri. Sikap menyeluruh ini paling tepat dimaknai sebagai...',
 'Internalisasi Nilai-Nilai Kemenkeu (Integritas, Profesionalisme, Sinergi, Pelayanan, Kesempurnaan) menjadi budaya kerja',
 'Sekadar memenuhi syarat administratif kenaikan pangkat',
 'Kepatuhan pada satu nilai saja secara berlebihan',
 'Perilaku yang tidak berkaitan dengan nilai organisasi',
 null, 'A',
 'Rangkaian perilaku itu mencerminkan kelima Nilai-Nilai Kemenkeu yang terinternalisasi menjadi budaya kerja — inti pesan Bab V bahwa nilai diwujudkan dalam perilaku nyata sehari-hari.',
 'medium'),

('b0000000-0000-4000-8000-020500000000',
 'Manakah pernyataan yang PALING tepat menggambarkan peran Nilai Dasar ASN BerAKHLAK menurut rangkuman Bab V?',
 'Sekadar slogan tanpa pengaruh pada budaya kerja',
 'Syarat administratif semata untuk kenaikan pangkat',
 'Pengganti total seluruh nilai organisasi setiap kementerian',
 'Tonggak baru untuk membangun budaya ASN yang selaras dengan harapan masyarakat',
 null, 'D',
 'Bab V menempatkan Nilai Dasar ASN BerAKHLAK sebagai tonggak baru bagi seluruh ASN untuk membangun budaya ASN yang selaras dengan harapan masyarakat.',
 'easy'),

('b0000000-0000-4000-8000-020500000000',
 'Dalam sebuah kasus, pegawai harus memilih antara mempercepat layanan dengan menerabas prosedur, atau tetap patuh prosedur meski sedikit lebih lama. Keputusan yang paling selaras dengan keseluruhan Nilai-Nilai Kemenkeu adalah...',
 'Menerabas prosedur demi kecepatan semata',
 'Menyerahkan keputusan kepada pemohon',
 'Menolak melayani agar tidak berisiko',
 'Tetap patuh prosedur (integritas & akurasi) sambil mengupayakan layanan yang cepat, transparan, dan aman',
 null, 'D',
 'Nilai-Nilai Kemenkeu menuntut keterpaduan: Integritas dan Pelayanan yang akurat/aman tidak boleh dikorbankan demi kecepatan. Pilihan terbaik adalah tetap patuh prosedur sambil mengupayakan layanan cepat, transparan, dan aman.',
 'medium')
;
