-- 5 soal per bab untuk Modul Nilai-Nilai Kementerian Keuangan (M2)

delete from questions where chapter_id in (
  'b0000000-0000-4000-8000-020100000000',
  'b0000000-0000-4000-8000-020200000000',
  'b0000000-0000-4000-8000-020300000000',
  'b0000000-0000-4000-8000-020400000000',
  'b0000000-0000-4000-8000-020500000000'
);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values
('b0000000-0000-4000-8000-020100000000', 'Menurut modul Nilai-Nilai Kementerian Keuangan, apa yang dimaksud dengan "nilai"?', 'Keyakinan tentang apa yang dianggap baik/buruk yang memengaruhi tindakan seseorang dan menjadi pedoman hidup bermasyarakat', 'Aturan tertulis yang mengikat seluruh pegawai organisasi', 'Standar kinerja yang ditetapkan oleh pimpinan organisasi', 'Kumpulan prosedur kerja yang berlaku di suatu instansi', null, 'A', 'Modul mendefinisikan nilai sebagai keyakinan tentang apa yang dianggap baik/buruk, yang memengaruhi tindakan seseorang dan menjadi pedoman hidup bermasyarakat.', 'easy'),
('b0000000-0000-4000-8000-020100000000', 'Nilai organisasi, menurut Bab I modul ini, harus dimiliki dan dijadikan pedoman bersama oleh siapa saja di dalam organisasi?', 'Hanya pimpinan puncak organisasi', 'Individu, kelompok, dan seluruh pemangku kepentingan organisasi', 'Hanya pegawai baru yang belum berpengalaman', 'Hanya unit yang menangani sumber daya manusia', null, 'B', 'Nilai organisasi didefinisikan sebagai keyakinan & kepercayaan yang dimiliki individu, kelompok, dan seluruh pemangku kepentingan organisasi untuk berpikir, bertindak, dan berperilaku demi mencapai tujuan organisasi.', 'easy'),
('b0000000-0000-4000-8000-020100000000', 'Bab I modul ini menjelaskan bahwa Kementerian Keuangan sebagai organisasi modern melakukan apa terhadap praktik manajemen yang sehat (best practices)?', 'Mengabaikannya karena dianggap tidak relevan dengan birokrasi pemerintah', 'Menyerahkan sepenuhnya kepada masing-masing unit Eselon I tanpa pedoman bersama', 'Mengadopsi dan mengadaptasinya, lalu menetapkan nilai-nilai organisasi untuk diimplementasikan di seluruh unit kerja', 'Menggantinya sepenuhnya dengan praktik dari sektor swasta tanpa penyesuaian', null, 'C', 'Modul menyebutkan Kemenkeu mengadopsi & mengadaptasi praktik manajemen sehat (best practices), dengan nilai-nilai organisasi ditetapkan dan diimplementasikan di seluruh unit kerja sebagai budaya organisasi menuju visi & misi Kemenkeu.', 'medium'),
('b0000000-0000-4000-8000-020100000000', 'Modul Nilai-Nilai Kementerian Keuangan ini secara khusus disusun sebagai bahan belajar mandiri untuk keperluan apa?', 'Seleksi Calon Pegawai Negeri Sipil (CPNS) Kemenkeu', 'Ujian dinas kenaikan golongan struktural eselon I', 'Ujian sertifikasi jabatan fungsional auditor', 'Ujian Penyesuaian Kenaikan Pangkat (UPKP) Tingkat V di Kementerian Keuangan RI', null, 'D', 'Sesuai Bab I, modul ini disusun sebagai bahan belajar mandiri untuk Ujian Penyesuaian Kenaikan Pangkat (UPKP) Tingkat V di Kementerian Keuangan RI.', 'easy'),
('b0000000-0000-4000-8000-020100000000', 'Cakupan pembahasan modul ini, sebagaimana disebutkan pada Bab I Pendahuluan, meliputi hal-hal berikut, KECUALI:', 'Perhitungan tunjangan kinerja berbasis capaian nilai organisasi', 'Proses pembentukan dan fungsi nilai', 'Internalisasi nilai melalui budaya organisasi', 'Pengertian nilai dan nilai organisasi', 'Keterkaitan nilai ASN dan Nilai-Nilai Kemenkeu sebagai pedoman berperilaku', 'A', 'Cakupan modul meliputi pengertian nilai & nilai organisasi, proses pembentukan, fungsi, internalisasi nilai melalui budaya organisasi, serta keterkaitan nilai ASN dan Nilai-Nilai Kemenkeu. Perhitungan tunjangan kinerja tidak disebutkan sebagai cakupan modul.', 'medium'),
('b0000000-0000-4000-8000-020200000000', 'Menurut Kluckhohn, sebagaimana dikutip dalam Bab II modul ini, nilai adalah konsepsi dari apa yang diinginkan yang memengaruhi apa?', 'Struktur organisasi perusahaan', 'Penentuan cara dan tujuan tindakan', 'Besaran gaji dan tunjangan pegawai', 'Jenis pendidikan formal seseorang', null, 'B', 'Kluckhohn mendefinisikan nilai sebagai konsepsi dari apa yang diinginkan yang memengaruhi penentuan cara dan tujuan tindakan.', 'medium'),
('b0000000-0000-4000-8000-020200000000', 'Sifat-sifat nilai yang dijelaskan dalam Bab II modul ini ada empat. Manakah yang BUKAN merupakan salah satu sifat nilai tersebut?', 'Merupakan realitas abstrak yang ada dalam kehidupan manusia', 'Bersifat normatif, mengandung harapan, cita-cita, dan keharusan', 'Bersifat statis dan tidak pernah berubah sepanjang masa', 'Berfungsi sebagai daya dorong/motivator, manusia adalah pendukung nilai', null, 'C', 'Empat sifat nilai menurut modul: (1) realitas abstrak, (2) normatif/das sollen, (3) daya dorong/motivator, dan (4) nilai selalu berkembang seiring kehidupan manusia -- bukan statis/tidak berubah.', 'medium'),
('b0000000-0000-4000-8000-020200000000', 'Menurut Roope Heinila (2024) yang dikutip dalam Bab II, nilai organisasi pada intinya adalah gabungan dari apa?', 'Anggaran, aset, dan target kinerja organisasi', 'Visi, misi, dan logo resmi organisasi', 'Struktur jabatan, uraian tugas, dan standar operasional prosedur', 'Kepercayaan (beliefs), filosofi (philosophies), dan prinsip-prinsip (principles) yang menjadi pendorong (driver) organisasi', null, 'D', 'Roope Heinila menyebut nilai organisasi sebagai "DNA" perusahaan, yaitu kepercayaan (beliefs), filosofi (philosophies), dan prinsip-prinsip (principles) yang menjadi pendorong (driver) organisasi.', 'medium'),
('b0000000-0000-4000-8000-020200000000', 'Menurut Susan M. Heathfield (2021) dalam Bab II, urutan awal proses identifikasi nilai organisasi dimulai dari langkah apa?', 'Menggali, mempelajari, dan mendiskusikan nilai yang berkembang dalam kehidupan sehari-hari organisasi', 'Menetapkan sanksi bagi pelanggar nilai organisasi', 'Mengumumkan nilai organisasi secara sepihak oleh direksi', 'Melakukan survei kepuasan pelanggan eksternal', null, 'A', 'Tahapan pertama menurut Heathfield adalah menggali, mempelajari, dan mendiskusikan nilai yang berkembang dalam kehidupan sehari-hari organisasi, baru kemudian mencari kesepakatan/konsensus di antara leader/manager.', 'hard'),
('b0000000-0000-4000-8000-020200000000', 'Stephen P. Robbins dalam bukunya "Organizational Behavior" menyebutkan enam karakteristik budaya organisasi. Manakah pasangan berikut yang BUKAN termasuk keenam karakteristik tersebut?', 'Innovation and risk taking, serta Attention to detail', 'Financial orientation, serta Market competitiveness', 'Team orientation, serta Stability', 'Outcome orientation, serta People orientation', null, 'B', 'Enam karakteristik budaya organisasi menurut Robbins adalah innovation and risk taking, attention to detail, outcome orientation, people orientation, team orientation, dan stability. "Financial orientation" dan "market competitiveness" tidak termasuk di dalamnya.', 'medium'),
('b0000000-0000-4000-8000-020300000000', 'Core Values ASN BerAKHLAK diresmikan oleh Presiden Joko Widodo pada tanggal berapa?', '17 Agustus 2021', '1 Januari 2021', '27 Juli 2021', '20 Mei 2021', null, 'C', 'Sesuai Bab III, BerAKHLAK diresmikan oleh Presiden Joko Widodo pada tanggal 27 Juli 2021.', 'easy'),
('b0000000-0000-4000-8000-020300000000', 'Akronim BerAKHLAK terdiri dari tujuh nilai dasar ASN. Manakah urutan yang benar sesuai modul?', 'Berkinerja, Akuntabel, Kompeten, Harmonis, Loyal, Adaptif, Kolaboratif', 'Berintegritas, Akuntabel, Kolaboratif, Harmonis, Loyal, Adaptif, Kompeten', 'Berorientasi Pelayanan, Adaptif, Kompeten, Harmonis, Loyal, Akuntabel, Kolaboratif', 'Berorientasi Pelayanan, Akuntabel, Kompeten, Harmonis, Loyal, Adaptif, Kolaboratif', null, 'D', 'BerAKHLAK adalah akronim dari Berorientasi Pelayanan, Akuntabel, Kompeten, Harmonis, Loyal, Adaptif, dan Kolaboratif -- 7 nilai dasar ASN.', 'easy'),
('b0000000-0000-4000-8000-020300000000', 'Dasar hukum peluncuran implementasi Core Values dan Employer Branding ASN (BerAKHLAK) adalah Surat Edaran Menteri PANRB Nomor berapa?', 'SE Menteri PANRB Nomor 20 Tahun 2021', 'SE Menteri PANRB Nomor 12 Tahun 2020', 'SE Menteri PANRB Nomor 5 Tahun 2022', 'SE Menteri PANRB Nomor 8 Tahun 2019', null, 'A', 'Dasar hukum peluncuran BerAKHLAK adalah SE Menteri PANRB Nomor 20 Tahun 2021 tentang Implementasi Core Values dan Employer Branding Aparatur Sipil Negara.', 'medium'),
('b0000000-0000-4000-8000-020300000000', 'Berdasarkan Tabel 1 keterkaitan Core Values ASN dan Nilai-Nilai Kementerian Keuangan pada Bab III, nilai ASN "Kompeten" selaras dengan Nilai Kemenkeu apa?', 'Integritas', 'Profesionalisme', 'Sinergi', 'Kesempurnaan', null, 'B', 'Tabel 1 pada Bab III memetakan nilai ASN "Kompeten" selaras dengan Nilai Kemenkeu "Profesionalisme".', 'medium'),
('b0000000-0000-4000-8000-020300000000', 'Employer branding ASN "#banggamelayanibangsa" merupakan pemutakhiran dari employer branding sebelumnya yang berbunyi apa?', '"ASN unggul, negeri maju"', '"Bekerja untuk negeri"', '"Melayani dengan sepenuh hati"', '"Satu ASN, satu bangsa"', null, 'C', 'Modul menyebutkan bahwa "#banggamelayanibangsa" adalah pemutakhiran dari employer branding sebelumnya, yaitu "melayani dengan sepenuh hati".', 'hard'),
('b0000000-0000-4000-8000-020400000000', 'Nilai Kemenkeu "Integritas" memiliki dua perilaku utama dan ditetapkan bersama empat nilai lainnya melalui Keputusan Menteri Keuangan Nomor berapa?', 'Melayani dengan berorientasi kepuasan pemangku kepentingan; serta bersikap proaktif -- ditetapkan melalui PMK Nomor 190/PMK.01/2018', 'Mempunyai keahlian dan pengetahuan luas; serta bekerja dengan hati -- ditetapkan melalui KMK Nomor 127/KMK.01/2013', 'Memiliki sangka baik, saling percaya, dan saling menghormati; serta menemukan solusi terbaik -- ditetapkan melalui KMK Nomor 429/KMK.01/2022', 'Bersikap jujur, tulus, dan dapat dipercaya; serta menjaga martabat dan tidak melakukan hal-hal tercela -- ditetapkan melalui KMK Nomor 312/KMK.01/2011', null, 'D', 'Dua perilaku utama Integritas adalah: (1) bersikap jujur, tulus, dan dapat dipercaya; (2) menjaga martabat dan tidak melakukan hal-hal tercela. Nilai-Nilai Kemenkeu (termasuk Integritas) ditetapkan melalui Keputusan Menteri Keuangan Nomor 312/KMK.01/2011.', 'easy'),
('b0000000-0000-4000-8000-020400000000', 'Nilai Kemenkeu "Profesionalisme" menekankan bekerja tuntas dan akurat atas dasar kompetensi terbaik. Salah satu perilaku utamanya adalah "bekerja dengan hati", yang dimaknai sebagai apa dalam modul ini?', 'Menyeimbangkan SOP dengan hati nurani/perasaan, mencintai pekerjaan bukan karena terpaksa atau sekadar dibayar', 'Bekerja hanya berdasarkan perasaan tanpa mengikuti SOP', 'Mengutamakan hubungan emosional dengan atasan di atas kompetensi', 'Bekerja lembur tanpa batas demi menyelesaikan tugas', null, 'A', 'Perilaku "bekerja dengan hati" dimaknai sebagai menyeimbangkan SOP dengan hati nurani/perasaan; mencintai pekerjaan, bukan bekerja karena terpaksa atau sekadar dibayar.', 'medium'),
('b0000000-0000-4000-8000-020400000000', 'Nilai Kemenkeu "Sinergi" memiliki makna membangun dan memastikan hubungan kerja sama internal yang produktif serta kemitraan yang harmonis dengan pemangku kepentingan. Apa perilaku utama pertama dari nilai Sinergi?', 'Bersikap jujur, tulus, dan dapat dipercaya', 'Memiliki sangka baik, saling percaya, dan saling menghormati', 'Melayani dengan berorientasi pada kepuasan pemangku kepentingan', 'Melakukan perbaikan terus menerus', null, 'B', 'Perilaku utama pertama Sinergi adalah memiliki sangka baik, saling percaya, dan saling menghormati; perilaku utama kedua adalah menemukan dan melaksanakan solusi terbaik.', 'medium'),
('b0000000-0000-4000-8000-020400000000', 'Nilai Kemenkeu "Pelayanan" (Service) dilaksanakan dengan empat prinsip utama. Manakah kombinasi berikut yang sesuai dengan makna nilai Pelayanan pada modul?', 'Tertutup, birokratis, hierarkis, dan kaku', 'Efisien, murah, cepat, dan formal', 'Sepenuh hati, transparan, cepat, akurat, dan aman', 'Kompetitif, individualis, cepat, dan fleksibel', null, 'C', 'Makna Pelayanan adalah memberikan layanan yang memenuhi kepuasan pemangku kepentingan, dilaksanakan dengan sepenuh hati, transparan, cepat, akurat, dan aman.', 'easy'),
('b0000000-0000-4000-8000-020400000000', 'Nilai Kemenkeu "Kesempurnaan" (Excellence) menegaskan bahwa kesempurnaan hakiki hanya milik Tuhan Yang Maha Kuasa. Apa implikasi dari hal tersebut bagi pegawai Kemenkeu menurut modul ini?', 'Pegawai tidak perlu berusaha karena kesempurnaan tidak mungkin dicapai manusia', 'Kesempurnaan hanya menjadi tanggung jawab pimpinan puncak organisasi', 'Pegawai cukup mengikuti prosedur tanpa perlu berinovasi', 'Manusia tidak akan pernah sempurna sehingga perlu usaha pengembangan diri tanpa batas melalui perbaikan terus-menerus dan inovasi', null, 'D', 'Karena kesempurnaan hakiki hanya milik Tuhan, manusia tidak akan pernah sempurna sehingga perlu usaha pengembangan diri tanpa batas, diwujudkan lewat dua perilaku utama: perbaikan terus-menerus dan pengembangan inovasi/kreativitas.', 'medium'),
('b0000000-0000-4000-8000-020500000000', 'Menurut rangkuman Bab V Penutup, mengapa Nilai Dasar ASN BerAKHLAK dan Nilai-Nilai Kementerian Keuangan dinyatakan saling mendukung, bukan bertentangan?', 'Karena punya konsep dasar yang sama: ASN/pegawai mengelola pribadi selaras tujuan pelaksanaan tugas', 'Karena keduanya diterbitkan pada tahun yang sama', 'Karena keduanya disusun oleh Kementerian PANRB', 'Karena keduanya hanya berlaku bagi pejabat struktural', null, 'A', 'Bab V menegaskan Nilai Dasar ASN dan Nilai-Nilai Kemenkeu saling mendukung karena konsep dasarnya sama, yaitu ASN/pegawai mengelola pribadi selaras dengan tujuan pelaksanaan tugas.', 'medium'),
('b0000000-0000-4000-8000-020500000000', 'Bab V Penutup menyebutkan bahwa Nilai Dasar ASN BerAKHLAK berperan sebagai apa bagi seluruh ASN?', 'Sekadar slogan tanpa dampak pada budaya kerja', 'Tonggak baru untuk membangun budaya ASN yang selaras harapan masyarakat', 'Pengganti total seluruh nilai organisasi kementerian/lembaga', 'Syarat administratif semata untuk kenaikan pangkat', null, 'B', 'Menurut Bab V, Nilai Dasar ASN BerAKHLAK adalah tonggak baru bagi seluruh ASN untuk membangun budaya ASN yang selaras dengan harapan masyarakat.', 'easy'),
('b0000000-0000-4000-8000-020500000000', 'Bab V Penutup merangkum kembali Nilai-Nilai Kementerian Keuangan ke dalam berapa materi utama?', '3 materi utama', '4 materi utama', '5 materi utama', '7 materi utama', null, 'C', 'Bab V merangkum Nilai-Nilai Kementerian Keuangan ke dalam 5 materi utama: Integritas, Profesionalisme, Sinergi, Pelayanan, dan Kesempurnaan.', 'easy'),
('b0000000-0000-4000-8000-020500000000', 'Dalam rangkuman Bab V, apa yang menjadi prasyarat kinerja organisasi melalui budaya organisasi terkait Nilai-Nilai Organisasi?', 'Lokasi kantor pusat organisasi', 'Besarnya anggaran operasional organisasi', 'Jumlah pegawai yang bersertifikasi', 'Kohesi individu-kelompok-organisasi', null, 'D', 'Bab V menyatakan bahwa kohesi individu-kelompok-organisasi adalah prasyarat kinerja organisasi melalui budaya organisasi.', 'hard'),
('b0000000-0000-4000-8000-020500000000', 'Manakah pernyataan berikut yang PALING TEPAT menggambarkan definisi "Nilai" sebagaimana dirangkum ulang pada Bab V Penutup?', 'Nilai adalah keyakinan tentang baik/buruk yang memengaruhi perilaku dalam bertindak', 'Nilai adalah dokumen resmi yang diterbitkan oleh Sekretariat Jenderal', 'Nilai adalah target kinerja tahunan yang harus dicapai pegawai', 'Nilai adalah struktur organisasi formal Kementerian Keuangan', null, 'A', 'Bab V merangkum definisi nilai sebagai keyakinan tentang baik/buruk yang memengaruhi perilaku dalam bertindak.', 'easy')
;
