-- =====================================================================
-- Bank soal APLIKATIF / STUDI KASUS — Modul Tata Aturan Kepegawaian (M3)
-- =====================================================================
-- Mengganti soal hafalan lama dengan soal studi kasus per bab, berpijak pada
-- materi/ringkasan modul: UU 20/2023 ASN (PNS/PPPK, jabatan), hak & kewajiban
-- ASN, kelembagaan Manajemen ASN (Presiden - PAN-RB), CPNS/BUP/JPT/pemberhentian
-- (PP 11/2017 stdd PP 17/2020), serta Sistem Merit, Karier & Disiplin Kemenkeu
-- (PMK 224/2020, PMK 38/2025, PP 94/2021, Keppres 56/1974).
-- File ini idempotent: menghapus dulu soal M3 yang ada, lalu memasukkan yang baru.
--
-- Aman untuk skema baru: attempts menyimpan salinan soal (jsonb), jadi riwayat
-- lama tidak terpengaruh; seen_questions ikut terhapus otomatis (cascade).

delete from questions where chapter_id in (
  'b0000000-0000-4000-8000-030100000000',
  'b0000000-0000-4000-8000-030200000000',
  'b0000000-0000-4000-8000-030300000000',
  'b0000000-0000-4000-8000-030400000000',
  'b0000000-0000-4000-8000-030500000000'
);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values

-- ===================== BAB I: PENGANTAR UU ASN, PNS/PPPK, JABATAN =====================
('b0000000-0000-4000-8000-030100000000',
 'Dalam sosialisasi, seorang pegawai menyatakan bahwa dasar hukum utama ASN saat ini masih UU Nomor 5 Tahun 2014. Koreksi yang tepat adalah...',
 'Keliru, karena UU Nomor 5 Tahun 2014 telah digantikan oleh UU Nomor 20 Tahun 2023 tentang ASN',
 'Benar, UU Nomor 5 Tahun 2014 masih menjadi dasar hukum utama ASN',
 'Keliru, karena dasar hukum ASN adalah UU Nomor 43 Tahun 1999',
 'Keliru, karena dasar hukum ASN adalah UU Nomor 8 Tahun 1974',
 null, 'A',
 'UU Nomor 20 Tahun 2023 tentang ASN menggantikan UU Nomor 5 Tahun 2014, sehingga rujukan utama ASN saat ini adalah UU Nomor 20 Tahun 2023.',
 'easy'),

('b0000000-0000-4000-8000-030100000000',
 'Sinta diangkat untuk mengisi kebutuhan pegawai berdasarkan perjanjian kerja untuk jangka waktu tertentu. Berdasarkan UU Nomor 20 Tahun 2023, status kepegawaian Sinta adalah...',
 'PNS, karena semua pegawai pemerintah berstatus PNS',
 'PPPK, karena diangkat berdasarkan perjanjian kerja untuk jangka waktu tertentu',
 'PNS, karena bekerja penuh waktu di instansi pemerintah',
 'Bukan Pegawai ASN',
 null, 'B',
 'PPPK diangkat berdasarkan perjanjian kerja untuk jangka waktu tertentu, sedangkan PNS diangkat secara tetap oleh Pejabat Pembina Kepegawaian (PPK).',
 'easy'),

('b0000000-0000-4000-8000-030100000000',
 'Seorang pegawai ingin memahami hierarki Jabatan Manajerial dari tingkat tertinggi ke tingkat dasar. Urutan yang benar adalah...',
 'Administrator - Pengawas - Pimpinan Tinggi',
 'Pengawas - Administrator - Pimpinan Tinggi',
 'Pimpinan Tinggi - Administrator - Pengawas',
 'Pimpinan Tinggi - Pengawas - Administrator',
 null, 'C',
 'Jabatan Manajerial terdiri atas Jabatan Pimpinan Tinggi (tertinggi), Jabatan Administrator (menengah), dan Jabatan Pengawas (dasar).',
 'medium'),

('b0000000-0000-4000-8000-030100000000',
 'Rudi, pemegang Jabatan Administrasi, menjalani tugas belajar penuh selama 9 (sembilan) bulan. Konsekuensi terhadap jabatannya adalah...',
 'Tidak ada konsekuensi apa pun terhadap jabatannya',
 'Gajinya dihentikan hingga tugas belajar selesai',
 'Langsung dipindahkan ke Jabatan Fungsional',
 'Diberhentikan dari Jabatan Administrasi karena tugas belajar lebih dari 6 (enam) bulan',
 null, 'D',
 'PNS diberhentikan dari Jabatan Administrasi apabila menjalani tugas belajar lebih dari 6 (enam) bulan; 9 bulan telah melampaui ambang tersebut.',
 'medium'),

('b0000000-0000-4000-8000-030100000000',
 'Dina menduduki Jabatan Fungsional kategori keterampilan. Jenjang yang mungkin ia tempati adalah...',
 'Penyelia, Mahir, Terampil, atau Pemula',
 'Ahli Utama, Ahli Madya, Ahli Muda, atau Ahli Pertama',
 'Utama, Madya, atau Pratama',
 'Eselon III, IV, atau V',
 null, 'A',
 'Jabatan Fungsional kategori keterampilan terdiri atas jenjang Penyelia, Mahir, Terampil, dan Pemula.',
 'medium'),

('b0000000-0000-4000-8000-030100000000',
 'Berbeda dengan kategori keterampilan, jenjang Jabatan Fungsional kategori keahlian terdiri atas...',
 'Penyelia, Mahir, Terampil, Pemula',
 'Ahli Utama, Ahli Madya, Ahli Muda, Ahli Pertama',
 'Pimpinan Tinggi, Administrator, Pengawas',
 'Utama, Madya, Muda, Pratama',
 null, 'B',
 'Jabatan Fungsional kategori keahlian terdiri atas jenjang Ahli Utama, Ahli Madya, Ahli Muda, dan Ahli Pertama.',
 'hard'),

('b0000000-0000-4000-8000-030100000000',
 'Manakah pernyataan yang PALING tepat tentang perbedaan pengangkatan PNS dan PPPK menurut UU Nomor 20 Tahun 2023?',
 'PNS dan PPPK sama-sama diangkat berdasarkan perjanjian kerja',
 'PNS diangkat untuk jangka waktu tertentu, sedangkan PPPK diangkat secara tetap',
 'PNS diangkat secara tetap oleh PPK, sedangkan PPPK berdasarkan perjanjian kerja untuk jangka waktu tertentu',
 'Keduanya diangkat oleh Presiden secara langsung tanpa PPK',
 null, 'C',
 'PNS diangkat sebagai pegawai tetap oleh PPK, sedangkan PPPK diangkat berdasarkan perjanjian kerja untuk jangka waktu tertentu sesuai kebutuhan instansi.',
 'medium'),

('b0000000-0000-4000-8000-030100000000',
 'Andi adalah ASN yang tugasnya berbasis keahlian/keterampilan tertentu dan tidak termasuk jabatan manajerial. Jenis jabatan yang ia duduki adalah...',
 'Jabatan Pimpinan Tinggi',
 'Jabatan Administrator',
 'Jabatan Pengawas',
 'Jabatan Fungsional',
 null, 'D',
 'Jabatan yang menekankan keahlian/keterampilan tertentu dan berada di luar jabatan manajerial adalah Jabatan Fungsional.',
 'medium'),

-- ===================== BAB II: HAK & KEWAJIBAN ASN =====================
('b0000000-0000-4000-8000-030200000000',
 'Dalam diskusi tentang hak Pegawai ASN, seorang pegawai menyebut empat hal berikut. Manakah yang sebenarnya BUKAN termasuk 7 (tujuh) hak Pegawai ASN?',
 'Jaminan sosial',
 'Bantuan hukum',
 'Cuti di luar tanggungan negara',
 'Pengembangan diri',
 null, 'C',
 'Tujuh hak Pegawai ASN: penghasilan, penghargaan yang bersifat motivasi, tunjangan dan fasilitas, jaminan sosial, lingkungan kerja, pengembangan diri, dan bantuan hukum. Cuti di luar tanggungan negara adalah jenis cuti, bukan bagian dari 7 hak tersebut.',
 'medium'),

('b0000000-0000-4000-8000-030200000000',
 'Bayu menolak dimutasi ke provinsi lain semata karena alasan pribadi tanpa dasar yang sah. Sikap ini bertentangan dengan kewajiban ASN, yaitu...',
 'Bersedia ditempatkan di seluruh wilayah NKRI dan di perwakilan NKRI di luar negeri',
 'Menjaga netralitas dari politik praktis',
 'Menyimpan rahasia jabatan dan negara',
 'Mengembangkan kompetensi diri',
 null, 'A',
 'Salah satu kewajiban ASN adalah bersedia ditempatkan di seluruh wilayah NKRI dan di perwakilan NKRI di luar negeri.',
 'medium'),

('b0000000-0000-4000-8000-030200000000',
 'Menjelang pemilu, seorang ASN diajak menjadi juru kampanye partai dan mengarahkan rekan-rekannya memilih calon tertentu. Berdasarkan kewajiban ASN, ia seharusnya...',
 'Menerima, karena itu murni hak politik pribadi',
 'Menolak, karena ASN wajib menjaga netralitas dan bebas dari pengaruh serta intervensi partai politik',
 'Menerima, asalkan dilakukan di luar jam kerja',
 'Menolak secara terbuka, tetapi boleh mengarahkan pilihan rekan secara diam-diam',
 null, 'B',
 'ASN wajib menjaga netralitas dan bebas dari pengaruh/intervensi golongan dan partai politik; keterlibatan dalam politik praktis dilarang.',
 'medium'),

('b0000000-0000-4000-8000-030200000000',
 'Seorang ASN menghadapi tuntutan hukum yang berkaitan dengan pelaksanaan tugas kedinasannya. Sesuai 7 hak Pegawai ASN, ia berhak memperoleh...',
 'Penghasilan tambahan secara otomatis',
 'Cuti besar khusus',
 'Bantuan hukum',
 'Kenaikan pangkat istimewa',
 null, 'C',
 'Bantuan hukum merupakan salah satu dari 7 hak Pegawai ASN, diberikan terkait pelaksanaan tugas kedinasan.',
 'medium'),

('b0000000-0000-4000-8000-030200000000',
 'Kantor memfasilitasi pelatihan dan kesempatan meningkatkan kompetensi bagi pegawai. Fasilitas ini merupakan pemenuhan hak ASN berupa...',
 'Jaminan sosial',
 'Bantuan hukum',
 'Penghargaan yang bersifat motivasi',
 'Pengembangan diri',
 null, 'D',
 'Pengembangan diri (pengembangan kompetensi) adalah salah satu dari 7 hak Pegawai ASN.',
 'easy'),

('b0000000-0000-4000-8000-030200000000',
 'Manakah tindakan yang PALING mencerminkan kewajiban ASN untuk setia dan taat kepada Pancasila, UUD 1945, NKRI, dan pemerintah yang sah?',
 'Menolak ajakan menyebarkan paham yang bertentangan dengan Pancasila dan melaporkannya',
 'Mengikuti setiap ajakan sepanjang menguntungkan diri sendiri',
 'Bersikap masa bodoh terhadap ancaman ideologi demi menjaga netralitas',
 'Menyerahkan seluruh urusan ideologi hanya kepada aparat keamanan',
 null, 'A',
 'Kesetiaan pada Pancasila, UUD 1945, NKRI, dan pemerintah yang sah diwujudkan antara lain dengan menolak dan melaporkan ajakan yang bertentangan dengan Pancasila.',
 'medium'),

('b0000000-0000-4000-8000-030200000000',
 'Seorang ASN mengalami kecelakaan kerja dan memerlukan perlindungan berupa jaminan kesehatan dan kecelakaan kerja. Hak Pegawai ASN yang paling relevan adalah...',
 'Pengembangan diri',
 'Jaminan sosial',
 'Bantuan hukum',
 'Penghargaan yang bersifat motivasi',
 null, 'B',
 'Jaminan sosial mencakup perlindungan seperti jaminan kesehatan dan jaminan kecelakaan kerja bagi Pegawai ASN.',
 'easy'),

('b0000000-0000-4000-8000-030200000000',
 'Seorang ASN diminta menjalankan kebijakan resmi pimpinan yang sah dan sesuai aturan, tetapi ia mengabaikannya tanpa alasan yang sah. Ia melanggar kewajiban ASN berupa...',
 'Menjaga netralitas',
 'Menyimpan rahasia jabatan',
 'Menaati peraturan perundang-undangan dan melaksanakan tugas kedinasan dengan penuh tanggung jawab',
 'Bersedia ditempatkan di seluruh wilayah NKRI',
 null, 'C',
 'ASN wajib menaati ketentuan peraturan perundang-undangan dan melaksanakan tugas kedinasan dengan penuh pengabdian, kejujuran, kesadaran, dan tanggung jawab.',
 'medium'),

-- ===================== BAB III: KELEMBAGAAN MANAJEMEN ASN =====================
('b0000000-0000-4000-8000-030300000000',
 'Dalam struktur Manajemen ASN nasional, pemegang kekuasaan pemerintahan tertinggi atas kebijakan, pembinaan profesi, dan Manajemen ASN adalah...',
 'Menteri PAN-RB',
 'Kepala BKN',
 'Ketua KASN',
 'Presiden',
 null, 'D',
 'Presiden adalah pemegang kekuasaan pemerintahan tertinggi dalam kebijakan, pembinaan profesi, dan Manajemen ASN.',
 'easy'),

('b0000000-0000-4000-8000-030300000000',
 'Kewenangan Presiden atas kebijakan dan Manajemen ASN sehari-hari secara nasional didelegasikan kepada...',
 'Kementerian PAN-RB',
 'Kementerian Dalam Negeri',
 'Badan Kepegawaian Negara',
 'Sekretariat Kabinet',
 null, 'A',
 'Presiden mendelegasikan kewenangan atas kebijakan, pembinaan profesi, dan Manajemen ASN kepada Kementerian PAN-RB.',
 'easy'),

('b0000000-0000-4000-8000-030300000000',
 'Sebuah unit ingin mengetahui lembaga yang bertugas mengawasi penerapan Sistem Merit pada Kementerian/Lembaga. Jawaban yang tepat adalah...',
 'Lembaga Administrasi Negara',
 'Kementerian PAN-RB',
 'Sekretariat Kabinet',
 'Mahkamah Agung',
 null, 'B',
 'Salah satu tugas Kementerian PAN-RB adalah melakukan pengawasan penerapan Sistem Merit pada Kementerian/Lembaga.',
 'medium'),

('b0000000-0000-4000-8000-030300000000',
 'Manakah yang BUKAN termasuk pendelegasian kewenangan Presiden kepada Kementerian PAN-RB dalam Manajemen ASN?',
 'Perumusan dan penetapan kebijakan strategis',
 'Koordinasi dan sinkronisasi kebijakan',
 'Menetapkan putusan pengadilan tata usaha negara atas sengketa kepegawaian',
 'Pengendalian kebijakan Manajemen ASN secara nasional',
 null, 'C',
 'Pendelegasian meliputi perumusan/penetapan kebijakan strategis, koordinasi dan sinkronisasi, serta pengendalian kebijakan Manajemen ASN nasional. Menetapkan putusan pengadilan bukan kewenangan yang didelegasikan.',
 'medium'),

('b0000000-0000-4000-8000-030300000000',
 'Dalam mengisi sebuah jabatan, seorang pejabat memilih calon berdasarkan kedekatan pribadi, bukan kualifikasi dan kompetensi. Prinsip yang dilanggar adalah...',
 'Prinsip senioritas mutlak',
 'Prinsip pemerataan daerah asal',
 'Prinsip loyalitas pada atasan',
 'Sistem Merit — berdasarkan kualifikasi, kompetensi, dan kinerja tanpa membedakan latar belakang',
 null, 'D',
 'Sistem Merit menuntut kebijakan dan Manajemen ASN berdasarkan kualifikasi, kompetensi, dan kinerja secara adil dan wajar tanpa membedakan latar belakang (politik, ras, agama, gender, dan sebagainya).',
 'medium'),

('b0000000-0000-4000-8000-030300000000',
 'Pengembangan karier PNS menurut UU Nomor 20 Tahun 2023 didasarkan pada...',
 'Kualifikasi, kompetensi, penilaian kinerja, dan kebutuhan instansi (Sistem Merit)',
 'Semata-mata masa kerja dan usia pegawai',
 'Kedekatan pegawai dengan pimpinan',
 'Hasil undian jabatan yang tersedia',
 null, 'A',
 'Pengembangan karier PNS didasarkan pada kualifikasi, kompetensi, penilaian kinerja, dan kebutuhan instansi melalui manajemen talenta berbasis Sistem Merit.',
 'medium'),

-- ===================== BAB IV: CPNS, BUP, JPT, PEJABAT NEGARA, PEMBERHENTIAN =====================
('b0000000-0000-4000-8000-030400000000',
 'Sari baru lulus seleksi CPNS. Sebelum diangkat menjadi PNS, ia harus menjalani masa percobaan selama...',
 '6 (enam) bulan',
 '1 (satu) tahun',
 '2 (dua) tahun',
 '3 (tiga) tahun',
 null, 'B',
 'Masa percobaan CPNS adalah 1 (satu) tahun, dilaksanakan melalui pendidikan dan pelatihan terintegrasi.',
 'easy'),

('b0000000-0000-4000-8000-030400000000',
 'Pak Hadi adalah seorang Pejabat Administrasi. Batas Usia Pensiun (BUP) yang berlaku baginya adalah...',
 '65 tahun',
 '60 tahun',
 '58 tahun',
 '56 tahun',
 null, 'C',
 'BUP 58 tahun berlaku bagi Pejabat Administrasi, Pejabat Fungsional Ahli Muda, Ahli Pertama, dan Pejabat Fungsional Keterampilan.',
 'medium'),

('b0000000-0000-4000-8000-030400000000',
 'Bu Rina menduduki Jabatan Pimpinan Tinggi. Batas Usia Pensiun (BUP) yang berlaku baginya adalah...',
 '56 tahun',
 '58 tahun',
 '65 tahun',
 '60 tahun',
 null, 'D',
 'BUP 60 tahun berlaku bagi pejabat yang menduduki Jabatan Pimpinan Tinggi dan Pejabat Fungsional Ahli Madya.',
 'medium'),

('b0000000-0000-4000-8000-030400000000',
 'Seorang Pejabat Fungsional Ahli Utama akan mencapai Batas Usia Pensiun (BUP) pada usia...',
 '65 tahun',
 '60 tahun',
 '58 tahun',
 '70 tahun',
 null, 'A',
 'BUP 65 tahun berlaku bagi Pejabat Fungsional Ahli Utama.',
 'medium'),

('b0000000-0000-4000-8000-030400000000',
 'Untuk mengisi JPT Madya di sebuah Instansi Pusat, panitia seleksi mengusulkan 3 (tiga) nama calon per lowongan melalui PPK. Pihak yang memilih 1 (satu) nama akhir adalah...',
 'PPK secara langsung',
 'Presiden',
 'Menteri PAN-RB',
 'Kepala BKN',
 null, 'B',
 'Untuk JPT Utama/Madya di Instansi Pusat, tiga nama calon yang diusulkan PPK disampaikan kepada Presiden, dan Presiden memilih 1 (satu) nama.',
 'medium'),

('b0000000-0000-4000-8000-030400000000',
 'Masa jabatan bagi Jabatan Pimpinan Tinggi (JPT) menurut ketentuan paling lama adalah...',
 '3 (tiga) tahun',
 '4 (empat) tahun',
 '5 (lima) tahun',
 '10 (sepuluh) tahun',
 null, 'C',
 'Masa jabatan JPT paling lama 5 (lima) tahun, dapat diperpanjang berdasarkan kinerja, kompetensi, dan kebutuhan instansi sesuai ketentuan.',
 'medium'),

('b0000000-0000-4000-8000-030400000000',
 'Seorang PNS diangkat menjadi Menteri. Berdasarkan Pasal 58 UU Nomor 20 Tahun 2023, status kepegawaiannya adalah...',
 'Diberhentikan tidak dengan hormat sebagai PNS',
 'Otomatis pensiun dini',
 'Tetap menjabat sebagai PNS dan Menteri sekaligus tanpa perubahan status',
 'Diberhentikan sementara dari jabatan ASN-nya, tetapi tidak kehilangan status PNS',
 null, 'D',
 'PNS yang diangkat menjadi pejabat negara (seperti Menteri) diberhentikan sementara dari jabatan ASN-nya, tetapi tidak kehilangan status PNS, dan diaktifkan kembali setelah tidak lagi menjabat.',
 'hard'),

('b0000000-0000-4000-8000-030400000000',
 'Seorang PNS meninggal dunia ketika masih aktif bertugas. Jenis pemberhentian yang berlaku baginya adalah...',
 'Diberhentikan dengan hormat',
 'Diberhentikan tidak dengan hormat',
 'Diberhentikan sementara',
 'Tidak diberhentikan',
 null, 'A',
 'PNS yang meninggal dunia, tewas, atau hilang termasuk kategori diberhentikan dengan hormat.',
 'easy'),

('b0000000-0000-4000-8000-030400000000',
 'Seorang PNS terbukti menggunakan ijazah palsu saat pengangkatan dan dihukum atas tindak pidana jabatan. Jenis pemberhentian yang tepat adalah...',
 'Diberhentikan dengan hormat',
 'Diberhentikan tidak dengan hormat',
 'Diberhentikan sementara lalu langsung diaktifkan',
 'Cukup dikenai hukuman disiplin ringan',
 null, 'B',
 'Penggunaan ijazah palsu dan pidana jabatan/kejahatan tertentu termasuk alasan pemberhentian tidak dengan hormat sebagai PNS.',
 'medium'),

('b0000000-0000-4000-8000-030400000000',
 'Seorang PNS telah menyelesaikan tugas belajar, tetapi tidak melapor kepada PPK dalam 15 (lima belas) hari kerja sejak tugas belajar berakhir. Konsekuensinya, ia dapat...',
 'Diberi penghargaan khusus',
 'Dinaikkan pangkatnya secara istimewa',
 'Diberhentikan karena tidak melapor dalam 15 (lima belas) hari kerja sejak berakhirnya tugas belajar',
 'Diberi cuti tambahan sebagai kompensasi',
 null, 'C',
 'Tidak melapor kepada PPK dalam 15 (lima belas) hari kerja sejak berakhirnya tugas belajar termasuk alasan pemberhentian PNS.',
 'hard'),

-- ===================== BAB V: SISTEM MERIT, KARIER & DISIPLIN KEMENKEU =====================
('b0000000-0000-4000-8000-030500000000',
 'Sejak momentum apa Kementerian Keuangan mulai menerapkan sistem merit secara menyeluruh?',
 'Sejak pandemi tahun 2020',
 'Sejak berlakunya UU ASN tahun 2014',
 'Sejak awal berdirinya Kementerian Keuangan',
 'Sejak reformasi birokrasi tahun 2007',
 null, 'D',
 'Kemenkeu sejak reformasi birokrasi tahun 2007 telah menerapkan sistem merit (rekrutmen objektif, pengukuran kompetensi, manajemen kinerja, peringkat jabatan, talent management, dan remunerasi berbasis peringkat jabatan dan kinerja).',
 'easy'),

('b0000000-0000-4000-8000-030500000000',
 'Seorang PNS Kemenkeu tidak masuk kerja tanpa alasan sah secara kumulatif 15 (lima belas) hari dalam satu tahun. Sesuai ambang pelanggaran jam kerja (PP 94/2021), hukuman disiplinnya adalah...',
 'Sedang — pemotongan tunjangan kinerja 25% selama 9 bulan',
 'Ringan — teguran lisan',
 'Berat — penurunan jabatan setingkat lebih rendah',
 'Berat — pemberhentian dengan hormat tidak atas permintaan sendiri',
 null, 'A',
 'Tidak masuk kerja 14-16 hari kumulatif dikenai hukuman disiplin sedang berupa pemotongan tunjangan kinerja 25% selama 9 bulan.',
 'hard'),

('b0000000-0000-4000-8000-030500000000',
 'PNS lain hanya tidak masuk kerja tanpa alasan sah 5 (lima) hari kumulatif dalam satu tahun. Hukuman disiplin yang sesuai adalah...',
 'Sedang — pemotongan tunjangan kinerja 25% selama 6 bulan',
 'Ringan — teguran lisan',
 'Berat — pembebasan dari jabatan menjadi jabatan pelaksana',
 'Tidak ada hukuman apa pun',
 null, 'B',
 'Tidak masuk kerja pada rentang 4-10 hari kumulatif dikenai hukuman disiplin ringan; 5 hari termasuk kategori teguran lisan.',
 'medium'),

('b0000000-0000-4000-8000-030500000000',
 'Seorang PNS tercatat tidak masuk kerja tanpa alasan sah 22 (dua puluh dua) hari kumulatif dalam satu tahun. Hukuman disiplin yang dijatuhkan tergolong...',
 'Ringan — teguran tertulis',
 'Sedang — pemotongan tunjangan kinerja 25% selama 12 bulan',
 'Berat — penurunan jabatan setingkat lebih rendah selama 12 bulan',
 'Tidak ada hukuman karena masih di bawah ambang',
 null, 'C',
 'Tidak masuk kerja 21-24 hari kumulatif dikenai hukuman disiplin berat berupa penurunan jabatan setingkat lebih rendah selama 12 bulan.',
 'hard'),

('b0000000-0000-4000-8000-030500000000',
 'Dalam tahapan pola karier Kemenkeu (PMK 224/PMK.01/2020), setelah CPNS diangkat menjadi PNS, ia menjalani masa branding selama...',
 '6 (enam) bulan',
 '1 (satu) tahun',
 '3 (tiga) tahun',
 '2 (dua) tahun',
 null, 'D',
 'Masa branding berlangsung 2 (dua) tahun setelah CPNS diangkat menjadi PNS, mencakup penguatan nilai Kemenkeu, kode etik, disiplin, pembekalan teknis jabatan, dan rencana pengembangan karier individu.',
 'medium'),

('b0000000-0000-4000-8000-030500000000',
 'Manajemen Talenta di Lingkungan Kementerian Keuangan saat ini diatur oleh peraturan yang mencabut PMK Nomor 60/PMK.01/2016, yaitu...',
 'PMK Nomor 38 Tahun 2025',
 'PMK Nomor 224/PMK.01/2020',
 'PMK Nomor 216/PMK.01/2018',
 'PMK Nomor 190/PMK.01/2018',
 null, 'A',
 'PMK Nomor 38 Tahun 2025 tentang Manajemen Talenta di Lingkungan Kemenkeu mencabut PMK Nomor 60/PMK.01/2016 (stdd PMK Nomor 161/PMK.01/2017).',
 'medium'),

('b0000000-0000-4000-8000-030500000000',
 'Berdasarkan Keppres Nomor 56 Tahun 1974, besar iuran wajib PNS untuk dana pensiun serta tabungan hari tua dan perumahan adalah...',
 '7,5% (5% dana pensiun, 2,5% THT)',
 '10% (4,75% dana pensiun; 3,25% tabungan hari tua dan perumahan)',
 '5% (4% dana pensiun, 1% THT)',
 '12% (8% dana pensiun, 4% THT)',
 null, 'B',
 'Keppres Nomor 56 Tahun 1974 menetapkan iuran wajib PNS sebesar 10% dari penghasilan: 4,75% untuk dana pensiun dan 3,25% untuk tabungan hari tua dan perumahan.',
 'hard'),

('b0000000-0000-4000-8000-030500000000',
 'Seorang PNS sakit lebih dari 14 (empat belas) hari dan mengajukan cuti sakit. Syarat yang harus dipenuhi adalah...',
 'Cukup memberi tahu atasan secara lisan',
 'Melampirkan surat keterangan sakit yang dibuat sendiri',
 'Mengajukan permintaan tertulis dilampiri surat keterangan dokter pemerintah',
 'Tidak perlu dokumen apa pun',
 null, 'C',
 'Untuk cuti sakit lebih dari 14 hari, PNS mengajukan permintaan tertulis yang dilampiri surat keterangan dokter pemerintah; cuti sakit diberikan paling lama 1 tahun dan dapat ditambah 6 bulan.',
 'medium')
;
