-- =====================================================================
-- Bank soal APLIKATIF / STUDI KASUS — Modul Etika PNS (M1)
-- =====================================================================
-- Mengganti sebagian soal hafalan lama dengan soal studi kasus per bab.
-- File ini idempotent: menghapus dulu soal Etika PNS yang ada, lalu memasukkan
-- kumpulan baru (mayoritas studi kasus + beberapa cek konsep inti).
-- Semua soal berpijak pada materi/ringkasan modul (Sonny Keraf, UU 20/2023,
-- PP 42/2004, PMK 190/PMK.01/2018, KMK 416/KMK.01/2023, dll).
--
-- Aman untuk skema baru: attempts menyimpan salinan soal (jsonb), jadi riwayat
-- lama tidak terpengaruh; seen_questions ikut terhapus otomatis (cascade).

delete from questions where chapter_id in (
  'b0000000-0000-4000-8000-010100000000',
  'b0000000-0000-4000-8000-010200000000',
  'b0000000-0000-4000-8000-010300000000',
  'b0000000-0000-4000-8000-010400000000',
  'b0000000-0000-4000-8000-010500000000',
  'b0000000-0000-4000-8000-010600000000',
  'b0000000-0000-4000-8000-010700000000',
  'b0000000-0000-4000-8000-010800000000',
  'b0000000-0000-4000-8000-010900000000',
  'b0000000-0000-4000-8000-011000000000'
);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values

-- ===================== BAB A: PENGANTAR =====================
('b0000000-0000-4000-8000-010100000000',
 'Rina, seorang pegawai, selalu menyelesaikan target pekerjaan paling cepat di unitnya. Namun ia kerap melewati prosedur, menekan rekan, dan mengabaikan kepatutan demi angka capaian. Berdasarkan pesan Bab Pengantar modul, penilaian yang paling tepat atas cara kerja Rina adalah...',
 'Sudah benar, karena PNS yang baik cukup diukur dari efektivitas dan efisiensi',
 'Belum cukup, karena PNS dituntut juga menjunjung nilai moral, hukum, dan kepatutan sebagai landasan perilaku',
 'Sudah benar, karena hasil kerja lebih penting daripada cara mencapainya',
 'Belum cukup, karena seharusnya ia bekerja lebih lambat agar tidak menonjol',
 null, 'B',
 'Bab Pengantar menegaskan PNS dituntut tidak hanya bekerja efektif dan efisien, tetapi juga menjunjung tinggi nilai moral, hukum, dan kepatutan. Cara mencapai hasil tetap harus etis.',
 'medium'),

('b0000000-0000-4000-8000-010100000000',
 'Modul menempatkan etika sebagai fondasi utama yang membentuk tiga hal pada diri PNS. Ketiga hal tersebut adalah...',
 'Karakter, integritas, dan profesionalisme',
 'Pangkat, senioritas, dan jabatan',
 'Popularitas, jaringan, dan pengaruh',
 'Kekayaan, status, dan kekuasaan',
 null, 'A',
 'Etika adalah fondasi pembentuk karakter, integritas, dan profesionalisme individu, terutama PNS sebagai pelayan publik dan pengelola keuangan negara.',
 'easy'),

('b0000000-0000-4000-8000-010100000000',
 'Dalam Bab Pengantar, PNS digambarkan memegang amanah ganda. Amanah ganda tersebut adalah sebagai...',
 'Penegak hukum tunggal sekaligus hakim',
 'Pengusaha sekaligus investor negara',
 'Pelayan publik sekaligus pengelola keuangan negara',
 'Diplomat sekaligus juru bicara pemerintah',
 null, 'C',
 'PNS memegang amanah sebagai pelayan publik sekaligus pengelola keuangan negara, sehingga etika menjadi landasan penting perilakunya.',
 'easy'),

-- ===================== BAB B: PRINSIP-PRINSIP MORAL PNS (Sonny Keraf) =====================
('b0000000-0000-4000-8000-010200000000',
 'Di loket pelayanan, Doni mendahulukan seorang kerabat yang baru datang, padahal ada pemohon lain yang sudah antre lebih dulu sejak pagi. Prinsip moral PNS (Sonny Keraf) yang paling dilanggar Doni adalah...',
 'Bertindak secara adil',
 'Profesionalisme',
 'Integritas moral yang tinggi',
 'Tanggung jawab terhadap kepentingan publik',
 null, 'A',
 'Prinsip Bertindak Adil menuntut perlakuan sama tanpa diskriminasi dengan asas yang datang pertama dilayani pertama. Mendahulukan kerabat melanggar prinsip ini.',
 'medium'),

('b0000000-0000-4000-8000-010200000000',
 'Seorang pengusaha menekan Sari agar hasil pemeriksaannya diringankan, dengan iming-iming imbalan. Sari menolak dan tetap bekerja sesuai fakta agar tidak dikendalikan pihak lain untuk menyalahgunakan wewenang. Sikap Sari paling mencerminkan prinsip...',
 'Bertindak adil',
 'Integritas moral yang tinggi',
 'Jangan lakukan pada orang lain apa yang tidak ingin dilakukan pada diri sendiri',
 'Profesionalisme',
 null, 'B',
 'Integritas Moral yang Tinggi berarti bertindak sesuai prinsip, menjaga nama baik, dan tidak dikendalikan pihak lain untuk menyalahgunakan kekuasaan atau wewenang yang merugikan kepentingan publik.',
 'medium'),

('b0000000-0000-4000-8000-010200000000',
 'Demi mempercepat sebuah program yang dianggap baik, seorang pejabat mengusulkan memanipulasi data dukung agar lolos, dengan alasan "yang penting tujuannya mulia". Prinsip moral PNS yang menolak cara berpikir ini adalah...',
 'Bertindak adil',
 'Berpihak kepada kebenaran dan kejujuran',
 'Jangan menghalalkan segala cara untuk mencapai tujuan',
 'Tanggung jawab terhadap kepentingan publik',
 null, 'C',
 'Prinsip Jangan Menghalalkan Segala Cara menolak manipulasi yang merugikan kepentingan publik; pencapaian tujuan harus tetap sesuai sistem dan prosedur yang berlaku.',
 'hard'),

('b0000000-0000-4000-8000-010200000000',
 'Budi selalu melayani pemohon tanpa mempersulit, karena ia membayangkan tidak ingin dipersulit bila berada di posisi mereka. Sikap Budi paling sesuai dengan prinsip moral...',
 'Bertindak adil',
 'Profesionalisme',
 'Jangan lakukan pada orang lain apa yang Anda sendiri tidak mau hal itu dilakukan pada Anda',
 'Integritas moral yang tinggi',
 null, 'C',
 'Prinsip ketujuh Sonny Keraf: jangan mempersulit atau meminta sesuatu dalam pelayanan publik, karena kita pun tidak ingin diperlakukan demikian.',
 'medium'),

('b0000000-0000-4000-8000-010200000000',
 'Seorang pegawai ditawari jabatan dan sejumlah uang agar mau memuluskan kepentingan kelompok tertentu yang merugikan masyarakat. Ia menolak karena meyakini kepentingan publik tidak dapat digantikan uang atau jabatan. Prinsip yang ia pegang adalah...',
 'Tanggung jawab terhadap kepentingan publik',
 'Bertindak adil',
 'Profesionalisme',
 'Berpihak kepada kebenaran dan kejujuran',
 null, 'A',
 'Prinsip Tanggung Jawab terhadap Kepentingan Publik menempatkan kepentingan publik sebagai nilai tertinggi yang tidak tergantikan uang atau jabatan; profesi PNS adalah panggilan mengabdi.',
 'medium'),

-- ===================== BAB C: PENGERTIAN ETIKA =====================
('b0000000-0000-4000-8000-010300000000',
 'Secara etimologi, kata "etika" berasal dari bahasa Yunani kuno "ethos" yang berarti...',
 'Aturan tertulis yang ditetapkan penguasa',
 'Adat istiadat atau kebiasaan hidup yang dianggap baik oleh masyarakat',
 'Hukuman bagi pelanggar norma',
 'Ilmu tentang hitungan dan pengukuran',
 null, 'B',
 'Secara etimologi, etika berasal dari kata Yunani ethos yang berarti adat istiadat atau kebiasaan hidup yang dianggap baik oleh suatu masyarakat.',
 'easy'),

('b0000000-0000-4000-8000-010300000000',
 'Seorang pegawai melakukan perbuatan yang secara aturan tidak dilarang, namun dinilai tidak pantas dan melanggar kepatutan di mata masyarakat. Kasus ini menunjukkan bahwa etika berfungsi sebagai...',
 'Sekumpulan sanksi pidana bagi pegawai',
 'Sistem nilai dan norma moral yang menjadi pegangan dalam mengatur tingkah laku',
 'Standar penilaian fisik pegawai',
 'Syarat administratif kenaikan pangkat',
 null, 'B',
 'Menurut KBBI, etika adalah sistem nilai dan norma moral yang menjadi pegangan seseorang atau kelompok dalam mengatur tingkah laku. Kepatutan dinilai secara moral, tidak selalu identik dengan aturan tertulis.',
 'medium'),

('b0000000-0000-4000-8000-010300000000',
 'Etika berkaitan erat dengan istilah "moral". Kata moral berasal dari bahasa Latin "mos" (jamak: mores) yang maknanya...',
 'Adat kebiasaan atau cara hidup melakukan perbuatan baik',
 'Perintah resmi dari atasan',
 'Ilmu tentang tata negara',
 'Perjanjian antarlembaga',
 null, 'A',
 'Moral berasal dari bahasa Latin mos (jamak mores) yang berarti adat kebiasaan atau cara hidup untuk melakukan perbuatan baik dan menghindari keburukan; etika dan moral berpengertian kurang lebih sama.',
 'easy'),

-- ===================== BAB D: KODE ETIK PNS =====================
('b0000000-0000-4000-8000-010400000000',
 'Ari menggunakan kendaraan dinas dan printer kantor untuk keperluan usaha sampingannya di akhir pekan. Berdasarkan nilai dasar ASN, perbuatan Ari paling bertentangan dengan nilai...',
 'Harmonis',
 'Akuntabel',
 'Adaptif',
 'Kolaboratif',
 null, 'B',
 'Nilai Akuntabel menuntut penggunaan kekayaan dan barang milik negara secara bertanggung jawab, efektif, dan efisien, serta tidak menyalahgunakan kewenangan jabatan. Memakai aset negara untuk kepentingan pribadi melanggar nilai ini.',
 'medium'),

('b0000000-0000-4000-8000-010400000000',
 'Dina memperoleh data rahasia jabatan. Seorang kenalan memintanya membocorkan data itu. Dina menolak dan menjaga kerahasiaannya demi menjaga nama baik instansi dan negara. Sikap Dina mencerminkan nilai dasar ASN...',
 'Kompeten',
 'Loyal',
 'Adaptif',
 'Berorientasi pelayanan',
 null, 'B',
 'Nilai Loyal mencakup menjaga nama baik ASN, instansi, dan negara, serta menjaga rahasia jabatan dan negara. Menolak membocorkan data rahasia adalah wujud nilai Loyal.',
 'medium'),

('b0000000-0000-4000-8000-010400000000',
 'Dalam suatu perkara, seorang PNS diminta memberikan keterangan. Ia menolak memberikan kesaksian palsu meskipun ditekan. Perbuatan ini paling tepat dikaitkan dengan etika PNS dalam ranah...',
 'Etika dalam bernegara',
 'Etika terhadap diri sendiri',
 'Etika terhadap sesama PNS',
 'Etika dalam bermasyarakat',
 null, 'A',
 'Menurut Pasal 7 PP No. 42 Tahun 2004, salah satu butir Etika dalam Bernegara adalah tidak memberikan kesaksian palsu atau keterangan yang tidak benar.',
 'hard'),

('b0000000-0000-4000-8000-010400000000',
 'Kode etik dan kode perilaku ASN diatur dalam UU Nomor 20 Tahun 2023 tentang ASN. Menurut Pasal 4 ayat (1), tujuan kode etik dan kode perilaku adalah menjaga...',
 'Kenaikan pangkat otomatis setiap pegawai',
 'Martabat dan kehormatan ASN serta kepentingan bangsa dan negara',
 'Besaran tunjangan kinerja pegawai',
 'Jumlah formasi penerimaan pegawai',
 null, 'B',
 'Pasal 4 ayat (1) UU No. 20 Tahun 2023 menyatakan kode etik dan kode perilaku bertujuan menjaga martabat dan kehormatan ASN serta kepentingan bangsa dan negara.',
 'medium'),

('b0000000-0000-4000-8000-010400000000',
 'Pedoman sikap, tingkah laku, dan perbuatan PNS dalam tugas dan pergaulan hidup sehari-hari, yang wajib dilaksanakan PNS di seluruh Indonesia, diatur dalam...',
 'PP No. 42 Tahun 2004 tentang Pembinaan Jiwa Korps dan Kode Etik PNS',
 'UU No. 17 Tahun 2003 tentang Keuangan Negara',
 'PP No. 94 Tahun 2021 tentang Disiplin PNS',
 'PMK No. 190/PMK.01/2018',
 null, 'A',
 'Pasal 1 ayat (2) PP No. 42 Tahun 2004 mendefinisikan Kode Etik PNS sebagai pedoman sikap, tingkah laku, dan perbuatan PNS dalam tugas dan pergaulan hidup sehari-hari.',
 'medium'),

-- ===================== BAB E: KODE ETIK INSTANSI DAN KODE ETIK PROFESI =====================
('b0000000-0000-4000-8000-010500000000',
 'Sebuah organisasi profesi menyusun kode etik yang bagus di atas kertas, tetapi tidak ada pengawasan pelaksanaan dan tidak ada evaluasi atas pelanggaran. Berdasarkan modul, kondisi ini gagal memenuhi syarat mutlak kode etik karena...',
 'Kode etik seharusnya dibuat oleh pemerintah pusat, bukan profesi',
 'Kode etik harus diawasi terus-menerus dan setiap pelanggaran dievaluasi serta dikenakan tindakan',
 'Kode etik cukup berisi kewajiban tanpa larangan',
 'Kode etik tidak boleh memuat sanksi apa pun',
 null, 'B',
 'Dua syarat mutlak agar kode etik berfungsi: (1) dibuat oleh masing-masing profesi, dan (2) pelaksanaannya diawasi terus-menerus, setiap pelanggaran dievaluasi dan dikenakan tindakan oleh komite khusus.',
 'medium'),

('b0000000-0000-4000-8000-010500000000',
 'Berdasarkan PP No. 42 Tahun 2004, penetapan kode etik instansi menjadi kewenangan...',
 'Organisasi profesi yang bersangkutan',
 'Pejabat Pembina Kepegawaian masing-masing instansi',
 'Majelis Kehormatan Kode Etik',
 'Kepala daerah setempat',
 null, 'B',
 'Kode etik instansi ditetapkan oleh Pejabat Pembina Kepegawaian masing-masing instansi, sedangkan kode etik profesi ditetapkan oleh organisasi profesi masing-masing (Pasal 13 dan 14 PP No. 42 Tahun 2004).',
 'medium'),

('b0000000-0000-4000-8000-010500000000',
 'Menurut Pasal 101 PP No. 11 Tahun 2017 tentang Manajemen PNS, setiap Jabatan Fungsional (JF) wajib memiliki 1 organisasi profesi JF paling lama...',
 '1 tahun sejak penetapan JF',
 '3 tahun sejak penetapan JF',
 '5 tahun sejak penetapan JF',
 '10 tahun sejak penetapan JF',
 null, 'C',
 'Pasal 101 PP No. 11 Tahun 2017 mewajibkan setiap JF memiliki satu organisasi profesi paling lama 5 tahun sejak penetapan JF; ketentuan ini tidak berubah meski PP tersebut diubah dengan PP No. 17 Tahun 2020.',
 'medium'),

-- ===================== BAB F: IMPLEMENTASI ETIKA DALAM ORGANISASI PEMERINTAH =====================
('b0000000-0000-4000-8000-010600000000',
 'Di sebuah unit, aturan etika sudah lengkap, tetapi pimpinan justru sering melanggarnya. Akibatnya pegawai enggan menaati aturan. Menurut Keraf (2002), faktor yang paling lemah dalam kasus ini adalah...',
 'Aturan formal internal yang rinci',
 'Sosialisasi aturan sejak awal masuk',
 'Teladan nyata dari pimpinan Kementerian',
 'Adanya sanksi tertulis',
 null, 'C',
 'Salah satu dari lima syarat Keraf agar implementasi etika berhasil adalah keteladanan nyata dari pimpinan (Menteri dan Eselon I). Pimpinan yang melanggar meruntuhkan kepatuhan pegawai.',
 'medium'),

('b0000000-0000-4000-8000-010600000000',
 'Seorang pemimpin menindak tegas pelanggaran, tetapi hanya kepada bawahan yang tidak disukainya, sementara orang dekatnya dibiarkan. Menurut Magnis-Suseno (2002), pemimpin ini gagal pada aspek...',
 'Kompetensi',
 'Konsistensi (tidak pilih kasih)',
 'Transparansi',
 'Etos kerja kelompok',
 null, 'B',
 'Dalam unsur Kepemimpinan yang Bermutu (Magnis-Suseno), Konsistensi berarti tidak pilih kasih dalam menegakkan aturan. Menindak selektif berdasarkan suka atau tidak suka melanggar aspek ini.',
 'medium'),

('b0000000-0000-4000-8000-010600000000',
 'Menurut Magnis-Suseno (2002), keberhasilan perwujudan etika dalam organisasi pemerintah dipengaruhi empat unsur utama. Keempat unsur tersebut adalah...',
 'Anggaran, sarana, teknologi, dan lokasi kantor',
 'Etos kerja, moralitas pribadi, kepemimpinan yang bermutu, dan kondisi sistemik (lingkungan kerja serta pengawasan)',
 'Pangkat, masa kerja, pendidikan, dan usia',
 'Popularitas, relasi, jabatan, dan penghasilan',
 null, 'B',
 'Magnis-Suseno menyebut empat unsur: etos kerja, moralitas pribadi, kepemimpinan yang bermutu, serta kondisi sistemik berupa lingkungan kerja dan pengawasan/pengendalian.',
 'medium'),

('b0000000-0000-4000-8000-010600000000',
 'Sebuah instansi menerapkan sanksi secara konsekuen sebagai bentuk pendidikan, dan memberi penghargaan sebagai motivasi. Langkah ini merupakan salah satu dari lima hal yang menurut Keraf (2002) diperlukan agar...',
 'Anggaran instansi meningkat',
 'Implementasi etika dalam organisasi pemerintah terwujud dengan baik',
 'Jumlah pegawai bertambah',
 'Jam kerja menjadi lebih singkat',
 null, 'B',
 'Keraf menyebut penerapan sanksi secara konsekuen sebagai pendidikan dan penghargaan sebagai motivasi merupakan salah satu dari lima syarat agar implementasi etika dalam organisasi pemerintah terwujud dengan baik.',
 'medium'),

-- ===================== BAB G: IMPLEMENTASI NILAI DASAR PNS & KODE ETIK DI KEMENKEU =====================
('b0000000-0000-4000-8000-010700000000',
 'Menjelang Pemilu, seorang pegawai Kemenkeu aktif mengunggah dukungan terbuka kepada salah satu pasangan calon di media sosial. Perbuatan ini paling bertentangan dengan Nilai Kemenkeu...',
 'Kesempurnaan',
 'Integritas',
 'Sinergi',
 'Pelayanan',
 null, 'B',
 'Nilai Integritas menuntut berperilaku baik dan benar serta memegang teguh kode etik, termasuk bersikap netral dalam Pemilu/Pilkada dan bijak bermedia sosial. Kampanye terbuka melanggar netralitas.',
 'medium'),

('b0000000-0000-4000-8000-010700000000',
 'Dalam sebuah rapat panjang lintas unit, Tia mengingatkan agar jadwal memberi jeda waktu ibadah dan membangun kerja sama yang kooperatif antarunit. Sikap Tia paling mencerminkan Nilai Kemenkeu...',
 'Sinergi',
 'Kesempurnaan',
 'Integritas',
 'Profesionalisme',
 null, 'A',
 'Nilai Sinergi berarti membangun kerja sama internal yang produktif dan kemitraan harmonis, termasuk perilaku kooperatif antarunit dan memberi kesempatan ibadah saat rapat.',
 'medium'),

('b0000000-0000-4000-8000-010700000000',
 'Rudi bekerja tuntas dan akurat sesuai kompetensi terbaiknya, disiplin terhadap jam kerja, dan menjaga kerahasiaan data. Perilaku Rudi paling mencerminkan Nilai Kemenkeu...',
 'Pelayanan',
 'Sinergi',
 'Profesionalisme',
 'Kesempurnaan',
 null, 'C',
 'Nilai Profesionalisme berarti bekerja tuntas dan akurat berdasarkan kompetensi terbaik dengan tanggung jawab dan komitmen tinggi; termasuk disiplin waktu kerja dan menjaga kerahasiaan data.',
 'medium'),

('b0000000-0000-4000-8000-010700000000',
 'Pengaturan Kode Etik dan Kode Perilaku PNS di lingkungan Kementerian Keuangan ditetapkan melalui...',
 'PP No. 42 Tahun 2004',
 'UU No. 20 Tahun 2023',
 'PMK No. 190/PMK.01/2018',
 'KMK No. 416/KMK.01/2023',
 null, 'C',
 'Kode Etik dan Kode Perilaku PNS di lingkungan Kemenkeu diatur dalam PMK No. 190/PMK.01/2018. Landasan perilakunya adalah Nilai Dasar ASN ditambah 5 Nilai Kemenkeu.',
 'medium'),

('b0000000-0000-4000-8000-010700000000',
 'Untuk mencegah pelanggaran kode etik, pimpinan unit Eselon I di Kemenkeu antara lain wajib memberdayakan sebuah unit dan berkoordinasi dengan pengawas internal. Unit dan pengawas internal yang dimaksud adalah...',
 'Unit Kepatuhan Internal (UKI) dan Inspektorat Jenderal',
 'Panitia Anggaran dan Badan Pemeriksa Keuangan',
 'Dewan Perwakilan dan Kejaksaan',
 'Serikat pegawai dan Ombudsman',
 null, 'A',
 'Pimpinan unit Eselon I wajib memberdayakan Unit Kepatuhan Internal (UKI) dan berkoordinasi dengan Inspektorat Jenderal dalam pengawasan internal untuk mencegah pelanggaran kode etik.',
 'hard'),

-- ===================== BAB H: PENEGAKAN KODE ETIK DI KEMENKEU =====================
('b0000000-0000-4000-8000-010800000000',
 'Seorang pegawai yang diduga melanggar kode etik telah dipanggil dua kali secara sah oleh Majelis Kode Etik, namun tidak hadir tanpa alasan yang sah. Tindak lanjut Majelis yang tepat adalah...',
 'Membatalkan seluruh proses karena terlapor tidak hadir',
 'Merekomendasikan sanksi moral berdasarkan bukti yang ada tanpa pemeriksaan',
 'Menyerahkan perkara ke pengadilan umum',
 'Menunggu sampai terlapor bersedia hadir tanpa batas waktu',
 null, 'B',
 'Jika terlapor tidak memenuhi panggilan kedua tanpa alasan yang sah, Majelis merekomendasikan penjatuhan sanksi moral berdasarkan bukti yang ada tanpa melakukan pemeriksaan.',
 'hard'),

('b0000000-0000-4000-8000-010800000000',
 'Sebuah instansi hendak menetapkan jumlah anggota Majelis Kode Etik lebih dari 5 orang. Ketentuan yang benar mengenai jumlah anggota tersebut adalah...',
 'Boleh genap agar mudah dibagi tugas',
 'Harus berjumlah ganjil untuk mencegah kebuntuan saat pengambilan suara',
 'Harus tepat 5 orang, tidak boleh lebih',
 'Bebas, tidak ada ketentuan jumlah',
 null, 'B',
 'Jika anggota Majelis lebih dari 5 orang, jumlahnya harus ganjil untuk mencegah deadlock ketika keputusan diambil melalui suara terbanyak.',
 'medium'),

('b0000000-0000-4000-8000-010800000000',
 'Sebuah pengaduan dugaan pelanggaran kode etik masuk, tetapi tidak mencantumkan identitas pelapor maupun terlapor dan tanpa bukti. Berdasarkan syarat pengaduan dalam PMK 190/PMK.01/2018, pengaduan ini...',
 'Langsung diproses sebagai temuan Inspektorat Jenderal',
 'Belum memenuhi syarat, karena pengaduan minimal memuat waktu dan tempat kejadian, bukti dan/atau saksi, serta identitas pelapor dan terlapor',
 'Wajib diproses meski tanpa identitas dan bukti',
 'Otomatis menjatuhkan sanksi kepada terlapor',
 null, 'B',
 'Pengaduan minimal memuat: (1) waktu dan tempat kejadian; (2) bukti dan/atau saksi; (3) identitas pelapor dan terlapor. Pengaduan tanpa unsur tersebut belum memenuhi syarat.',
 'medium'),

('b0000000-0000-4000-8000-010800000000',
 'Menurut Pasal 16 PP No. 42 Tahun 2004, PNS yang melanggar kode etik dikenakan sanksi moral, dan atas rekomendasi Majelis dapat pula dikenakan tindakan administratif berupa...',
 'Hukuman disiplin PNS sesuai PP No. 94 Tahun 2021',
 'Pidana penjara oleh Majelis',
 'Denda administratif kepada keluarga',
 'Pencabutan gelar akademik',
 null, 'A',
 'Sanksi moral dapat disertai tindakan administratif berupa hukuman disiplin PNS (diatur PP No. 94 Tahun 2021) atas rekomendasi Majelis Kode Etik. Sanksi moral dibuat tertulis, berupa pernyataan tertutup atau terbuka.',
 'medium'),

('b0000000-0000-4000-8000-010800000000',
 'Dalam pembentukan Majelis Kode Etik untuk memeriksa seorang pejabat, terdapat ketentuan mengenai jabatan dan pangkat anggota Majelis, yaitu...',
 'Boleh lebih rendah asalkan jumlahnya banyak',
 'Tidak boleh lebih rendah dari jabatan dan pangkat PNS yang diperiksa',
 'Harus selalu lebih tinggi dua tingkat',
 'Tidak diatur sama sekali',
 null, 'B',
 'Jabatan dan pangkat anggota Majelis tidak boleh lebih rendah dari jabatan dan pangkat PNS yang diperiksa, demi menjaga kewibawaan dan keadilan pemeriksaan.',
 'medium'),

-- ===================== BAB I: IMPLEMENTASI KODE ETIK PADA ERA SISTEM KERJA FLEKSIBEL =====================
('b0000000-0000-4000-8000-010900000000',
 'Selama bekerja fleksibel dari rumah (SKF), Nino merasa tidak diawasi langsung sehingga sering terlambat mengisi presensi dan tidak melaporkan hasil kerja. Berdasarkan kewajiban pegawai dalam KMK 416/KMK.01/2023, sikap Nino keliru karena...',
 'SKF membebaskan pegawai dari jam kerja dan pelaporan',
 'Pegawai tetap wajib mematuhi jam kerja, mengisi presensi, dan melaporkan hasil kerja melalui aplikasi office automation',
 'Presensi hanya berlaku bagi pegawai yang bekerja di kantor',
 'Pelaporan hasil kerja hanya diperlukan saat diminta atasan',
 null, 'B',
 'KMK 416/KMK.01/2023 mewajibkan pegawai mengisi daftar hadir via aplikasi presensi, patuh jam kerja, dan melaporkan hasil kerja via aplikasi pelaporan office automation. Fleksibilitas bukan berarti bebas tanpa batas.',
 'medium'),

('b0000000-0000-4000-8000-010900000000',
 'Saat SKF, Lita mengakses aplikasi kantor lewat WiFi publik yang tidak aman dan mengabaikan pembaruan antivirus, sehingga data berisiko bocor. Aspek kode etik selama SKF yang paling dilanggar Lita adalah...',
 'Etika sosial dan kesopanan digital',
 'Tanggung jawab dan integritas dalam menjaga keamanan data',
 'Disiplin penggunaan waktu kerja',
 'Etika dalam komunikasi dan kolaborasi',
 null, 'B',
 'Salah satu aspek kode etik penting selama SKF adalah tanggung jawab dan integritas menjaga keamanan data: menghindari internet tidak aman, waspada phishing, memperbarui sistem/antivirus, dan mem-backup data.',
 'medium'),

('b0000000-0000-4000-8000-010900000000',
 'Dalam sebuah acara resmi kedinasan yang dilaksanakan secara virtual, panduan etika mengharuskan peserta untuk...',
 'Mematikan kamera agar hemat kuota',
 'Menyalakan video wajah dan bersikap hormat serta tegap saat lagu kebangsaan atau pengibaran bendera',
 'Bergabung kapan saja tanpa keharusan tepat waktu',
 'Menggunakan nama samaran demi privasi',
 null, 'B',
 'Panduan etika acara kedinasan virtual (SE-42/MK.01/2020) antara lain mewajibkan menyalakan video wajah dan bersikap hormat dengan posisi tegap saat lagu kebangsaan atau pengibaran bendera.',
 'medium'),

('b0000000-0000-4000-8000-010900000000',
 'Sistem Kerja Fleksibel (SKF) di Kementerian Keuangan ditetapkan melalui...',
 'PP No. 42 Tahun 2004',
 'PMK No. 190/PMK.01/2018',
 'Keputusan Menteri Keuangan Nomor 416/KMK.01/2023',
 'UU No. 20 Tahun 2023',
 null, 'C',
 'SKF ditetapkan melalui KMK Nomor 416/KMK.01/2023 sebagai respons dinamika lingkungan kerja. Justru dalam SKF, etika dan integritas makin krusial karena pegawai tidak selalu dalam pengawasan langsung.',
 'medium'),

('b0000000-0000-4000-8000-010900000000',
 'Saat bekerja fleksibel, seorang pegawai menggunakan laptop dan aplikasi kantor untuk menjalankan usaha pribadinya di jam kerja. Perbuatan ini melanggar aspek kode etik SKF berupa...',
 'Penggunaan sarana dan prasarana secara etis, tidak untuk kepentingan pribadi',
 'Etika komunikasi dan kolaborasi',
 'Kepatuhan terhadap pengawasan dan evaluasi',
 'Etika sosial dan kesopanan digital',
 null, 'A',
 'Salah satu aspek kode etik selama SKF adalah penggunaan sarana-prasarana secara etis, yakni tidak menyalahgunakannya untuk kepentingan pribadi.',
 'medium'),

-- ===================== BAB PENUTUP =====================
('b0000000-0000-4000-8000-011000000000',
 'Pesan penutup modul menegaskan bahwa kepatuhan terhadap etika menjadi ukuran kematangan pribadi dan profesionalisme pegawai. Ukuran ini berlaku...',
 'Hanya di lingkungan kerja fisik (kantor)',
 'Hanya saat diawasi atasan',
 'Baik di lingkungan kerja fisik maupun digital',
 'Hanya bagi pejabat, bukan pegawai pelaksana',
 null, 'C',
 'Modul menutup dengan penegasan bahwa kepatuhan terhadap etika adalah ukuran kematangan dan profesionalisme pegawai, baik dalam lingkungan kerja fisik maupun digital.',
 'easy'),

('b0000000-0000-4000-8000-011000000000',
 'Menurut bagian Penutup, kode etik dan kode perilaku sebaiknya dimaknai sebagai...',
 'Sekadar aturan formal yang penting saat ada pemeriksaan',
 'Pedoman sikap yang mencerminkan nilai dasar ASN dan budaya organisasi',
 'Formalitas administratif tanpa pengaruh pada perilaku',
 'Beban yang menghambat kinerja pegawai',
 null, 'B',
 'Penutup menegaskan kode etik dan kode perilaku bukan sekadar aturan formal, melainkan pedoman sikap yang mencerminkan nilai dasar ASN dan budaya organisasi.',
 'easy'),

-- ============================================================
-- TAMBAHAN (perdalam) — studi kasus lanjutan per bab
-- ============================================================

-- ---- BAB A: PENGANTAR ----
('b0000000-0000-4000-8000-010100000000',
 'Menjelang tutup tahun anggaran, Hasan tergoda memakai fasilitas kantor untuk urusan pribadi, berpikir hasil kerjanya sudah bagus. Pesan Bab Pengantar yang paling tepat menegur pikiran ini adalah...',
 'Selama target tercapai, penggunaan fasilitas untuk pribadi wajar',
 'Sebagai pengelola keuangan negara, PNS mengemban amanah sehingga wajib menjunjung nilai moral, hukum, dan kepatutan, bukan sekadar hasil',
 'Etika hanya relevan bagi pejabat tinggi',
 'Kepatutan tidak penting selama tidak melanggar hukum tertulis',
 null, 'B',
 'Bab Pengantar menegaskan PNS sebagai pengelola keuangan negara mengemban amanah, sehingga menjunjung nilai moral, hukum, dan kepatutan adalah keharusan, bukan sekadar mengejar hasil.',
 'medium'),

('b0000000-0000-4000-8000-010100000000',
 'Kedudukan PNS sebagai pelayan publik sekaligus pengelola keuangan negara membawa implikasi utama terhadap perilakunya, yaitu...',
 'PNS bebas menentukan standar moralnya sendiri',
 'Etika menjadi landasan penting perilaku karena menyangkut kepercayaan publik dan pengelolaan sumber daya negara',
 'PNS cukup fokus pada tugas teknis semata',
 'Nilai moral hanya berlaku di luar jam kerja',
 null, 'B',
 'Karena menyangkut kepercayaan publik dan pengelolaan sumber daya negara, etika menjadi landasan penting perilaku PNS di lingkungan birokrasi.',
 'medium'),

-- ---- BAB B: PRINSIP MORAL ----
('b0000000-0000-4000-8000-010200000000',
 'Andre ditugaskan menangani pekerjaan yang menantang. Alih-alih memaksakan diri berisiko salah, ia belajar, mengikuti aturan, dan konsisten menjalankan tugas sesuai kompetensinya. Sikap Andre paling mencerminkan prinsip moral...',
 'Profesionalisme',
 'Bertindak adil',
 'Jangan menghalalkan segala cara',
 'Tanggung jawab terhadap kepentingan publik',
 null, 'A',
 'Prinsip Profesionalisme menuntut bertindak sesuai kemampuan/keahlian dan peraturan, serta konsekuen dan konsisten menjalankan profesi.',
 'medium'),

('b0000000-0000-4000-8000-010200000000',
 'Seorang atasan meminta Nia menuliskan laporan yang "sedikit dipoles" agar terlihat baik, padahal faktanya bermasalah. Nia menolak, dengan sikap tegas bahwa yang salah tetap salah dan yang benar tetap benar. Prinsip moral yang dipegang Nia adalah...',
 'Berpihak kepada kebenaran dan kejujuran',
 'Bertindak adil',
 'Profesionalisme',
 'Jangan lakukan pada orang lain apa yang tidak ingin dilakukan pada diri sendiri',
 null, 'A',
 'Prinsip Berpihak kepada Kebenaran dan Kejujuran menuntut sikap tegas: yang salah adalah salah, yang benar adalah benar. Kejujuran adalah prinsip paling pokok bagi penyelenggara negara.',
 'medium'),

('b0000000-0000-4000-8000-010200000000',
 'Manakah situasi yang paling menggambarkan pelanggaran prinsip Bertindak Adil?',
 'Menolak gratifikasi dari pihak yang dilayani',
 'Memberikan mutu pelayanan berbeda berdasarkan suku atau agama pemohon',
 'Bekerja sesuai standar operasional prosedur',
 'Melaporkan dugaan pelanggaran sesuai ketentuan',
 null, 'B',
 'Prinsip Bertindak Adil menuntut memperlakukan semua orang sama tanpa diskriminasi. Membedakan mutu layanan berdasarkan suku atau agama melanggar prinsip ini.',
 'medium'),

('b0000000-0000-4000-8000-010200000000',
 'Menurut Sonny Keraf, profesi PNS pada hakikatnya adalah panggilan untuk mengabdi, bukan sarana mengejar kekayaan atau kedudukan. Pandangan ini merupakan inti dari prinsip...',
 'Tanggung jawab terhadap kepentingan publik',
 'Profesionalisme',
 'Bertindak adil',
 'Integritas moral yang tinggi',
 null, 'A',
 'Prinsip Tanggung Jawab terhadap Kepentingan Publik menegaskan kepentingan publik sebagai nilai tertinggi dan profesi PNS sebagai panggilan mengabdi, bukan mencari kekayaan atau kedudukan.',
 'medium'),

-- ---- BAB C: PENGERTIAN ETIKA ----
('b0000000-0000-4000-8000-010300000000',
 'Dalam pembahasan modul, istilah "etika PNS" pada akhirnya diartikan setara dengan...',
 'Peraturan disiplin pegawai',
 'Kode etik PNS',
 'Sumpah jabatan PNS',
 'Perjanjian kinerja PNS',
 null, 'B',
 'Untuk pembahasan selanjutnya, modul mengartikan etika PNS sebagai kode etik PNS.',
 'easy'),

('b0000000-0000-4000-8000-010300000000',
 'Pernyataan yang tepat mengenai hubungan etika dan moral menurut modul adalah...',
 'Etika dan moral saling bertentangan',
 'Etika berasal dari Yunani (ethos) dan moral dari Latin (mos/mores); keduanya berpengertian kurang lebih sama tentang kebiasaan berbuat baik',
 'Moral hanya untuk urusan agama, etika hanya untuk urusan kerja',
 'Etika selalu bertingkat lebih rendah daripada moral',
 null, 'B',
 'Etika (Yunani: ethos) dan moral (Latin: mos/mores) sama-sama merujuk adat kebiasaan melakukan perbuatan baik; modul menyatakan keduanya berpengertian kurang lebih sama.',
 'medium'),

-- ---- BAB D: KODE ETIK PNS ----
('b0000000-0000-4000-8000-010400000000',
 'Sebuah unit banyak menerima keluhan lambatnya layanan. Wira berinisiatif memahami kebutuhan masyarakat, bersikap ramah, cekatan, solutif, dan terus memperbaiki proses. Sikap Wira mencerminkan nilai dasar ASN...',
 'Berorientasi pelayanan',
 'Loyal',
 'Adaptif',
 'Akuntabel',
 null, 'A',
 'Nilai Berorientasi Pelayanan berarti memahami dan memenuhi kebutuhan masyarakat, bersikap ramah, cekatan, solutif, dapat diandalkan, serta melakukan perbaikan tiada henti.',
 'medium'),

('b0000000-0000-4000-8000-010400000000',
 'Fina rutin meningkatkan kompetensinya dan membantu rekan belajar agar kualitas kerja tim menjadi yang terbaik. Nilai dasar ASN yang paling menonjol adalah...',
 'Harmonis',
 'Kompeten',
 'Kolaboratif',
 'Loyal',
 null, 'B',
 'Nilai Kompeten berarti terus meningkatkan kompetensi diri, membantu orang lain belajar, dan memberikan kualitas kerja terbaik.',
 'medium'),

('b0000000-0000-4000-8000-010400000000',
 'Di unit dengan anggota beragam latar belakang, Reza menghargai perbedaan, suka menolong, dan menjaga lingkungan kerja tetap kondusif. Nilai dasar ASN yang ia terapkan adalah...',
 'Harmonis',
 'Akuntabel',
 'Adaptif',
 'Berorientasi pelayanan',
 null, 'A',
 'Nilai Harmonis berarti saling peduli dan menghargai perbedaan tanpa membedakan latar belakang, suka menolong, serta membangun lingkungan kerja yang kondusif.',
 'medium'),

('b0000000-0000-4000-8000-010400000000',
 'Ketika instansi menerapkan sistem kerja baru, Yuni cepat menyesuaikan diri dan proaktif berinovasi, sekaligus terbuka bekerja sama menggerakkan berbagai pihak. Dua nilai dasar ASN yang paling tercermin adalah...',
 'Adaptif dan Kolaboratif',
 'Loyal dan Akuntabel',
 'Harmonis dan Kompeten',
 'Berorientasi pelayanan dan Loyal',
 null, 'A',
 'Adaptif berarti cepat menyesuaikan diri dan berinovasi; Kolaboratif berarti terbuka bekerja sama dan menggerakkan sumber daya untuk tujuan bersama.',
 'medium'),

('b0000000-0000-4000-8000-010400000000',
 'Menjaga informasi rahasia, patuh pada standar operasional prosedur, dan melaksanakan kebijakan pejabat berwenang termasuk dalam etika PNS pada ranah...',
 'Etika dalam berorganisasi',
 'Etika dalam bermasyarakat',
 'Etika terhadap diri sendiri',
 'Etika dalam bernegara',
 null, 'A',
 'Menurut Pasal 7 PP No. 42 Tahun 2004, menjaga informasi rahasia, patuh SOP, dan melaksanakan kebijakan pejabat berwenang termasuk Etika PNS dalam Berorganisasi.',
 'hard'),

('b0000000-0000-4000-8000-010400000000',
 'Seorang PNS menolak menangani perkara yang melibatkan bisnis keluarganya karena berpotensi konflik kepentingan. Perbuatan ini termasuk etika PNS terhadap...',
 'Diri sendiri',
 'Sesama PNS',
 'Masyarakat',
 'Negara',
 null, 'A',
 'Etika PNS terhadap Diri Sendiri mencakup menghindari konflik kepentingan. Menolak menangani perkara yang melibatkan bisnis keluarga adalah wujudnya.',
 'medium'),

-- ---- BAB E: KODE ETIK INSTANSI & PROFESI ----
('b0000000-0000-4000-8000-010500000000',
 'Salah satu syarat mutlak agar sebuah kode etik profesi benar-benar berfungsi adalah kode etik itu dibuat oleh...',
 'Masing-masing profesi, agar dijiwai cita-cita dan nilai profesi tersebut',
 'Lembaga legislatif',
 'Atasan langsung pegawai',
 'Majelis Kode Etik pusat',
 null, 'A',
 'Syarat pertama agar kode etik berfungsi adalah dibuat oleh masing-masing profesi sehingga dijiwai cita-cita dan nilai profesi bersangkutan.',
 'medium'),

('b0000000-0000-4000-8000-010500000000',
 'Menurut PP No. 11 Tahun 2017, tugas organisasi profesi Jabatan Fungsional antara lain menyusun kode etik profesi, memberikan advokasi, serta...',
 'Menetapkan besaran gaji anggota',
 'Memeriksa dan memberi rekomendasi atas pelanggaran kode etik/kode perilaku profesi',
 'Mengangkat pejabat struktural',
 'Menyusun anggaran instansi',
 null, 'B',
 'Tugas organisasi profesi JF meliputi menyusun kode etik/kode perilaku profesi, memberikan advokasi, serta memeriksa dan memberi rekomendasi atas pelanggaran kode etik/kode perilaku profesi.',
 'medium'),

('b0000000-0000-4000-8000-010500000000',
 'PP No. 11 Tahun 2017 tentang Manajemen PNS kemudian diubah dengan PP No. 17 Tahun 2020. Terkait Pasal 101 tentang organisasi profesi, ketentuannya...',
 'Dihapus seluruhnya',
 'Tidak mengalami perubahan',
 'Diganti dengan peraturan daerah',
 'Ditangguhkan sementara',
 null, 'B',
 'PP No. 11 Tahun 2017 diubah dengan PP No. 17 Tahun 2020, namun Pasal 101 tentang organisasi profesi tidak mengalami perubahan.',
 'medium'),

-- ---- BAB F: IMPLEMENTASI DALAM ORGANISASI ----
('b0000000-0000-4000-8000-010600000000',
 'Di sebuah kantor, sikap dasar pegawai dalam bekerja sangat dipengaruhi kebiasaan kelompok di sekitarnya; bila kelompoknya rajin, individu ikut rajin. Menurut Magnis-Suseno, hal ini menggambarkan unsur...',
 'Etos kerja',
 'Moralitas pribadi',
 'Kepemimpinan yang bermutu',
 'Transparansi keputusan',
 null, 'A',
 'Etos Kerja adalah sikap dasar dalam bekerja yang dapat dipengaruhi etos kerja kelompok di sekitarnya.',
 'medium'),

('b0000000-0000-4000-8000-010600000000',
 'Kesesuaian sikap dan perilaku pegawai dengan norma, yang mencakup kejujuran, tidak korupsi, dan taat etika birokrasi, menurut Magnis-Suseno termasuk unsur...',
 'Moralitas pribadi',
 'Etos kerja',
 'Kondisi sistemik',
 'Kepemimpinan yang bermutu',
 null, 'A',
 'Moralitas Pribadi adalah kesesuaian sikap dan perilaku dengan norma, mencakup kejujuran, tidak korupsi, dan taat etika birokrasi.',
 'medium'),

('b0000000-0000-4000-8000-010600000000',
 'Menurut Magnis-Suseno, keberhasilan penerapan etika juga bergantung pada kondisi sistemik, yaitu lingkungan kerja yang mendukung serta...',
 'Besarnya anggaran instansi',
 'Pengawasan dan pengendalian dari dalam maupun luar organisasi, termasuk pengawasan masyarakat',
 'Jumlah pegawai yang banyak',
 'Lokasi kantor yang strategis',
 null, 'B',
 'Kondisi sistemik mencakup lingkungan kerja yang mendukung dan pengawasan/pengendalian dari dalam maupun luar organisasi, termasuk pengawasan masyarakat.',
 'hard'),

('b0000000-0000-4000-8000-010600000000',
 'Menurut Keraf, agar implementasi etika berhasil, komitmen moral pimpinan perlu diterjemahkan menjadi... dan disosialisasikan sejak pegawai mulai masuk.',
 'Slogan yang dipajang di dinding',
 'Aturan formal internal yang rinci termasuk sanksi yang jelas',
 'Anggaran tambahan tahunan',
 'Struktur organisasi yang baru',
 null, 'B',
 'Keraf menyebut komitmen moral pimpinan harus diterjemahkan ke aturan formal internal yang rinci termasuk sanksi jelas, lalu disosialisasikan sejak awal pegawai masuk.',
 'medium'),

-- ---- BAB G: IMPLEMENTASI DI KEMENKEU ----
('b0000000-0000-4000-8000-010700000000',
 'Bima melayani setiap pemangku kepentingan dengan sepenuh hati, ramah, santun, transparan, dan tidak diskriminatif. Nilai Kemenkeu yang paling tercermin adalah...',
 'Pelayanan',
 'Integritas',
 'Kesempurnaan',
 'Sinergi',
 null, 'A',
 'Nilai Pelayanan berarti memenuhi kepuasan pemangku kepentingan dengan sepenuh hati, transparan, cepat, akurat, dan aman, serta tanpa diskriminasi.',
 'medium'),

('b0000000-0000-4000-8000-010700000000',
 'Sebuah unit terus melakukan perbaikan dan inovasi di segala bidang untuk menjadi dan memberikan yang terbaik. Nilai Kemenkeu yang diterapkan adalah...',
 'Kesempurnaan',
 'Profesionalisme',
 'Pelayanan',
 'Sinergi',
 null, 'A',
 'Nilai Kesempurnaan berarti senantiasa melakukan perbaikan di segala bidang untuk menjadi dan memberikan yang terbaik.',
 'medium'),

('b0000000-0000-4000-8000-010700000000',
 'SE Nomor 12/MK.01/2019 mengatur penerapan nilai Pancasila dan Bela Negara bagi PNS Kemenkeu. Salah satu nilai Bela Negara yang dimaksud adalah...',
 'Cinta tanah air',
 'Mengejar keuntungan pribadi',
 'Netralitas anggaran',
 'Efisiensi belanja semata',
 null, 'A',
 'Nilai Bela Negara antara lain cinta tanah air, kesadaran berbangsa dan bernegara, yakin Pancasila sebagai ideologi negara, serta rela berkorban untuk bangsa dan negara.',
 'medium'),

('b0000000-0000-4000-8000-010700000000',
 'Berdasarkan ketentuan penerapan nilai Pancasila di Kemenkeu, hari lahir Pancasila yang wajib diperingati setiap tahun jatuh pada tanggal...',
 '1 Juni',
 '17 Agustus',
 '1 Oktober',
 '28 Oktober',
 null, 'A',
 'Terdapat kewajiban memperingati hari lahir Pancasila setiap tanggal 1 Juni.',
 'easy'),

-- ---- BAB H: PENEGAKAN ----
('b0000000-0000-4000-8000-010800000000',
 'Majelis Kode Etik akan memeriksa seorang terlapor. Pemanggilan pertama secara tertulis dilakukan paling singkat berapa lama sebelum tanggal pemeriksaan?',
 '3 hari kerja',
 '7 hari kerja',
 '14 hari kerja',
 '30 hari kerja',
 null, 'B',
 'Pemanggilan pertama secara tertulis dilakukan paling singkat 7 hari kerja sebelum tanggal pemeriksaan.',
 'medium'),

('b0000000-0000-4000-8000-010800000000',
 'Dalam pemeriksaan oleh Majelis Kode Etik, sidang dilakukan secara tertutup dan keputusan diambil dengan cara...',
 'Ditentukan sepihak oleh ketua Majelis',
 'Musyawarah mufakat; bila tidak tercapai, diambil suara terbanyak',
 'Diserahkan ke pengadilan umum',
 'Ditentukan oleh atasan terlapor',
 null, 'B',
 'Pemeriksaan dilakukan dalam sidang tertutup; keputusan diambil secara musyawarah mufakat, dan bila tidak tercapai diambil berdasarkan suara terbanyak.',
 'medium'),

('b0000000-0000-4000-8000-010800000000',
 'Dugaan pelanggaran kode etik dapat berasal dari pengaduan dan/atau temuan. Yang termasuk kategori Temuan adalah...',
 'Temuan atasan terlapor, Unit Kepatuhan Internal, dan/atau Inspektorat Jenderal',
 'Temuan dari akun media sosial pribadi',
 'Temuan dari keluarga terlapor',
 'Temuan organisasi profesi luar instansi',
 null, 'A',
 'Temuan terdiri atas Temuan Atasan Terlapor, Temuan Unit Kepatuhan Internal, dan/atau Temuan Inspektorat Jenderal.',
 'medium'),

('b0000000-0000-4000-8000-010800000000',
 'Sanksi moral bagi pelanggar kode etik dibuat secara tertulis dan dapat berupa...',
 'Pernyataan secara tertutup atau pernyataan secara terbuka',
 'Denda dan pidana penjara',
 'Penurunan gaji secara otomatis',
 'Pemberhentian seketika tanpa proses',
 null, 'A',
 'Sesuai Pasal 16 PP No. 42 Tahun 2004, sanksi moral dibuat tertulis berupa pernyataan secara tertutup atau pernyataan secara terbuka.',
 'medium'),

-- ---- BAB I: SISTEM KERJA FLEKSIBEL ----
('b0000000-0000-4000-8000-010900000000',
 'Selama SKF, salah satu kewajiban pegawai adalah tetap responsif dan dapat dihubungi. Bentuk konkretnya adalah...',
 'Mengabaikan pesan kerja di luar jam istirahat',
 'Online dan siap dihubungi melalui peralatan kolaborasi resmi Kementerian Keuangan pada jam kerja',
 'Hanya menerima telepon pribadi',
 'Menonaktifkan seluruh notifikasi kerja',
 null, 'B',
 'KMK 416/2023 mewajibkan pegawai tetap responsif, dapat dihubungi, dan online di peralatan kolaborasi Kementerian Keuangan selama jam kerja.',
 'medium'),

('b0000000-0000-4000-8000-010900000000',
 'Rina terdaftar pada dua kegiatan kedinasan virtual yang berlangsung bersamaan. Berdasarkan pedoman etika acara virtual, sikap yang tepat adalah...',
 'Mengikuti keduanya sekaligus sambil mematikan kamera',
 'Memprioritaskan dan fokus pada salah satu kegiatan',
 'Tidak mengikuti keduanya',
 'Menyerahkan akun kepada rekan kerja',
 null, 'B',
 'Pedoman etika acara virtual menyebutkan bila ada dua kegiatan bersamaan, pegawai memprioritaskan salah satu kegiatan.',
 'medium'),

('b0000000-0000-4000-8000-010900000000',
 'Untuk acara resmi kedinasan virtual, peserta diminta bergabung paling lambat berapa lama sebelum acara dimulai?',
 '1 menit',
 '3 menit',
 '10 menit',
 '30 menit',
 null, 'B',
 'Ketentuan teknis acara virtual menyebutkan peserta bergabung paling lambat 3 menit sebelum acara dimulai, serta login lebih awal untuk verifikasi host.',
 'medium'),

('b0000000-0000-4000-8000-010900000000',
 'Etika teknis dalam rapat kedinasan virtual antara lain mencantumkan nama asli dan unit kerja, menampilkan wajah, serta...',
 'Menggunakan nama panggilan bebas',
 'Mematikan mikrofon saat pimpinan atau narasumber sedang berbicara',
 'Menyalakan mikrofon terus-menerus',
 'Mengganti latar dengan gambar bebas tanpa aturan',
 null, 'B',
 'Ketentuan teknis rapat virtual mencakup mencantumkan nama asli dan unit kerja, menampilkan wajah, serta mematikan mikrofon saat pimpinan atau narasumber berbicara.',
 'medium'),

-- ---- BAB PENUTUP ----
('b0000000-0000-4000-8000-011000000000',
 'Bagian Penutup menegaskan setiap pegawai Kemenkeu bertanggung jawab menjaga dua hal melalui perilaku etis di setiap kondisi kerja. Dua hal itu adalah...',
 'Nama baik institusi dan kepercayaan masyarakat',
 'Jumlah anggaran dan aset pribadi',
 'Jabatan dan pangkat pribadi',
 'Popularitas dan relasi',
 null, 'A',
 'Penutup menegaskan setiap pegawai bertanggung jawab menjaga nama baik institusi dan kepercayaan masyarakat melalui perilaku etis di setiap kondisi kerja.',
 'easy')
;
