-- Materi + mind map + soal: Bab "Verbal #2" (Modul TPA v2)
-- Sub-topik: Analogi, Analogi Induktif, Analogi Deklaratif, Kelompok Kata
-- (dipecah dari seed_tpa_v2_verbal2_wacana.sql supaya 1 file = 1 bab)

delete from questions where chapter_id = 'b0000000-0000-4000-8000-060200000000';
delete from contents where chapter_id = 'b0000000-0000-4000-8000-060200000000';

insert into contents (chapter_id, heading, body, order_index) values
('b0000000-0000-4000-8000-060200000000', 'Analogi', '**Definisi:** Soal analogi menguji seberapa cepat kamu menangkap hubungan logis antara dua kata yang berpasangan (bentuk A : B), lalu menerapkan hubungan yang sama pada pasangan kata lain.

**Cara Kerja / Langkah Pengerjaan:**
1. Baca pasangan kata A : B pada soal, lalu kenali jenis hubungannya (tempat dengan produk khas, alat dengan profesi, sebab-akibat, benda dengan fungsinya, ukuran, atau golongan/kategori).
2. Ubah hubungan itu menjadi satu kalimat pendek yang menjelaskan keterkaitannya, misalnya "A adalah tempat yang menghasilkan B" atau "A adalah alat yang dipakai oleh profesi B".
3. Untuk soal level lanjutan, periksa apakah polanya berlapis: gradasi intensitas, simbol dengan makna, urutan proses/tahapan, atau gabungan dua lapis hubungan sekaligus.
4. Uji pola kalimat itu ke tiap pilihan jawaban satu per satu, lalu coret opsi yang tidak menghasilkan kalimat dengan pola serupa.
5. Untuk pola gradasi atau urutan, pastikan arah dan derajat hubungannya benar-benar sepadan dengan soal, bukan cuma temanya yang mirip.

**Rumus & Poin Kunci:**
- Jenis hubungan yang sering muncul: tempat dengan produk khasnya (sawah : padi), alat dengan profesi yang memakainya (petani : cangkul), sebab dengan akibat (lapar : makan), benda dengan fungsinya, hubungan ukuran (besar-kecil), serta hubungan golongan/kategori (jenis-genus).
- Hubungan gradasi intensitas adalah urutan tingkat kekuatan/kadar suatu keadaan, misalnya GERIMIS : HUJAN sejajar dengan SEJUK : DINGIN (gerimis adalah tingkat hujan yang lebih ringan, sejuk adalah tingkat dingin yang lebih ringan).
- Hubungan simbol dengan makna yang diwakilinya, misalnya MERAH : BAHAYA sejajar dengan PUTIH : SUCI -- ini hubungan benda/warna dengan makna simbolis yang disepakati secara sosial, bukan hubungan benda dengan sifat fisiknya.
- Hubungan urutan proses atau tahapan, misalnya TELUR : ULAT : KEPOMPONG : KUPU-KUPU atau BENIH : TUNAS : POHON, yang menuntutmu mengenali posisi suatu kata dalam sebuah rangkaian proses, bukan cuma satu pasangan lepas.
- Soal level lanjutan kerap menggabungkan dua lapis hubungan sekaligus, misalnya sebab-akibat yang di dalamnya juga tersembunyi hubungan gradasi, sehingga kamu perlu menalar dua langkah: menemukan pola dasar dulu, baru menyaring tingkat/derajatnya.

**Kesalahan Umum / Jebakan:**
- Opsi yang hubungannya tampak mirip tapi arah atau derajatnya terbalik, atau levelnya tidak sepadan dengan pola pertanyaan.
- Berhenti di hubungan permukaan yang pertama kali terlintas tanpa mengecek apakah hubungan itu punya "arah" atau "derajat" tertentu, padahal itulah jebakan paling umum di level OTO Bappenas.

**Tips cara cepat**: baca dulu pasangan A : B pada soal, lalu ubah menjadi satu kalimat pendek yang menjelaskan keterkaitannya, misalnya "A adalah tempat yang menghasilkan B" atau "A adalah alat yang dipakai oleh profesi B". Setelah pola kalimatnya ketemu, cocokkan pola itu ke tiap pilihan jawaban satu per satu, lalu coret opsi yang tidak menghasilkan kalimat dengan pola serupa. Cara ini jauh lebih cepat dan minim jebakan dibanding menghafal sinonim kata semata, karena kunci soal analogi adalah hubungan, bukan makna kata itu sendiri. Untuk soal level lanjutan, jangan berhenti di hubungan permukaan yang pertama kali terlintas -- cek apakah hubungan itu punya "arah" atau "derajat" tertentu (misalnya dari ringan ke berat, dari awal ke akhir proses), karena jebakan paling umum di level OTO Bappenas adalah opsi yang hubungannya mirip tapi arah/derajatnya terbalik atau levelnya tidak sepadan.

**Kesimpulan:** Kuasai pola dasar hubungan A : B dengan mengubahnya jadi kalimat pendek, lalu untuk soal level lanjutan selalu waspadai arah dan derajat hubungannya agar tidak terjebak opsi yang mirip tapi tidak sepadan.

**Contoh Soal:** Lengkapi pola gradasi berikut: RIAK : OMBAK : TSUNAMI = ... : ... : ... Manakah deret emosi yang menjadi analogi paling presisi?

- A. (KECEWA, MARAH, MENGAMUK)
- B. (SEDIH, KECEWA, MARAH)
- C. (JENGKEL, MARAH, MENGAMUK)
- D. (TAKUT, WASPADA, PANIK)
- E. (SENANG, GEMBIRA, BAHAGIA)

**Pembahasan:**

**Diketahui:** Pola RIAK : OMBAK : TSUNAMI adalah hubungan gradasi intensitas gelombang air dari yang paling lemah (riak) ke sedang (ombak) ke paling dahsyat (tsunami) -- tiga tingkat kekuatan yang berjenjang naik dalam satu jenis fenomena yang sama.

**Ditanya:** Deret emosi manakah (opsi A-E) yang menjadi analogi paling presisi dengan pola gradasi tersebut?

**Jawab:** Kita butuh deret emosi yang juga berjenjang tiga tingkat dari paling ringan ke paling ekstrem, dan seluruh deret harus berasal dari satu jenis emosi yang sama (bukan campuran emosi berbeda). Opsi A (KECEWA, MARAH, MENGAMUK) kurang presisi karena "kecewa" bukan tingkat paling ringan dari skala kemarahan, melainkan emosi lain yang berdekatan. Opsi B (SEDIH, KECEWA, MARAH) juga tidak tepat karena "sedih" bukan bagian dari skala intensitas marah, melainkan jenis emosi berbeda. Opsi D (TAKUT, WASPADA, PANIK) adalah gradasi emosi takut, bukan emosi marah seperti pada soal. Opsi E (SENANG, GEMBIRA, BAHAGIA) adalah gradasi emosi senang, juga bukan marah. Opsi C (JENGKEL, MARAH, MENGAMUK) benar-benar presisi, sebab jengkel adalah tingkat kemarahan paling ringan, marah adalah tingkat menengah, dan mengamuk adalah puncak intensitasnya -- persis mengikuti pola riak-ombak-tsunami yang sama-sama menaik tiga tingkat dari ringan ke ekstrem dalam satu jenis fenomena (gelombang air vs emosi marah). Ini menegaskan bahwa kunci soal gradasi bukan sekadar "sama-sama emosi" atau "sama-sama air", melainkan konsistensi arah kenaikan intensitas pada jenis fenomena yang benar-benar sama. Jadi jawabannya adalah C.', 1),
('b0000000-0000-4000-8000-060200000000', 'Analogi Induktif', '**Definisi:** Analogi induktif adalah cara menyimpulkan pola hubungan umum setelah melihat beberapa contoh pasangan kata yang sejenis, bukan hanya dari satu pasangan A : B saja.

**Cara Kerja / Langkah Pengerjaan:**
1. Kenali bentuk soalnya: kamu disodori beberapa pasangan kata sekaligus (biasanya tiga pasang atau lebih, kadang empat atau lebih pada level lanjutan) yang semuanya mengikuti satu pola hubungan tertentu.
2. Bandingkan seluruh pasangan yang diberikan untuk menemukan benang merah hubungannya (apakah semuanya soal sebab-akibat, bagian-keseluruhan, ciri khas, atau golongan yang sama).
3. Uji pola yang kamu temukan ke SETIAP pasangan sampai pasangan terakhir sebelum menyimpulkan -- jangan berhenti setelah dua atau tiga pasangan pertama saja.
4. Jika ada satu pasangan yang tidak cocok dengan pola mayoritas, curigai itu sebagai jebakan dan cari pola yang lebih sempit/spesifik yang tetap konsisten menaungi pasangan-pasangan lain.
5. Terapkan pola final yang sudah teruji itu untuk menarik simpulan atau melengkapi pasangan/opsi berikutnya yang konsisten.

**Rumus & Poin Kunci:**
- Pada level soal yang lebih menantang, analogi induktif menyajikan empat pasangan kata atau lebih sekaligus, bukan cuma tiga.
- Contoh pola yang valid: GAJAH : BELALAI, JERAPAH : LEHER, BURUNG : PARUH sama-sama menunjukkan hubungan hewan dengan ciri fisik paling menonjol/khas yang menjadi identitas utamanya.
- Rumuskan pola seketat dan sespesifik mungkin (misalnya "ciri fisik unik yang menjadi identitas utama hewan", bukan sekadar "hewan dengan bagian tubuhnya") supaya pasangan yang menyimpang lebih mudah terlihat.

**Kesalahan Umum / Jebakan:**
- Salah satu pasangan sengaja disisipkan sebagai jebakan: sekilas tampak sejenis (topik atau kategorinya sama) tetapi sebenarnya mengikuti pola hubungan yang berbeda. Contoh: IKAN : SISIK tampak semirip GAJAH : BELALAI dkk secara topik (hewan dan bagian tubuh), padahal sisik bukan ciri paling menonjol yang membedakan ikan (hampir semua ikan bersisik secara umum), sehingga bukan hubungan ciri unik pembeda seperti tiga pasangan lainnya.
- Berhenti menyimpulkan pola hanya dari dua atau tiga pasangan pertama, padahal pola yang tampak cocok di awal bisa jadi hanya kebetulan dan gugur ketika diuji ke pasangan keempat atau kelima.

**Tips cara cepat**: jangan terpaku pada satu pasangan saja, tetapi bandingkan seluruh pasangan yang diberikan untuk menemukan benang merah hubungannya (apakah semuanya soal sebab-akibat, bagian-keseluruhan, atau golongan yang sama). Setelah pola umum ditemukan, barulah pola itu diuji ke pilihan jawaban yang tersedia. Ketika pasangan yang disajikan berjumlah empat atau lebih, uji pola yang kamu temukan ke SETIAP pasangan sampai pasangan terakhir sebelum menyimpulkan -- jika ada satu pasangan yang tidak cocok dengan pola mayoritas, curigai itu sebagai jebakan dan cari pola yang lebih sempit/spesifik yang tetap konsisten menaungi pasangan-pasangan lain, bukan pola yang longgar sehingga semua pasangan "kelihatan" cocok.

**Kesimpulan:** Analogi induktif menuntutmu menarik pola dari beberapa pasangan kata sekaligus dan menguji pola itu ke semua pasangan yang ada, bukan berhenti di dua-tiga pasangan pertama, agar tidak terjebak pasangan yang menyimpang.

**Contoh Soal:** Perhatikan pasangan kata berikut: DOKTER : STETOSKOP, POLISI : BORGOL, KOKI : PISAU, PETANI : CANGKUL, dan PENGACARA : DASI. Manakah pasangan yang TIDAK mengikuti pola hubungan yang sama dengan pasangan-pasangan lainnya?

- A. DOKTER : STETOSKOP
- B. POLISI : BORGOL
- C. KOKI : PISAU
- D. PETANI : CANGKUL
- E. PENGACARA : DASI

**Pembahasan:**

**Diketahui:** Lima pasangan kata: DOKTER : STETOSKOP, POLISI : BORGOL, KOKI : PISAU, PETANI : CANGKUL, dan PENGACARA : DASI.

**Ditanya:** Pasangan mana (opsi A-E) yang TIDAK mengikuti pola hubungan yang sama dengan pasangan-pasangan lainnya?

**Jawab:** Opsi A, B, C, dan D (DOKTER : STETOSKOP, POLISI : BORGOL, KOKI : PISAU, PETANI : CANGKUL) sama-sama menunjukkan hubungan profesi dengan alat kerja utama yang secara fungsional dipakai langsung untuk menjalankan tugas inti profesi tersebut: dokter memeriksa pasien dengan stetoskop, polisi mengamankan tersangka dengan borgol, koki mengolah bahan makanan dengan pisau, dan petani mengolah lahan dengan cangkul. Sementara itu opsi E (PENGACARA : DASI) adalah jebakan, sebab dasi hanyalah atribut pakaian/penampilan, bukan alat yang dipakai untuk menjalankan tugas inti profesi pengacara (yaitu membela/mendampingi klien secara hukum). Pola induktif yang konsisten pada empat pasangan lainnya adalah "profesi dengan alat kerja fungsional yang langsung dipakai untuk menjalankan tugas utama profesi", sehingga PENGACARA : DASI harus disingkirkan dari kelompok tersebut. Jadi jawabannya adalah E.', 2),
('b0000000-0000-4000-8000-060200000000', 'Analogi Deklaratif', '**Definisi:** Analogi deklaratif adalah bentuk analogi yang hubungannya berupa pernyataan fakta atau definisi yang sifatnya langsung dan baku antara dua kata, misalnya hubungan bagian dengan keseluruhannya (jari : tangan), atau hubungan sesuatu dengan tempat asalnya yang sudah pasti secara definisi.

**Cara Kerja / Langkah Pengerjaan:**
1. Identifikasi hubungan pasangan A : B pada soal -- apakah berupa fakta/definisi baku (bagian-keseluruhan, tempat asal, dsb) yang berlaku tanpa syarat tambahan apa pun.
2. Coba ubah pasangan A : B menjadi kalimat statis seperti "A adalah bagian dari B" atau "A adalah jenis dari B" tanpa memakai kata kerja aktif.
3. Bandingkan tiap opsi jawaban dengan mencoba pola kalimat statis yang sama, cari opsi yang punya jenis hubungan fakta sejenis (bagian-keseluruhan dengan bagian-keseluruhan, bukan dicampur sebab-akibat atau alat-profesi).
4. Uji opsi yang meragukan dengan mengubahnya jadi kalimat "A menggunakan/menghasilkan/menyebabkan B" -- jika kalimat itu terasa dipaksakan atau butuh kata kerja aktif supaya masuk akal, berarti itu hubungan fungsional, singkirkan.
5. Pilih opsi yang tetap benar sebagai pernyataan statis tanpa syarat tambahan, sepadan secara struktural dengan pola A : B pada soal.

**Rumus & Poin Kunci:**
- Ciri khas analogi deklaratif: hubungannya tetap benar tanpa syarat/konteks tambahan apa pun (fakta baku) -- berbeda dari analogi fungsional yang sifatnya kontekstual dan butuh kata kerja aktif seperti "menggunakan", "menghasilkan", atau "menyebabkan" untuk menjelaskannya.
- Analogi deklaratif menitikberatkan pada hubungan yang "sudah pasti benar secara definisi" sehingga tidak banyak ditafsirkan ulang, berbeda dengan analogi biasa yang polanya bisa bervariasi (sebab-akibat, alat-profesi, dsb).

**Kesalahan Umum / Jebakan:**
- Opsi jawaban yang tampak mirip karena sama-sama "berpasangan secara wajar", padahal sebenarnya berjenis hubungan fungsional (alat-profesi, sebab-akibat, tempat-produk), bukan hubungan bagian-keseluruhan atau fakta baku seperti pada soal.
- Contoh: untuk pasangan RODA : MOBIL (bagian-keseluruhan, deklaratif), opsi seperti SOPIR : MOBIL (pelaku dengan objek yang dikendarainya) atau BENSIN : MOBIL (bahan bakar dengan objek yang digerakkannya) sekilas terasa "berhubungan erat dengan mobil", tetapi keduanya BUKAN hubungan bagian-keseluruhan, sehingga harus disingkirkan meskipun topiknya sama-sama tentang mobil.

**Tips cara cepat**: tanyakan pada diri sendiri, "apakah hubungan A dan B ini adalah fakta baku yang tidak terbantahkan?" Jika ya, cari pasangan opsi jawaban yang punya hubungan fakta sejenis (bagian-keseluruhan dengan bagian-keseluruhan, bukan dicampur dengan sebab-akibat), karena analogi deklaratif menuntut kesamaan jenis hubungan yang presisi, bukan sekadar mirip-mirip. Uji tambahan yang ampuh untuk membedakan dari analogi fungsional: coba ubah pasangan A : B menjadi kalimat "A menggunakan/menghasilkan/menyebabkan B" -- jika kalimat itu terasa dipaksakan atau butuh kata kerja aktif untuk masuk akal, berarti itu hubungan fungsional, bukan deklaratif. Sebaliknya, jika pasangan itu cukup dijelaskan dengan kalimat statis seperti "A adalah bagian dari B" atau "A adalah jenis dari B" tanpa kata kerja aktif, itu tandanya hubungan deklaratif yang sesungguhnya.

**Kesimpulan:** Analogi deklaratif menuntut hubungan fakta baku yang berlaku tanpa syarat apa pun, sehingga kunci membedakannya dari jebakan analogi fungsional adalah menguji apakah pasangan kata butuh kata kerja aktif untuk dijelaskan atau tidak.

**Contoh Soal:** BAB : BUKU = ... Manakah pasangan berikut yang merupakan analogi deklaratif sejati (bagian-keseluruhan), sepadan dengan pola BAB : BUKU?

- A. PENULIS : BUKU
- B. BABAK : DRAMA
- C. PERCETAKAN : BUKU
- D. PEMBACA : BUKU
- E. PENERBIT : BUKU

**Pembahasan:**

**Diketahui:** Hubungan BAB : BUKU adalah bagian dengan keseluruhannya secara definitif -- bab adalah unit pembagi isi dari sebuah buku, sebuah fakta struktural yang selalu benar tanpa syarat tambahan.

**Ditanya:** Pasangan mana (opsi A-E) yang merupakan analogi deklaratif sejati, sepadan dengan pola BAB : BUKU?

**Jawab:** Opsi A (PENULIS : BUKU) adalah jebakan analogi fungsional, karena penulis bukan bagian dari buku, melainkan pelaku yang menghasilkan/menciptakan buku (butuh kata kerja aktif "menulis" atau "menghasilkan" untuk menjelaskan hubungannya) -- ini sejenis dengan hubungan profesi-karya, bukan bagian-keseluruhan. Opsi C (PERCETAKAN : BUKU) juga fungsional, karena percetakan mencetak buku, bukan bagian dari buku. Opsi D (PEMBACA : BUKU) fungsional, karena pembaca membaca buku, bukan bagian dari buku. Opsi E (PENERBIT : BUKU) juga fungsional, karena penerbit menerbitkan buku, bukan bagian dari buku. Opsi B (BABAK : DRAMA) adalah jawaban yang tepat, karena babak adalah unit pembagi isi dari sebuah drama, persis sepadan secara struktural dengan bab yang menjadi unit pembagi isi buku -- keduanya sama-sama hubungan bagian dengan keseluruhan yang berlaku baku tanpa perlu kata kerja aktif untuk menjelaskannya. Ini menegaskan bahwa memeriksa apakah hubungan bisa dijelaskan tanpa kata kerja aktif adalah cara efektif memilah analogi deklaratif dari analogi fungsional yang menyamar mirip. Jadi jawabannya adalah B.', 3),
('b0000000-0000-4000-8000-060200000000', 'Kelompok Kata', '**Definisi:** Soal kelompok kata meminta kamu menemukan satu kata yang paling tidak sejenis atau tidak sekelompok dibandingkan kata-kata lain dalam daftar pilihan.

**Cara Kerja / Langkah Pengerjaan:**
1. Cek seluruh kata yang ada (biasanya 4-5 kata), lalu cari benang merah kesamaan di antara sebagian besar kata -- biasanya 3-4 kata sudah membentuk pola yang sama.
2. Beri "nama kategori" yang paling spesifik untuk kata-kata yang sepola itu, misalnya bukan cuma "sifat baik", tapi lebih spesifik lagi seperti "nilai moral/karakter" atau "jenis emosi".
3. Untuk kategori abstrak (sifat, konsep, nilai), bandingkan tiap kata terhadap nama kategori spesifik itu, jangan cuma berhenti di kategori benda konkret yang kasatmata (alat musik, hewan, alat tulis).
4. Simpulkan kata yang menyimpang dari pola mayoritas sebagai jawaban, meskipun secara sekilas kata itu tampak serumpun dengan yang lain.

**Rumus & Poin Kunci:**
- Kesamaan kelompok bisa berupa kesamaan kategori (sama-sama alat musik, sama-sama profesi, sama-sama jenis hewan), kesamaan fungsi (sama-sama alat tulis), atau kesamaan sifat (sama-sama bersifat cair).
- Pada level lanjutan, pengelompokan bisa berdasarkan kategori ABSTRAK berupa sifat, konsep, atau nilai yang dikandung kata-kata tersebut, bukan cuma kategori benda konkret.
- Level OTO Bappenas sering menyandingkan kata-kata abstrak untuk menguji ketajaman membedah sub-kategori konsep (misalnya nilai moral vs kemampuan kognitif, atau emosi vs hasil proses berpikir), bukan sekadar mengenali kategori benda yang kasatmata.

**Kesalahan Umum / Jebakan:**
- Contoh: dalam daftar JUJUR, ADIL, DISIPLIN, RAMAH, dan CERDAS, empat kata pertama sama-sama tergolong sifat/nilai moral atau karakter (virtue), sedangkan CERDAS menyimpang karena tergolong kemampuan kognitif/intelektual -- jebakannya adalah mengira semuanya "sama-sama sifat baik" tanpa membedah kategori abstrak yang lebih spesifik (moral vs kognitif).
- Contoh lain: KEMARAHAN, KESEDIHAN, KEBAHAGIAAN, dan KECEMASAN tergolong konsep emosi, sedangkan KEBIJAKSANAAN tergolong konsep hasil proses berpikir/pengalaman, bukan emosi, walaupun sama-sama kata benda abstrak berakhiran "ke-an".
- Terburu-buru menjawab kata yang "terasa aneh" secara sekilas tanpa lebih dulu mengecek benang merah kesamaan mayoritas kata yang ada.

**Tips cara cepat**: jangan buru-buru menjawab kata yang "terasa aneh" secara sekilas. Cek dulu 4-5 kata yang ada, cari benang merah kesamaan di antara sebagian besar kata (biasanya 3-4 kata sudah membentuk pola yang sama), baru simpulkan kata mana yang menyimpang dari pola mayoritas tersebut. Kadang jebakannya adalah kata yang terlihat berhubungan tapi sebenarnya beda kategori (misalnya termasuk "alat" vs termasuk "bahan"). Untuk kelompok kata abstrak, coba beri "nama kategori" yang paling spesifik untuk keempat kata yang sama polanya (misalnya bukan cuma "sifat baik", tapi lebih spesifik lagi seperti "nilai moral/karakter" atau "jenis emosi") -- semakin spesifik nama kategorinya, semakin mudah menemukan kata yang sebenarnya masuk sub-kategori berbeda meskipun tampak serumpun secara umum.

**Kesimpulan:** Menemukan kata yang tidak sekelompok memerlukan kejelian membedah kesamaan hingga ke sub-kategori yang paling spesifik, terutama saat kategorinya bersifat abstrak seperti sifat, nilai, atau konsep.

**Contoh Soal:** Manakah kata berikut yang TIDAK sekelompok dengan kata-kata lainnya?

- A. OPTIMISME
- B. AMBISI
- C. KEGIGIHAN
- D. KETEKUNAN
- E. KEBERANIAN

**Pembahasan:**

**Diketahui:** Lima kata: OPTIMISME, AMBISI, KEGIGIHAN, KETEKUNAN, KEBERANIAN.

**Ditanya:** Kata mana (opsi A-E) yang TIDAK sekelompok dengan kata-kata lainnya?

**Jawab:** Sekilas kelima kata tampak "sama-sama sifat positif yang mendukung kesuksesan seseorang", tetapi perlu dibedah lebih spesifik. Opsi C (KEGIGIHAN), D (KETEKUNAN), dan E (KEBERANIAN) adalah sifat/karakter yang berhubungan dengan cara seseorang bertindak atau berproses menghadapi kesulitan (karakter dalam berjuang). Opsi A (OPTIMISME) juga termasuk kategori ini karena merupakan sikap mental positif dalam menghadapi proses/masa depan. Opsi B (AMBISI) berbeda secara mendasar: ambisi adalah dorongan/keinginan kuat untuk mencapai suatu tujuan atau target, bukan cara seseorang menjalani prosesnya -- ambisi bisa ada tanpa kegigihan, ketekunan, keberanian, atau optimisme, dan sebaliknya. Dengan kata lain, empat kata lainnya menggambarkan "kualitas karakter dalam menjalani proses", sedangkan AMBISI menggambarkan "arah/dorongan menuju tujuan", sehingga AMBISI adalah kata yang tidak sekelompok. Jadi jawabannya adalah B.', 4);

update chapters set mindmap = '# Verbal #2
## Analogi
- Pola A : B -> ubah jadi kalimat pendek
- Jenis hubungan: tempat-produk, alat-profesi, sebab-akibat, fungsi, ukuran, golongan
- Uji pola kalimat ke opsi, eliminasi yang tidak cocok
## Analogi Induktif
- Beberapa contoh pasangan kata sejenis
- Tarik pola umum dari seluruh pasangan
- Terapkan pola ke pasangan/opsi berikutnya
## Analogi Deklaratif
- Hubungan berupa fakta/definisi baku (mis. bagian-keseluruhan)
- Tidak banyak ditafsirkan ulang
- Cocokkan jenis hubungan secara presisi
## Kelompok Kata
- Cari 1 kata yang tidak sekelompok
- Kesamaan: kategori, fungsi, atau sifat
- Temukan pola mayoritas dulu, baru simpulkan kata menyimpang' where id = 'b0000000-0000-4000-8000-060200000000';

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, order_index) values
('b0000000-0000-4000-8000-060200000000', 'GURU : MURID = DOKTER : ...', 'Pasien', 'Rumah Sakit', 'Obat', 'Suster', 'Stetoskop', 'A', 'Guru berhubungan dengan murid sebagai pihak yang dilayani/dibimbing dalam proses belajar-mengajar. Pola yang sama berlaku pada dokter yang melayani/menangani pasien. Rumah sakit, obat, suster, dan stetoskop hanyalah sarana pendukung, bukan pihak yang dilayani langsung.', 'easy', 1),
('b0000000-0000-4000-8000-060200000000', 'PETANI : CANGKUL = TUKANG KAYU : ... (pilih alat yang paling menentukan pekerjaan utamanya, bukan sekadar alat yang ia miliki)', 'Palu', 'Paku', 'Gergaji', 'Kayu', 'Meteran', 'C', 'Cangkul adalah alat utama petani untuk mengolah tanah, yaitu aktivitas inti dari pekerjaannya. Pola yang sama berlaku pada tukang kayu: gergaji adalah alat utama untuk memotong/membentuk kayu, aktivitas inti dari pekerjaannya. Palu dan meteran memang juga dipakai tukang kayu, tetapi keduanya alat pendukung (memaku, mengukur), bukan alat yang paling mendefinisikan pekerjaan inti memotong/membentuk kayu. Paku dan kayu adalah bahan, bukan alat.', 'medium', 2),
('b0000000-0000-4000-8000-060200000000', 'NELAYAN : JALA = PELUKIS : ... (pilih alat yang paling menentukan hasil karya utamanya, bukan sekadar bahan atau media)', 'Kanvas', 'Cat', 'Pensil', 'Kuas', 'Palet', 'D', 'Jala adalah alat utama nelayan untuk menangkap ikan, yaitu aktivitas inti profesinya. Pola yang sama berlaku pada pelukis: kuas adalah alat utama untuk membentuk goresan dan karya lukisannya. Kanvas dan palet hanyalah media/wadah pendukung, cat adalah bahan, dan pensil lazimnya dipakai untuk sketsa awal saja, bukan alat utama melukis.', 'medium', 3),
('b0000000-0000-4000-8000-060200000000', 'KEBUN : SAYUR = SAWAH : ... (pilih produk yang paling menjadi ciri khas dan hasil utama dari tempat tersebut, bukan sekadar sesuatu yang bisa ditemukan di sana)', 'Traktor', 'Padi', 'Jerami', 'Petani', 'Air', 'B', 'Kebun identik dengan sayur sebagai produk utama/khasnya, sebagaimana sawah identik dengan padi sebagai produk utama/khasnya. Jerami hanyalah hasil sampingan (sisa batang padi setelah panen), bukan produk utama yang menjadi tujuan bertani, sehingga meski berasal dari sawah, jerami bukan jawaban yang tepat. Traktor dan air adalah sarana pendukung, dan petani adalah pelaku, bukan produk.', 'hard', 4),
('b0000000-0000-4000-8000-060200000000', 'Perhatikan pola berlapis berikut: LAPAR : MAKAN setara dengan KELAPARAN : MELAHAP (tingkat kebutuhan yang lebih ekstrem melahirkan tindakan yang lebih intens pula). Berdasarkan pola berlapis tersebut (jenis kebutuhan fisiologis DAN tingkat intensitasnya), lengkapi: HAUS : MINUM setara dengan ... : ...', '(Dahaga, Teguk)', '(Kehausan, Menenggak)', '(Haus, Minum)', '(Lapar, Melahap)', '(Keringat, Mengelap)', 'B', 'Pola pada LAPAR : MAKAN dengan KELAPARAN : MELAHAP berlapis dua: pertama, jenis kebutuhan fisiologisnya harus sama (rasa lapar); kedua, tingkat intensitas kedua sisi pasangan harus naik bersama-sama (dari "lapar" yang biasa ke "kelaparan" yang ekstrem, dari "makan" yang netral ke "melahap" yang intens/rakus). Opsi A (Dahaga, Teguk) gagal secara intensitas karena "dahaga" hanya sinonim dari haus (bukan tingkat ekstrem) dan "teguk" adalah tindakan minum dalam ukuran kecil, bukan tindakan yang lebih intens. Opsi C (Haus, Minum) tidak menaikkan intensitas sama sekali, sama seperti pasangan dasar HAUS : MINUM tanpa ada eskalasi, sehingga tidak sepadan dengan pola berlapis KELAPARAN : MELAHAP. Opsi D (Lapar, Melahap) salah jenis kebutuhan fisiologis karena membahas rasa lapar, bukan haus. Opsi E (Keringat, Mengelap) sama sekali bukan tentang kebutuhan-tindakan pemenuhan, melainkan hasil-tindakan membersihkan, sehingga tidak sejenis. Opsi B (Kehausan, Menenggak) tepat karena "kehausan" adalah tingkat ekstrem dari "haus" (sejajar dengan "kelaparan" dari "lapar"), dan "menenggak" adalah tindakan minum yang jauh lebih intens/tergesa dibanding "minum" biasa (sejajar dengan "melahap" dari "makan"), sehingga polanya sama-sama berlapis pada jenis kebutuhan dan tingkat intensitasnya. Jadi jawabannya adalah B.', 'hard', 5),
('b0000000-0000-4000-8000-060200000000', 'Perhatikan pasangan kata berikut: AWAN : HUJAN, API : ABU, dan MENDUNG : GERIMIS. Pola hubungan yang konsisten pada ketiga pasangan tersebut adalah...', 'Golongan dengan anggotanya', 'Suatu keadaan/benda dengan hasil atau akibat yang ditimbulkannya', 'Alat dengan penggunanya', 'Tempat dengan produk khasnya', 'Sinonim antar kata', 'B', 'Ketiga pasangan kata menunjukkan pola sebab-akibat: awan menghasilkan hujan, api meninggalkan abu sebagai sisa pembakaran, dan mendung menjadi tanda datangnya gerimis. Ini adalah contoh analogi induktif karena pola ditarik dari beberapa pasangan sejenis sekaligus.', 'medium', 6),
('b0000000-0000-4000-8000-060200000000', 'Perhatikan pasangan kata berikut: MERPATI : BURUNG, KOMODO : REPTIL, PAUS : MAMALIA, dan KELELAWAR : BURUNG. Manakah pasangan yang TIDAK mengikuti pola hubungan yang sama dengan pasangan-pasangan lainnya?', 'MERPATI : BURUNG', 'KOMODO : REPTIL', 'PAUS : MAMALIA', 'KELELAWAR : BURUNG', 'Semua pasangan sudah tepat', 'D', 'Pola pada tiga pasangan MERPATI : BURUNG, KOMODO : REPTIL, dan PAUS : MAMALIA adalah anggota dengan golongan/kelas biologis tempatnya digolongkan secara taksonomi yang benar. Pasangan KELELAWAR : BURUNG tampak masuk akal secara sekilas karena kelelawar bisa terbang seperti burung, namun secara taksonomi kelelawar tergolong MAMALIA (menyusui, berbulu tipis, dan melahirkan), bukan burung (yang berkembang biak dengan bertelur dan berbulu unggas), sehingga pasangan ini adalah jebakan yang menyalahi pola golongan biologis yang benar meski tampak mirip topik. Opsi E salah karena memang ada satu pasangan yang menyimpang. Jadi jawabannya adalah D.', 'hard', 7),
('b0000000-0000-4000-8000-060200000000', 'Perhatikan pasangan kata berikut: KOPRAL : SERSAN, SERSAN : LETNAN, LETNAN : KAPTEN, dan KAPTEN : JENDERAL. Manakah pasangan yang TIDAK mengikuti pola hubungan yang sama dengan pasangan-pasangan lainnya?', 'KOPRAL : SERSAN', 'SERSAN : LETNAN', 'LETNAN : KAPTEN', 'KAPTEN : JENDERAL', 'Semua pasangan sudah tepat', 'D', 'Tiga pasangan pertama (KOPRAL : SERSAN, SERSAN : LETNAN, LETNAN : KAPTEN) menunjukkan pola pangkat yang lebih rendah menuju satu tingkat tepat di atasnya secara berurutan tanpa melompati jenjang mana pun. Pasangan KAPTEN : JENDERAL tampak mengikuti tema "pangkat rendah ke pangkat tinggi" yang sama, tetapi sebenarnya melompati beberapa jenjang pangkat di antaranya (mayor, letnan kolonel, kolonel, brigadir jenderal, dan seterusnya sebelum jenderal), sehingga bukan hubungan "satu tingkat tepat di atasnya" seperti tiga pasangan lainnya, melainkan lompatan jauh yang menyalahi pola berjenjang presisi tersebut. Opsi E salah karena ada satu pasangan yang menyimpang. Jadi jawabannya adalah D.', 'hard', 8),
('b0000000-0000-4000-8000-060200000000', 'Perhatikan pasangan kata berikut: PEMAHAT : PATUNG, PENULIS : NASKAH, PENJAHIT : BAJU, dan ARSITEK : GEDUNG. Manakah pasangan yang TIDAK mengikuti pola hubungan yang sama dengan pasangan-pasangan lainnya?', 'PEMAHAT : PATUNG', 'PENULIS : NASKAH', 'PENJAHIT : BAJU', 'ARSITEK : GEDUNG', 'Semua pasangan sudah tepat', 'D', 'Pola pada PEMAHAT : PATUNG, PENULIS : NASKAH, dan PENJAHIT : BAJU adalah profesi dengan karya yang ia hasilkan/bentuk secara langsung dengan keahliannya sendiri hingga menjadi wujud akhir: pemahat memahat langsung patungnya, penulis menulis langsung naskahnya, penjahit menjahit langsung bajunya. Pasangan ARSITEK : GEDUNG tampak sejenis karena sama-sama "profesi dengan hasil karya", namun sebenarnya berbeda pola: arsitek merancang desain/blueprint gedung, sedangkan wujud fisik gedungnya dibangun oleh pekerja konstruksi/tukang bangunan, bukan dibuat langsung oleh tangan arsitek sendiri seperti tiga profesi lainnya. Ini jebakan berlapis karena butuh membedakan "profesi yang merancang" dari "profesi yang langsung membuat wujud akhir karyanya" -- dua hal yang sekilas tampak sama sebagai "profesi dengan karya" tapi sebenarnya berbeda proses penciptaannya. Opsi E salah karena ada satu pasangan yang menyimpang. Jadi jawabannya adalah D.', 'hard', 9),
('b0000000-0000-4000-8000-060200000000', 'JARI : TANGAN = ...', 'Ranting : Pohon', 'Meja : Kursi', 'Guru : Sekolah', 'Air : Sungai', 'Dokter : Pasien', 'A', 'Hubungan JARI : TANGAN adalah hubungan bagian dengan keseluruhannya, sebuah fakta/definisi yang baku (analogi deklaratif). Pola yang sama terdapat pada RANTING : POHON, karena ranting adalah bagian dari pohon secara definitif, bukan sekadar berdekatan atau berfungsi bersama seperti pada pasangan lainnya.', 'medium', 10),
('b0000000-0000-4000-8000-060200000000', 'DAUN : POHON = ... (pilih pasangan yang benar-benar merupakan hubungan bagian dengan keseluruhan, bukan sekadar berkaitan erat)', 'Penulis : Buku', 'Halaman : Buku', 'Perpustakaan : Buku', 'Pembaca : Buku', 'Sampul : Penerbit', 'B', 'Hubungan DAUN : POHON adalah bagian dengan keseluruhannya, fakta baku (analogi deklaratif). Pola yang sama terdapat pada HALAMAN : BUKU, karena halaman adalah bagian dari buku secara definitif. Penulis : Buku dan Pembaca : Buku adalah hubungan fungsional (pelaku dengan objek yang ia tulis/baca), Perpustakaan : Buku adalah tempat penyimpanan bukan bagian, dan Sampul : Penerbit justru terbalik strukturnya (sampul adalah bagian dari buku, bukan bagian dari penerbit), sehingga tidak sepadan sama sekali dengan pola bagian-keseluruhan.', 'medium', 11),
('b0000000-0000-4000-8000-060200000000', 'Perhatikan pola berlapis berikut: RODA adalah bagian paling menentukan/khas dari MOBIL (kendaraan darat), dan SAYAP adalah bagian paling menentukan/khas dari PESAWAT (kendaraan udara) -- keduanya sama-sama bagian struktural utama yang menjadi identitas moda transportasi tersebut. Berdasarkan pola berlapis itu (hubungan bagian-keseluruhan DAN kekhasannya sebagai identitas utama moda transportasi), bagian manakah yang paling tepat melengkapi pola untuk KAPAL LAUT?', 'Nakhoda', 'Kemudi', 'Lambung', 'Pelabuhan', 'Layar', 'C', 'Pola RODA : MOBIL dan SAYAP : PESAWAT berlapis dua syarat: (1) hubungan bagian dengan keseluruhan yang bersifat baku/definitif, dan (2) bagian tersebut adalah struktur paling khas yang menjadi identitas utama moda transportasi itu -- roda adalah ciri utama kendaraan darat beroda, sayap adalah ciri utama pesawat terbang bersayap. Opsi A (Nakhoda) gugur di syarat pertama karena nakhoda adalah pelaku/orang yang mengendalikan kapal, bukan bagian fisik dari kapal. Opsi D (Pelabuhan) juga gugur di syarat pertama karena pelabuhan adalah tempat, bukan bagian dari kapal. Opsi B (Kemudi) memenuhi syarat pertama (kemudi memang bagian dari kapal) tetapi gugur di syarat kedua, sebab kemudi juga terdapat pada mobil dan pesawat sehingga bukan struktur yang secara khas mendefinisikan kapal laut. Opsi E (Layar) memenuhi syarat pertama untuk sebagian kapal, tetapi gugur di syarat kedua karena layar hanya ada pada kapal layar tradisional, tidak universal pada semua kapal laut modern (kapal motor, tanker, kapal tunda tidak memiliki layar), sehingga tidak bisa menjadi identitas utama "kapal laut" secara umum. Opsi C (Lambung) tepat karena lambung adalah struktur badan utama yang menentukan bentuk dan menjadi identitas fisik setiap kapal laut tanpa terkecuali, sepadan penuh dengan roda pada mobil dan sayap pada pesawat. Jadi jawabannya adalah C.', 'hard', 12),
('b0000000-0000-4000-8000-060200000000', 'Manakah kata berikut yang TIDAK sekelompok dengan kata-kata lainnya?', 'Ayam', 'Ular', 'Buaya', 'Komodo', 'Kadal', 'A', 'Ular, buaya, komodo, dan kadal semuanya termasuk golongan reptil. Ayam termasuk golongan unggas/burung, sehingga tidak sekelompok dengan keempat kata lainnya.', 'easy', 13),
('b0000000-0000-4000-8000-060200000000', 'Manakah kata berikut yang TIDAK sekelompok dengan kata-kata lainnya?', 'Pensil', 'Spidol', 'Krayon', 'Bolpoin', 'Penghapus', 'E', 'Pensil, spidol, krayon, dan bolpoin sama-sama tergolong alat tulis/gambar yang berfungsi untuk membuat goresan atau tulisan di atas media (kertas, papan, dsb). Penghapus berbeda kategori fungsinya: penghapus digunakan untuk menghilangkan/menghapus goresan atau tulisan, bukan membuatnya, sehingga fungsinya berlawanan dengan keempat alat lainnya meskipun sama-sama berada dalam kategori umum "alat tulis-menulis".', 'hard', 14),
('b0000000-0000-4000-8000-060200000000', 'Manakah kata berikut yang TIDAK sekelompok dengan kata-kata lainnya?', 'Biola', 'Gitar', 'Piano', 'Harmonika', 'Metronom', 'E', 'Sekilas Piano dan Harmonika bisa terasa "berbeda" dari Biola dan Gitar karena cara memainkannya berlainan (Biola dan Gitar dimainkan dengan cara digesek/dipetik pada senar/dawai, sedangkan Piano ditekan tutsnya dan Harmonika ditiup). Namun perbedaan cara memainkan ini bukan dasar pengelompokan yang tepat, sebab Biola, Gitar, Piano, dan Harmonika sama-sama tergolong alat musik yang fungsinya menghasilkan nada/melodi sebagai bagian dari sebuah komposisi musik. Metronom sama sekali berbeda kategori fungsinya: metronom adalah alat bantu yang menghasilkan ketukan/tempo teratur untuk memandu musisi berlatih, bukan alat yang menghasilkan nada atau melodi musik itu sendiri, sehingga secara fungsional ia adalah alat bantu pendukung latihan, bukan alat musik. Jebakan pada soal ini adalah tergoda memilih Piano atau Harmonika karena cara memainkannya berbeda dari Biola/Gitar, padahal pembeda kelompok yang sesungguhnya adalah fungsi menghasilkan nada musik (dimiliki keempatnya) versus fungsi menghasilkan ketukan tempo saja (hanya dimiliki Metronom). Jadi jawabannya adalah E.', 'hard', 15);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, order_index) values
('b0000000-0000-4000-8000-060200000000', 'MATA : TELINGA = ...', 'Lutut : Siku', 'Jari : Tangan', 'Kaki : Paha', 'Perut : Dada', 'Lidah : Hidung', 'E', 'Mata dan telinga adalah dua organ indera yang berbeda fungsi tetapi setingkat, yaitu sama-sama panca indera di kepala. Pola yang sepadan adalah lidah (indera pengecap) dan hidung (indera penciuman), yang juga merupakan dua organ indera berbeda fungsi namun setingkat.', 'medium', 16),
('b0000000-0000-4000-8000-060200000000', 'JURANG : TEBING = ...', 'Kilat : Petir', 'Laut : Pantai', 'Kerikil : Karang', 'Ranting : Pohon', 'Mendung : Awan', 'B', 'Jurang memiliki tebing sebagai dinding/batas tepinya. Pola yang sama berlaku pada laut, yang memiliki pantai sebagai batas/tepinya.', 'medium', 17),
('b0000000-0000-4000-8000-060200000000', 'TELUR : BUTIR = ...', 'Kilogram : Daging', 'Pisang : Tandan', 'Bawang : Siung', 'Lembar : Kertas', 'Kain : Meter', 'C', 'Butir adalah satuan hitung untuk satu buah telur. Pola yang sama berlaku pada bawang, yang satuan hitungnya adalah siung.', 'medium', 18),
('b0000000-0000-4000-8000-060200000000', 'BATA : TANAH LIAT = ...', 'Batu : Pasir', 'Bunga : Buah', 'Beton : Semen', 'Kertas : Buku', 'Tembikar : Keramik', 'C', 'Bata adalah produk yang dihasilkan dari bahan baku tanah liat. Pola yang sama berlaku pada beton, yang dihasilkan dari bahan baku utama semen.', 'medium', 19),
('b0000000-0000-4000-8000-060200000000', 'TERANG : CAHAYA = ...', 'Basah : Air', 'Botol : Air', 'Gelap : Lilin', 'Makanan : Lapar', 'Penutup : Pakaian', 'A', 'Kondisi terang ditimbulkan oleh keberadaan cahaya. Pola yang sama berlaku pada kondisi basah, yang ditimbulkan oleh keberadaan air.', 'medium', 20),
('b0000000-0000-4000-8000-060200000000', 'KARBONDIOKSIDA : FOTOSINTESA : OKSIGEN = ...', 'Batu : Keras : Arca', 'Murid : Didik : Lulus', 'Air Asin : Jemur : Garam', 'Pohon Aren : Nira : Gula', 'Kulit Kelapa : Sabut : Sapu', 'C', 'Karbondioksida (bahan baku) diproses melalui fotosintesa (proses) menjadi oksigen (hasil). Pola bahan baku-proses-hasil yang sepadan adalah air asin yang dijemur (proses penguapan) menjadi garam (hasil).', 'medium', 21),
('b0000000-0000-4000-8000-060200000000', 'LEM : SELOTIP = ...', 'Listrik : Air', 'Lilin : Lampu', 'Kunci : Pintu', 'Jam : Tangan', 'Sepeda : Roda', 'B', 'Lem dan selotip adalah dua benda berbeda wujud yang sama-sama berfungsi untuk merekatkan. Pola yang sama berlaku pada lilin dan lampu, dua benda berbeda wujud yang sama-sama berfungsi memberi penerangan.', 'medium', 22),
('b0000000-0000-4000-8000-060200000000', 'PERUSAHAAN : KARYAWAN = ...', 'Hotel : Tamu', 'Sekolah : Pelajar', 'Ujian : Pengawas', 'Bis : Penumpang', 'Universitas : Peneliti', 'B', 'Perusahaan memiliki karyawan sebagai anggota tetap yang bekerja di dalamnya. Pola yang sama berlaku pada sekolah, yang memiliki pelajar sebagai anggota tetapnya.', 'medium', 23),
('b0000000-0000-4000-8000-060200000000', 'IKLAN : BALIHO = INSKRIPSI : ...', 'Situs', 'Kitab', 'Silsilah', 'Prasasti', 'Museum', 'D', 'Iklan ditampilkan pada media baliho. Pola yang sama berlaku pada inskripsi (tulisan/pahatan), yang ditampilkan pada media prasasti.', 'medium', 24),
('b0000000-0000-4000-8000-060200000000', 'BUMI : MATAHARI = PHOBOS : ...', 'Mars', 'Venus', 'Uranus', 'Saturnus', 'Neptunus', 'A', 'Bumi mengorbit matahari sebagai pusatnya. Pola yang sama berlaku pada Phobos, satelit alami yang mengorbit planet Mars.', 'medium', 25),
('b0000000-0000-4000-8000-060200000000', 'NOMADEN : MENETAP = ...', 'Tegak : Lurus', 'Fosil : Tengkorak', 'Modern : Budaya', 'Berburu : Meramu', 'Vertikal : Horisontal', 'E', 'Nomaden dan menetap adalah pasangan kata yang berlawanan makna, yaitu gaya hidup berpindah versus tinggal tetap. Pola yang sama berlaku pada vertikal dan horisontal, dua arah yang saling berlawanan/tegak lurus.', 'medium', 26),
('b0000000-0000-4000-8000-060200000000', 'MASALAH : SOLUSI = ...', 'Ujian : Prestasi', 'Hujan : Pelangi', 'Penyakit : Obat', 'Cacian : Pujian', 'Badai : Cerah', 'C', 'Solusi digunakan untuk mengatasi masalah. Pola yang sama berlaku pada obat, yang digunakan untuk mengatasi/menyembuhkan penyakit.', 'easy', 27),
('b0000000-0000-4000-8000-060200000000', 'INSTING : NALURI = ...', 'Relatif : Hampir', 'Remang : Gelap', 'Inspirasi : Ilham', 'Instruksi : Instruktur', 'Intervensi : Sanggahan', 'C', 'Insting dan naluri adalah dua kata yang bersinonim (bermakna sama). Pola yang sama berlaku pada inspirasi dan ilham, yang juga bersinonim.', 'medium', 28),
('b0000000-0000-4000-8000-060200000000', 'BAIT : PUISI = ...', 'Paragraf : Wacana', 'Rima : Pantun', 'Kalimat : Kata', 'Bab : Novel', 'Lirik : Lagu', 'D', 'Bait adalah satuan struktural pembentuk sebuah puisi. Pola yang sama berlaku pada bab, yang merupakan satuan struktural pembentuk sebuah novel.', 'medium', 29),
('b0000000-0000-4000-8000-060200000000', 'PHOBOS : DEIMOS = CALISTO : ...', 'Amerika', 'Australia', 'Europa', 'Afrika', 'Asia', 'C', 'Phobos dan Deimos adalah dua satelit alami planet Mars. Pola yang sama berlaku pada Calisto dan Europa, yang sama-sama merupakan satelit alami planet Jupiter.', 'medium', 30),
('b0000000-0000-4000-8000-060200000000', 'TENDANG : KAKI = ...', 'Jilat : Mulut', 'Bau : Hidung', 'Pukul : Tongkat', 'Sentuh : Tangan', 'Telinga : Dengar', 'D', 'Tendang adalah tindakan yang dilakukan dengan kaki. Pola yang sama berlaku pada sentuh, yang merupakan tindakan yang dilakukan dengan tangan.', 'medium', 31);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, order_index) values
('b0000000-0000-4000-8000-060200000000', 'KANTUK : KEPENATAN = ...', 'Mimpi : Tidur', 'Marah : Kegeraman', 'Muka : Ekspresi', 'Senyum : Kegembiraan', 'D', 'Kantuk muncul sebagai akibat dari rasa kepenatan. Pola yang sama berlaku pada senyum, yang muncul sebagai akibat dari rasa kegembiraan.', 'easy', 32),
('b0000000-0000-4000-8000-060200000000', 'HUTAN : POHON = ...', 'Papan : Kayu', 'Armada : Kapal', 'Mawar : Duri', 'Rak : Buku', 'B', 'Hutan adalah tempat berkumpulnya pepohonan dalam jumlah besar. Pola yang sama berlaku pada armada, yang merupakan kesatuan berkumpulnya kapal-kapal.', 'easy', 33),
('b0000000-0000-4000-8000-060200000000', 'ANALGESIK : NYERI = ...', 'Ketahanan : Perkakas', 'Improvisasi : Musik', 'Pelumas : Gesekan', 'Kepercayaan : Tipuan', 'C', 'Analgesik adalah sesuatu yang berfungsi mengurangi rasa nyeri. Pola yang sama berlaku pada pelumas, yang berfungsi mengurangi gesekan.', 'medium', 34),
('b0000000-0000-4000-8000-060200000000', 'FILM : SKENARIO = ...', 'Drama : Panggung', 'Sandiwara : Plot', 'Teater : Acara', 'Resital : Tinjauan', 'B', 'Skenario adalah salah satu unsur pembangun sebuah film. Pola yang sama berlaku pada sandiwara, yang salah satu unsur pembangunnya adalah plot.', 'medium', 35),
('b0000000-0000-4000-8000-060200000000', 'BESAR : BERAT = ...', 'Kecil : Ringan', 'Tinggi : Kurus', 'Gadis : Cantik', 'Anak : Nakal', 'A', 'Sesuatu yang besar cenderung terasa berat. Pola yang sama berlaku pada sesuatu yang kecil, yang cenderung terasa ringan.', 'easy', 36),
('b0000000-0000-4000-8000-060200000000', 'LUCU : TERTAWA = ...', 'Kaget : Terkejut', 'Cantik : Terpesona', 'Sukses : Tercapai', 'Hati : Tergerak', 'B', 'Sesuatu yang lucu memicu reaksi tertawa. Pola yang sama berlaku pada sesuatu yang cantik, yang memicu reaksi terpesona.', 'medium', 37),
('b0000000-0000-4000-8000-060200000000', 'ACEH : SERAMBI MEKAH = ...', 'Michael Jackson : King of Pop', 'Michael Schumacher : Pembalap', 'Mikhail Gorbachev : Pemimpin Soviet', 'Madonna : Seksi', 'A', 'Aceh memiliki julukan Serambi Mekah. Pola yang sama berlaku pada Michael Jackson, yang memiliki julukan King of Pop.', 'medium', 38),
('b0000000-0000-4000-8000-060200000000', 'BALADA : LAGU = ...', 'Novel : Bab', 'Melodi : Ritme', 'Teh : Minuman', 'Siang : Hari', 'C', 'Balada adalah salah satu jenis dari lagu. Pola yang sama berlaku pada teh, yang merupakan salah satu jenis dari minuman.', 'easy', 39),
('b0000000-0000-4000-8000-060200000000', 'DISELESAIKAN : RAGU = ...', 'Dikonfirmasi : Curiga', 'Diumumkan : Pencalonan', 'Dimasukkan : Tamu', 'Disaran : Ide', 'A', 'Keraguan adalah sesuatu yang perlu diselesaikan. Pola yang sama berlaku pada kecurigaan, yang perlu dikonfirmasi.', 'medium', 40),
('b0000000-0000-4000-8000-060200000000', 'Manakah kata berikut yang TIDAK sekelompok dengan kata-kata lainnya?', 'Anjing', 'Elang', 'Buaya', 'Sapi', 'D', 'Anjing, elang, dan buaya tergolong hewan karnivora (pemakan daging). Sapi tergolong hewan herbivora, sehingga tidak sekelompok dengan ketiganya.', 'medium', 41),
('b0000000-0000-4000-8000-060200000000', 'Manakah kata berikut yang TIDAK sekelompok dengan kata-kata lainnya?', 'Sapi', 'Ayam', 'Kucing', 'Tikus', 'B', 'Sapi, kucing, dan tikus tergolong hewan mamalia (menyusui). Ayam tergolong unggas, sehingga tidak sekelompok dengan ketiganya.', 'medium', 42),
('b0000000-0000-4000-8000-060200000000', 'Manakah kata berikut yang TIDAK sekelompok dengan kata-kata lainnya?', 'Genteng', 'Tembok', 'Meja', 'Lantai', 'C', 'Genteng, tembok, dan lantai adalah bagian struktural pokok sebuah bangunan. Meja adalah perabot/furnitur, bukan bagian struktural bangunan, sehingga tidak sekelompok dengan ketiganya.', 'medium', 43),
('b0000000-0000-4000-8000-060200000000', 'Manakah kata berikut yang TIDAK sekelompok dengan kata-kata lainnya?', 'Basket', 'Bulu Tangkis', 'Tenis', 'Pingpong', 'A', 'Bulu tangkis, tenis, dan pingpong adalah olahraga yang memakai alat pemukul/raket dan net, serta bisa dimainkan tunggal maupun ganda. Basket tidak memakai alat pemukul maupun net, sehingga tidak sekelompok dengan ketiganya.', 'medium', 44);
