-- =====================================================================
-- Bank soal APLIKATIF / STUDI KASUS — Modul Wawasan Kebangsaan (M5)
-- =====================================================================
-- Mengganti soal hafalan lama dengan soal studi kasus / penalaran per bab,
-- berpijak pada materi/ringkasan modul: latar belakang & Konsensus Dasar
-- Nasional, Pancasila (sejarah & nilai), UUD 1945 & amandemen, wawasan
-- kebangsaan & peran ASN (kompetensi sosial kultural), serta makna NKRI.
-- File ini idempotent: menghapus dulu soal M5 yang ada, lalu memasukkan yang baru.
--
-- Aman untuk skema baru: attempts menyimpan salinan soal (jsonb), jadi riwayat
-- lama tidak terpengaruh; seen_questions ikut terhapus otomatis (cascade).

delete from questions where chapter_id in (
  'b0000000-0000-4000-8000-050100000000',
  'b0000000-0000-4000-8000-050200000000',
  'b0000000-0000-4000-8000-050300000000',
  'b0000000-0000-4000-8000-050400000000',
  'b0000000-0000-4000-8000-050500000000'
);

insert into questions (chapter_id, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty) values

-- ===================== BAB I: LATAR BELAKANG & KONSENSUS DASAR NASIONAL =====================
('b0000000-0000-4000-8000-050100000000',
 'Dalam sebuah upacara, seorang pembina menyebut titik awal perjalanan bangsa Indonesia sebagai negara merdeka. Tanggal yang tepat adalah...',
 '17 Agustus 1945',
 '20 Mei 1908',
 '28 Oktober 1928',
 '1 Juni 1945',
 null, 'A',
 'Indonesia merdeka sejak Proklamasi 17 Agustus 1945, yang menjadi titik awal perjalanan bangsa dengan segala dinamika politiknya.',
 'easy'),

('b0000000-0000-4000-8000-050100000000',
 'Indonesia mempertahankan keberagaman budaya, adat, bahasa, dan agama dalam satu kesatuan spirit, bukan menyeragamkannya. Karakter kebangsaan seperti ini disebut...',
 'Karakter Gesellschaft',
 'Karakter Gemeinschaft',
 'Karakter Monodualistis',
 'Karakter Individualistis',
 null, 'B',
 'Bangsa Indonesia dimaknai sebagai masyarakat dengan kesatuan spirit/karakter (Karakter Gemeinschaft); keberagaman tetap dipertahankan, bukan diseragamkan.',
 'medium'),

('b0000000-0000-4000-8000-050100000000',
 'Para tokoh yang merumuskan nilai-nilai kebangsaan sebagai landasan pembentukan dan penyelenggaraan negara Indonesia dikenal dengan sebutan...',
 'Dewan Konstituante',
 'Panitia Sembilan',
 'The Founding Fathers (para pendiri bangsa)',
 'Komite Nasional Indonesia Pusat',
 null, 'C',
 'Para pendiri bangsa (the Founding Fathers) merumuskan nilai-nilai kebangsaan sebagai landasan pembentukan dan penyelenggaraan negara.',
 'easy'),

('b0000000-0000-4000-8000-050100000000',
 'Menurut modul, Reformasi bagi bangsa Indonesia dimaknai sebagai proses...',
 'Perubahan bentuk negara kesatuan menjadi federal',
 'Kembali ke UUDS 1950 secara utuh',
 'Penghapusan seluruh lembaga negara warisan Orde Baru',
 'Reinventing, rebuilding, dan konsolidasi demokrasi, dari prosedural menuju kultural dan substantif',
 null, 'D',
 'Reformasi dimaknai sebagai proses reinventing, rebuilding, dan konsolidasi demokrasi bangsa Indonesia, dari prosedural menuju kultural dan substantif.',
 'medium'),

('b0000000-0000-4000-8000-050100000000',
 'Empat Konsensus Dasar Nasional yang perlu terus diangkat kembali adalah Pancasila, UUD NRI Tahun 1945, Bhinneka Tunggal Ika, dan...',
 'Negara Kesatuan Republik Indonesia (NKRI)',
 'Garis-Garis Besar Haluan Negara (GBHN)',
 'Wawasan Nusantara semata',
 'Konvensi ketatanegaraan',
 null, 'A',
 'Konsensus Dasar Nasional: Pancasila, UUD NRI Tahun 1945, Bhinneka Tunggal Ika, dan prinsip Negara Kesatuan Republik Indonesia (NKRI).',
 'easy'),

('b0000000-0000-4000-8000-050100000000',
 'Seorang ASN bekerja dengan rekan-rekan dari beragam suku dan agama. Sikap yang PALING mencerminkan semboyan Bhinneka Tunggal Ika adalah...',
 'Menuntut semua rekan menyeragamkan budaya dan cara beribadah',
 'Menghargai perbedaan sambil menjaga persatuan dalam satu tujuan bersama',
 'Hanya mau bekerja sama dengan yang satu suku',
 'Mengabaikan keberagaman demi efisiensi kerja',
 null, 'B',
 'Bhinneka Tunggal Ika berarti berbeda-beda tetapi tetap satu; sikap yang tepat adalah menghargai perbedaan sambil menjaga persatuan dalam tujuan bersama.',
 'medium'),

('b0000000-0000-4000-8000-050100000000',
 'Menurut modul, mengapa Konsensus Dasar Nasional perlu terus diangkat dan diperkuat kembali?',
 'Agar bentuk negara dapat diubah sewaktu-waktu',
 'Agar keberagaman dihapus demi keseragaman',
 'Untuk menjaga persatuan dan stabilitas nasional di tengah dinamika/kemelut politik',
 'Untuk menggantikan Pancasila dengan ideologi lain',
 null, 'C',
 'Konsensus Dasar Nasional perlu diangkat kembali untuk menjaga persatuan dan stabilitas nasional di tengah dinamika/kemelut politik yang mengganggu stabilitas.',
 'medium'),

('b0000000-0000-4000-8000-050100000000',
 'Semangat para pendiri bangsa (the Founding Fathers) yang paling relevan diteladani seorang ASN masa kini adalah...',
 'Mementingkan golongan sendiri di atas kepentingan bangsa',
 'Menyerah pada setiap perbedaan pendapat',
 'Menghindari musyawarah demi kecepatan',
 'Mengutamakan kepentingan bangsa dan mufakat di atas kepentingan pribadi/golongan',
 null, 'D',
 'Para pendiri bangsa mengutamakan kepentingan bangsa dan mufakat di atas kepentingan pribadi/golongan; semangat ini relevan diteladani ASN.',
 'medium'),

-- ===================== BAB II: PANCASILA (SEJARAH & NILAI) =====================
('b0000000-0000-4000-8000-050200000000',
 'Nama "Pancasila" sebagai dasar negara diusulkan dalam sidang pertama BPUPKI oleh...',
 'Ir. Soekarno, pada 1 Juni 1945',
 'Mr. Moh. Yamin, pada 29 Mei 1945',
 'Prof. R. Soepomo, pada 31 Mei 1945',
 'Drs. Moh. Hatta, pada 22 Juni 1945',
 null, 'A',
 'Nama Pancasila sebagai dasar negara diusulkan Ir. Soekarno pada sidang pertama BPUPKI tanggal 1 Juni 1945.',
 'easy'),

('b0000000-0000-4000-8000-050200000000',
 'Istilah "Pancasila" dalam kitab Sutasoma karya Mpu Tantular bermakna...',
 'Lima kesatuan wilayah Nusantara',
 'Berbatu sendi yang lima; pelaksanaan kesusilaan yang lima',
 'Lima dasar negara modern',
 'Lima prinsip pemerintahan kerajaan',
 null, 'B',
 'Dalam Sutasoma, Pancasila berarti berbatu sendi yang lima serta pelaksanaan kesusilaan yang lima.',
 'medium'),

('b0000000-0000-4000-8000-050200000000',
 'Menurut Notonegoro, nilai yang berguna bagi rohani manusia (mencakup kebenaran, keindahan, kebaikan/moral, dan religius) disebut nilai...',
 'Material',
 'Vital',
 'Kerohanian',
 'Sosiologis',
 null, 'C',
 'Notonegoro membagi nilai menjadi Material, Vital, dan Kerohanian. Nilai Kerohanian berguna bagi rohani (kebenaran, keindahan, kebaikan/moral, religius); Pancasila tergolong nilai kerohanian.',
 'medium'),

('b0000000-0000-4000-8000-050200000000',
 'Urutan kronologis yang benar terkait perumusan dan pengesahan Pancasila adalah...',
 'Piagam Jakarta (22 Juni 1945) - Pidato Soekarno (1 Juni 1945) - Pengesahan PPKI (18 Agustus 1945)',
 'Pengesahan PPKI (18 Agustus 1945) - Pidato Soekarno (1 Juni 1945) - Piagam Jakarta (22 Juni 1945)',
 'Pidato Soepomo (31 Mei 1945) - Piagam Jakarta (22 Juni 1945) - Pengesahan PPKI (17 Agustus 1945)',
 'Pidato Soekarno (1 Juni 1945) - Piagam Jakarta (22 Juni 1945) - Pengesahan PPKI (18 Agustus 1945)',
 null, 'D',
 'Urutan yang benar: pidato Soekarno mengusulkan Pancasila (1 Juni 1945); Piagam Jakarta oleh Panitia Sembilan (22 Juni 1945); pengesahan Pancasila oleh PPKI (18 Agustus 1945).',
 'hard'),

('b0000000-0000-4000-8000-050200000000',
 'Menjelang pengesahan 18 Agustus 1945, tujuh kata pada sila pertama Piagam Jakarta dihapus setelah Drs. Moh. Hatta berunding dengan sejumlah tokoh, antara lain...',
 'K.H. Wachid Hasyim',
 'Jenderal Terauchi',
 'Radjiman Wediodiningrat',
 'Mr. Moh. Yamin',
 null, 'A',
 'Drs. Moh. Hatta berunding dengan antara lain K.H. Wachid Hasyim, Ki Bagus Hadikusumo, Mr. Kasman Singadimedjo, dan Mr. Teuku M. Hasan, sehingga tujuh kata pada sila pertama disepakati dihapus.',
 'hard'),

('b0000000-0000-4000-8000-050200000000',
 'Setelah tujuh kata dihapus, rumusan sila pertama Pancasila yang sah menjadi...',
 'Ketuhanan dengan kewajiban menjalankan syariat bagi pemeluknya',
 'Ketuhanan Yang Maha Esa',
 'Kebangsaan Indonesia',
 'Keadilan sosial bagi seluruh rakyat Indonesia',
 null, 'B',
 'Setelah tujuh kata "dengan kewajiban menjalankan syariat Islam bagi pemeluk-pemeluknya" dihapus, sila pertama menjadi "Ketuhanan Yang Maha Esa".',
 'medium'),

('b0000000-0000-4000-8000-050200000000',
 'Pancasila digolongkan sebagai nilai kerohanian yang juga mengakui nilai material dan vital secara seimbang. Sikap yang mencerminkan hal ini adalah...',
 'Mengejar kekayaan materi tanpa mempedulikan moral dan spiritual',
 'Menolak sepenuhnya kebutuhan material demi rohani semata',
 'Menyeimbangkan pemenuhan kebutuhan jasmani, aktivitas, dan nilai moral/religius',
 'Mengabaikan aktivitas produktif sehari-hari',
 null, 'C',
 'Sebagai nilai kerohanian yang mengakui nilai material dan vital secara seimbang, Pancasila menuntun keseimbangan pemenuhan kebutuhan jasmani, aktivitas, dan nilai moral/religius.',
 'medium'),

('b0000000-0000-4000-8000-050200000000',
 'Pancasila secara resmi disahkan sebagai dasar negara oleh...',
 'BPUPKI pada 1 Juni 1945',
 'Panitia Sembilan pada 22 Juni 1945',
 'Konstituante pada tahun 1959',
 'PPKI pada 18 Agustus 1945',
 null, 'D',
 'Pancasila disahkan sebagai dasar negara oleh PPKI pada 18 Agustus 1945 (setelah tujuh kata pada sila pertama dihapus).',
 'medium'),

-- ===================== BAB III: UUD 1945 & AMANDEMEN =====================
('b0000000-0000-4000-8000-050300000000',
 'Setelah amandemen, pasal-pasal UUD 1945 (di luar Aturan Peralihan dan Aturan Tambahan) terdiri atas...',
 '20 Bab dan 73 Pasal',
 '16 Bab dan 37 Pasal',
 '21 Bab dan 84 Pasal',
 '18 Bab dan 71 Pasal',
 null, 'A',
 'Setelah amandemen, pasal-pasal UUD 1945 terdiri atas 20 Bab dan 73 Pasal, ditambah 3 pasal Aturan Peralihan dan 2 pasal Aturan Tambahan.',
 'medium'),

('b0000000-0000-4000-8000-050300000000',
 'Ketentuan bahwa Indonesia adalah Negara Kesatuan berbentuk Republik, dan bahwa bentuk NKRI tidak dapat diubah, berturut-turut diatur dalam...',
 'Pasal 4 ayat (1) dan Pasal 7',
 'Pasal 1 ayat (1) dan Pasal 37 ayat (5)',
 'Pasal 18 ayat (1) dan Pasal 25A',
 'Pasal 1 ayat (2) dan Pasal 18B ayat (2)',
 null, 'B',
 'Pasal 1 ayat (1) menyatakan Indonesia adalah Negara Kesatuan berbentuk Republik; Pasal 37 ayat (5) menegaskan bentuk NKRI tidak dapat diubah.',
 'medium'),

('b0000000-0000-4000-8000-050300000000',
 'Lembaga negara yang lahir sebagai hasil amandemen UUD 1945 (tidak ada sebelum amandemen) adalah...',
 'MPR, DPR, dan MA',
 'BPK dan DPA',
 'DPD, MK, dan KY',
 'KPU dan DPA',
 null, 'C',
 'Lembaga baru hasil amandemen adalah DPD, MK, dan KY. DPA justru dihapus melalui Perubahan Keempat.',
 'medium'),

('b0000000-0000-4000-8000-050300000000',
 'Urutan periodisasi konstitusi Indonesia yang benar setelah kemerdekaan adalah...',
 'Konstitusi RIS - UUD 1945 - UUDS 1950 - UUD 1945',
 'UUDS 1950 - UUD 1945 - Konstitusi RIS - UUDS 1950',
 'Konstitusi RIS - UUDS 1950 - UUD 1945 - Konstitusi RIS',
 'UUD 1945 - Konstitusi RIS - UUDS 1950 - UUD 1945 (kembali melalui Dekrit Presiden 5 Juli 1959)',
 null, 'D',
 'UUD 1945 (1945-1949), Konstitusi RIS (1949-1950), UUDS 1950 (1950-1959), lalu UUD 1945 diberlakukan kembali melalui Dekrit Presiden 5 Juli 1959.',
 'hard'),

('b0000000-0000-4000-8000-050300000000',
 'Lembaga negara yang justru DIHAPUS melalui amandemen UUD 1945 adalah...',
 'Dewan Pertimbangan Agung (DPA)',
 'Mahkamah Konstitusi (MK)',
 'Dewan Perwakilan Daerah (DPD)',
 'Komisi Yudisial (KY)',
 null, 'A',
 'Dewan Pertimbangan Agung (DPA) dihapus melalui Perubahan Keempat UUD 1945; sebaliknya MK, DPD, dan KY justru lahir dari amandemen.',
 'medium'),

('b0000000-0000-4000-8000-050300000000',
 'Salah satu hasil penting Perubahan Ketiga UUD 1945 (ditetapkan 9 November 2001) adalah...',
 'Pembatasan masa jabatan Presiden maksimal dua periode',
 'Presiden dan Wakil Presiden dipilih langsung oleh rakyat, serta lahirnya DPD, MK, dan KY',
 'Penghapusan Dewan Pertimbangan Agung (DPA)',
 'Perubahan Pasal 33 tentang sistem ekonomi',
 null, 'B',
 'Perubahan Ketiga menetapkan Presiden-Wakil Presiden dipilih langsung rakyat dan melahirkan DPD, MK, serta KY. Pembatasan masa jabatan Presiden ada pada Perubahan Pertama; penghapusan DPA pada Perubahan Keempat.',
 'hard'),

('b0000000-0000-4000-8000-050300000000',
 'UUD 1945 diberlakukan kembali menggantikan UUDS 1950 melalui...',
 'Proklamasi 17 Agustus 1945',
 'Sidang PPKI 18 Agustus 1945',
 'Dekrit Presiden 5 Juli 1959',
 'Konferensi Meja Bundar 1949',
 null, 'C',
 'Melalui Dekrit Presiden 5 Juli 1959, UUDS 1950 tidak lagi berlaku dan UUD 1945 diberlakukan kembali.',
 'medium'),

('b0000000-0000-4000-8000-050300000000',
 'Seorang tokoh mengusulkan mengubah bentuk NKRI menjadi negara federal melalui amandemen. Berdasarkan UUD 1945, usulan tersebut...',
 'Dapat dilakukan kapan saja melalui referendum daerah',
 'Dapat dilakukan oleh Presiden secara sepihak',
 'Dapat dilakukan oleh DPD sendiri',
 'Tidak dapat dilakukan, karena bentuk NKRI bersifat final (Pasal 37 ayat 5)',
 null, 'D',
 'Pasal 37 ayat (5) menegaskan bentuk Negara Kesatuan Republik Indonesia tidak dapat diubah, sehingga usulan mengubahnya menjadi federal tidak dapat dilakukan.',
 'medium'),

-- ===================== BAB IV: WAWASAN KEBANGSAAN & PERAN ASN =====================
('b0000000-0000-4000-8000-050400000000',
 'Tonggak sejarah "Kebangkitan Nasional" dalam kesadaran kebangsaan Indonesia ditandai oleh...',
 'Berdirinya Budi Utomo, 20 Mei 1908',
 'Sumpah Pemuda, 28 Oktober 1928',
 'Proklamasi Kemerdekaan, 17 Agustus 1945',
 'Pembentukan BPUPKI, 29 April 1945',
 null, 'A',
 'Budi Utomo yang berdiri pada 20 Mei 1908 menjadi tonggak awal Kebangkitan Nasional dalam kesadaran kebangsaan Indonesia.',
 'easy'),

('b0000000-0000-4000-8000-050400000000',
 'Menurut Prof. Muladi, wawasan kebangsaan adalah cara pandang bangsa Indonesia mengenai diri dan lingkungannya yang mengutamakan...',
 'Kepentingan golongan di atas kepentingan nasional',
 'Kesatuan dan persatuan wilayah, dengan integrasi nasional yang bersifat kultural',
 'Otonomi daerah tanpa keterlibatan pemerintah pusat',
 'Keseragaman budaya dan bahasa di seluruh wilayah',
 null, 'B',
 'Menurut Muladi, wawasan kebangsaan mengutamakan kesatuan dan persatuan wilayah; integrasi nasional bersifat kultural (ideologi, politik, sosial budaya, ekonomi, hankam).',
 'medium'),

('b0000000-0000-4000-8000-050400000000',
 'Berikut ini adalah bukti bahwa Indonesia menolak adanya warga kelas satu dan kelas dua, KECUALI...',
 'Bahasa nasional dipilih dari bahasa Melayu, bukan bahasa Jawa yang penuturnya mayoritas',
 'Sumpah Pemuda memadukan kebhinekaan dengan ketunggalikaan',
 'Bahasa Jawa dijadikan bahasa nasional karena penuturnya mayoritas',
 'Kemajemukan suku, adat, budaya, dan agama tetap dihormati',
 null, 'C',
 'Justru bahasa nasional dipilih dari bahasa Melayu, BUKAN bahasa Jawa meski penuturnya mayoritas. Karena itu, pernyataan bahwa bahasa Jawa dijadikan bahasa nasional adalah yang tidak tepat (KECUALI).',
 'medium'),

('b0000000-0000-4000-8000-050400000000',
 'Dasar hukum yang mewajibkan ASN bersumpah setia dan taat pada Pancasila, UUD 1945, negara, dan pemerintah serta mengutamakan kepentingan negara di atas kepentingan pribadi/golongan adalah...',
 'Permenpan-RB No. 38 Tahun 2017',
 'PP No. 11 Tahun 2017',
 'KMK No. 954/KMK.01/2019',
 'UU No. 5 Tahun 2014 Pasal 66 ayat (1)-(2)',
 null, 'D',
 'Fungsi ASN sebagai perekat dan pemersatu bangsa berlandaskan UU No. 5 Tahun 2014 Pasal 66 ayat (1)-(2): ASN wajib bersumpah setia dan taat serta mengutamakan kepentingan negara.',
 'medium'),

('b0000000-0000-4000-8000-050400000000',
 'Dalam 5 Level Profisiensi Kompetensi Sosial Kultural ASN, level dengan deskripsi "menjadi wakil pemerintah membangun hubungan sosial psikologis dengan masyarakat" (untuk pejabat eselon I dan fungsional utama) adalah...',
 'Level 5 (ahli)',
 'Level 4 (mumpuni)',
 'Level 3 (menengah)',
 'Level 1 (paham/dalam pengembangan)',
 null, 'A',
 'Level 5 (ahli) untuk eselon I dan fungsional utama: menjadi wakil pemerintah membangun hubungan sosial psikologis dengan masyarakat.',
 'hard'),

('b0000000-0000-4000-8000-050400000000',
 'Sebagai perekat dan pemersatu bangsa, sikap ASN yang tepat ketika bertugas di tengah masyarakat yang majemuk adalah...',
 'Memihak kelompok mayoritas agar tugas lebih mudah',
 'Melayani semua golongan secara adil dan menjaga persatuan tanpa diskriminasi',
 'Menghindari masyarakat yang berbeda latar belakang',
 'Menonjolkan identitas kelompoknya sendiri',
 null, 'B',
 'Sebagai perekat dan pemersatu bangsa, ASN melayani semua golongan secara adil, menjaga persatuan, dan tidak melakukan diskriminasi.',
 'medium'),

('b0000000-0000-4000-8000-050400000000',
 'Seorang pejabat mendayagunakan perbedaan latar belakang anggota timnya secara konstruktif dan kreatif demi efektivitas organisasi. Kompetensi yang ia tunjukkan adalah...',
 'Kompetensi teknis semata',
 'Kompetensi manajerial keuangan',
 'Kompetensi sosial kultural',
 'Kompetensi kebugaran fisik',
 null, 'C',
 'Mendayagunakan perbedaan secara konstruktif dan kreatif demi efektivitas organisasi merupakan wujud kompetensi sosial kultural ASN.',
 'medium'),

('b0000000-0000-4000-8000-050400000000',
 'Pemilihan bahasa Melayu (yang berkembang menjadi Bahasa Indonesia) sebagai bahasa nasional — bukan bahasa suku mayoritas — menunjukkan...',
 'Diskriminasi terhadap suku minoritas',
 'Ketidakpedulian pada persatuan bangsa',
 'Dominasi satu kelompok atas kelompok lain',
 'Semangat persatuan tanpa warga kelas satu dan kelas dua',
 null, 'D',
 'Pemilihan bahasa Melayu sebagai bahasa nasional (bukan bahasa suku mayoritas) menegaskan semangat persatuan tanpa membedakan warga kelas satu dan kelas dua.',
 'medium'),

-- ===================== BAB V: MAKNA NKRI =====================
('b0000000-0000-4000-8000-050500000000',
 'Konvensi hukum laut internasional yang menjadi rujukan satu kesatuan teritori NKRI (Sabang sampai Merauke, Miangas sampai Rote) adalah...',
 'UNCLOS 1982',
 'Konvensi Wina 1969',
 'Piagam PBB 1945',
 'Deklarasi Bangkok 1967',
 null, 'A',
 'Makna NKRI sebagai satu kesatuan teritori merujuk pada UNCLOS 1982 (United Nations Convention on the Law of the Sea).',
 'medium'),

('b0000000-0000-4000-8000-050500000000',
 'Dalam makna NKRI, "satu kesatuan bangsa" berlandaskan peristiwa sejarah...',
 'Proklamasi 1945',
 'Sumpah Pemuda 1928',
 'Kongres Pemuda I 1926',
 'Dekrit Presiden 1959',
 null, 'B',
 'Makna NKRI sebagai satu kesatuan bangsa berlandaskan Sumpah Pemuda 1928.',
 'easy'),

('b0000000-0000-4000-8000-050500000000',
 'Wawasan kebangsaan Indonesia tidak memberi tempat pada sikap...',
 'Cinta tanah air dan bangsa',
 'Kesetiakawanan sosial',
 'Patriotisme yang licik/picik (chauvinisme sempit)',
 'Penghargaan atas harkat dan martabat manusia',
 null, 'C',
 'Wawasan kebangsaan tidak memberi tempat pada patriotisme yang licik/picik; cinta tanah air diarahkan pula pada kepentingan seluruh umat manusia.',
 'easy'),

('b0000000-0000-4000-8000-050500000000',
 'Manakah pernyataan yang PALING tepat menggambarkan makna NKRI menurut modul?',
 'NKRI hanya berarti satu kesatuan wilayah geografis semata',
 'NKRI memberi ruang bagi tiap daerah membentuk ideologi sendiri',
 'NKRI adalah konsep yang dapat diubah sewaktu-waktu melalui referendum daerah',
 'NKRI mencakup satu kesatuan ideologi (Pancasila), politik, ekonomi, budaya nasional, serta sistem pertahanan keamanan yang khas',
 null, 'D',
 'Makna NKRI meliputi satu kesatuan teritori, bangsa, kepemilikan sumber kekayaan alam, ideologi (Pancasila), politik, ekonomi, budaya nasional, serta sistem hankam nasional yang khas.',
 'medium'),

('b0000000-0000-4000-8000-050500000000',
 'Prinsip "satu kesatuan kepemilikan sumber kekayaan alam" dalam makna NKRI berarti...',
 'Kekayaan alam di seluruh wilayah adalah milik bersama seluruh bangsa untuk sebesar-besar kemakmuran rakyat',
 'Kekayaan alam menjadi milik daerah penghasil semata',
 'Kekayaan alam boleh dikuasai pihak asing sepenuhnya',
 'Kekayaan alam dibagi hanya untuk kelompok tertentu',
 null, 'A',
 'Sebagai satu kesatuan, kekayaan alam di seluruh wilayah merupakan milik bersama seluruh bangsa dan dimanfaatkan untuk sebesar-besar kemakmuran rakyat.',
 'medium'),

('b0000000-0000-4000-8000-050500000000',
 'Cinta tanah air dalam wawasan kebangsaan Indonesia juga diarahkan pada...',
 'Permusuhan dengan bangsa lain',
 'Kepentingan seluruh umat manusia dan hubungan baik antarbangsa',
 'Isolasi diri dari pergaulan internasional',
 'Dominasi atas negara-negara tetangga',
 null, 'B',
 'Wawasan kebangsaan mengarahkan cinta tanah air juga pada kepentingan seluruh umat manusia serta hubungan baik antar-ras, bangsa, dan negara.',
 'medium'),

('b0000000-0000-4000-8000-050500000000',
 'Sebagai komitmen mempertahankan NKRI, pasal UUD 1945 yang tidak pernah diubah sejak amandemen adalah...',
 'Pasal 33',
 'Pasal 18',
 'Pasal 1 ayat (1)',
 'Pasal 28',
 null, 'C',
 'Pasal 1 ayat (1) UUD 1945 tidak pernah diubah sejak amandemen sebagai komitmen mempertahankan NKRI.',
 'medium'),

('b0000000-0000-4000-8000-050500000000',
 'Tindakan seorang ASN yang PALING mencerminkan wawasan kebangsaan dalam pekerjaan sehari-hari adalah...',
 'Mengutamakan kepentingan kelompok/golongannya sendiri',
 'Bersikap acuh dengan tidak peduli pada persatuan',
 'Memihak satu suku tertentu dalam pelayanan',
 'Mengutamakan kepentingan bangsa dan negara, melayani semua warga secara adil, serta menjaga persatuan',
 null, 'D',
 'Wawasan kebangsaan diwujudkan ASN dengan mengutamakan kepentingan bangsa dan negara, melayani semua warga secara adil, dan menjaga persatuan.',
 'medium')
;
